// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/auth.proto (package weladee.form.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserSessionRequest, GetUserSessionResponse, HandleOAuthCallbackRequest, HandleOAuthCallbackResponse, SendMagicLinkRequest, SendMagicLinkResponse, ValidateTokenRequest, ValidateTokenResponse } from "./auth_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Auth Service
 *
 * @generated from service weladee.form.v1.AuthService
 */
export const AuthService = {
  typeName: "weladee.form.v1.AuthService",
  methods: {
    /**
     * @generated from rpc weladee.form.v1.AuthService.SendMagicLink
     */
    sendMagicLink: {
      name: "SendMagicLink",
      I: SendMagicLinkRequest,
      O: SendMagicLinkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc weladee.form.v1.AuthService.HandleOAuthCallback
     */
    handleOAuthCallback: {
      name: "HandleOAuthCallback",
      I: HandleOAuthCallbackRequest,
      O: HandleOAuthCallbackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc weladee.form.v1.AuthService.ValidateToken
     */
    validateToken: {
      name: "ValidateToken",
      I: ValidateTokenRequest,
      O: ValidateTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc weladee.form.v1.AuthService.GetUserSession
     */
    getUserSession: {
      name: "GetUserSession",
      I: GetUserSessionRequest,
      O: GetUserSessionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

