// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file proto/form.proto (package weladee.form.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Struct, Timestamp } from "@bufbuild/protobuf";
import { PaginationRequest, PaginationResponse } from "./common_pb.ts";

/**
 * Enums
 *
 * @generated from enum weladee.form.v1.FormStatus
 */
export enum FormStatus {
  /**
   * @generated from enum value: FORM_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FORM_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: FORM_STATUS_PUBLISHED = 2;
   */
  PUBLISHED = 2,

  /**
   * @generated from enum value: FORM_STATUS_CLOSED = 3;
   */
  CLOSED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(FormStatus)
proto3.util.setEnumType(FormStatus, "weladee.form.v1.FormStatus", [
  { no: 0, name: "FORM_STATUS_UNSPECIFIED" },
  { no: 1, name: "FORM_STATUS_DRAFT" },
  { no: 2, name: "FORM_STATUS_PUBLISHED" },
  { no: 3, name: "FORM_STATUS_CLOSED" },
]);

/**
 * @generated from enum weladee.form.v1.FormTheme
 */
export enum FormTheme {
  /**
   * @generated from enum value: FORM_THEME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FORM_THEME_MINIMAL = 1;
   */
  MINIMAL = 1,

  /**
   * @generated from enum value: FORM_THEME_MIDNIGHT = 2;
   */
  MIDNIGHT = 2,

  /**
   * @generated from enum value: FORM_THEME_OCEAN = 3;
   */
  OCEAN = 3,

  /**
   * @generated from enum value: FORM_THEME_SUNSET = 4;
   */
  SUNSET = 4,

  /**
   * @generated from enum value: FORM_THEME_FOREST = 5;
   */
  FOREST = 5,

  /**
   * @generated from enum value: FORM_THEME_LAVENDER = 6;
   */
  LAVENDER = 6,
}
// Retrieve enum metadata with: proto3.getEnumType(FormTheme)
proto3.util.setEnumType(FormTheme, "weladee.form.v1.FormTheme", [
  { no: 0, name: "FORM_THEME_UNSPECIFIED" },
  { no: 1, name: "FORM_THEME_MINIMAL" },
  { no: 2, name: "FORM_THEME_MIDNIGHT" },
  { no: 3, name: "FORM_THEME_OCEAN" },
  { no: 4, name: "FORM_THEME_SUNSET" },
  { no: 5, name: "FORM_THEME_FOREST" },
  { no: 6, name: "FORM_THEME_LAVENDER" },
]);

/**
 * @generated from enum weladee.form.v1.QuestionType
 */
export enum QuestionType {
  /**
   * @generated from enum value: QUESTION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: QUESTION_TYPE_SHORT_TEXT = 1;
   */
  SHORT_TEXT = 1,

  /**
   * @generated from enum value: QUESTION_TYPE_LONG_TEXT = 2;
   */
  LONG_TEXT = 2,

  /**
   * @generated from enum value: QUESTION_TYPE_DROPDOWN = 3;
   */
  DROPDOWN = 3,

  /**
   * @generated from enum value: QUESTION_TYPE_CHECKBOXES = 4;
   */
  CHECKBOXES = 4,

  /**
   * @generated from enum value: QUESTION_TYPE_EMAIL = 5;
   */
  EMAIL = 5,

  /**
   * @generated from enum value: QUESTION_TYPE_PHONE = 6;
   */
  PHONE = 6,

  /**
   * @generated from enum value: QUESTION_TYPE_NUMBER = 7;
   */
  NUMBER = 7,

  /**
   * @generated from enum value: QUESTION_TYPE_DATE = 8;
   */
  DATE = 8,

  /**
   * @generated from enum value: QUESTION_TYPE_RATING = 9;
   */
  RATING = 9,

  /**
   * @generated from enum value: QUESTION_TYPE_OPINION_SCALE = 10;
   */
  OPINION_SCALE = 10,

  /**
   * @generated from enum value: QUESTION_TYPE_YES_NO = 11;
   */
  YES_NO = 11,

  /**
   * @generated from enum value: QUESTION_TYPE_FILE_UPLOAD = 12;
   */
  FILE_UPLOAD = 12,

  /**
   * @generated from enum value: QUESTION_TYPE_URL = 13;
   */
  URL = 13,
}
// Retrieve enum metadata with: proto3.getEnumType(QuestionType)
proto3.util.setEnumType(QuestionType, "weladee.form.v1.QuestionType", [
  { no: 0, name: "QUESTION_TYPE_UNSPECIFIED" },
  { no: 1, name: "QUESTION_TYPE_SHORT_TEXT" },
  { no: 2, name: "QUESTION_TYPE_LONG_TEXT" },
  { no: 3, name: "QUESTION_TYPE_DROPDOWN" },
  { no: 4, name: "QUESTION_TYPE_CHECKBOXES" },
  { no: 5, name: "QUESTION_TYPE_EMAIL" },
  { no: 6, name: "QUESTION_TYPE_PHONE" },
  { no: 7, name: "QUESTION_TYPE_NUMBER" },
  { no: 8, name: "QUESTION_TYPE_DATE" },
  { no: 9, name: "QUESTION_TYPE_RATING" },
  { no: 10, name: "QUESTION_TYPE_OPINION_SCALE" },
  { no: 11, name: "QUESTION_TYPE_YES_NO" },
  { no: 12, name: "QUESTION_TYPE_FILE_UPLOAD" },
  { no: 13, name: "QUESTION_TYPE_URL" },
]);

/**
 * Messages
 *
 * @generated from message weladee.form.v1.Question
 */
export class Question extends Message<Question> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string form_id = 2;
   */
  formId = "";

  /**
   * @generated from field: weladee.form.v1.QuestionType type = 3;
   */
  type = QuestionType.UNSPECIFIED;

  /**
   * @generated from field: string label = 4;
   */
  label = "";

  /**
   * @generated from field: string description = 5;
   */
  description = "";

  /**
   * @generated from field: string placeholder = 6;
   */
  placeholder = "";

  /**
   * @generated from field: bool required = 7;
   */
  required = false;

  /**
   * @generated from field: int32 order_index = 8;
   */
  orderIndex = 0;

  /**
   * @generated from field: google.protobuf.Struct options = 9;
   */
  options?: Struct;

  /**
   * @generated from field: google.protobuf.Struct validation_rules = 10;
   */
  validationRules?: Struct;

  /**
   * @generated from field: google.protobuf.Struct settings = 11;
   */
  settings?: Struct;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 12;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 13;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Question>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.Question";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "type", kind: "enum", T: proto3.getEnumType(QuestionType) },
    { no: 4, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "placeholder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "required", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "order_index", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "options", kind: "message", T: Struct },
    { no: 10, name: "validation_rules", kind: "message", T: Struct },
    { no: 11, name: "settings", kind: "message", T: Struct },
    { no: 12, name: "created_at", kind: "message", T: Timestamp },
    { no: 13, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Question {
    return new Question().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Question {
    return new Question().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Question {
    return new Question().fromJsonString(jsonString, options);
  }

  static equals(a: Question | PlainMessage<Question> | undefined, b: Question | PlainMessage<Question> | undefined): boolean {
    return proto3.util.equals(Question, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.Form
 */
export class Form extends Message<Form> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: string description = 4;
   */
  description = "";

  /**
   * @generated from field: weladee.form.v1.FormTheme theme = 5;
   */
  theme = FormTheme.UNSPECIFIED;

  /**
   * @generated from field: bool is_published = 6;
   */
  isPublished = false;

  /**
   * @generated from field: bool is_accepting_responses = 7;
   */
  isAcceptingResponses = false;

  /**
   * @generated from field: bool require_login = 8;
   */
  requireLogin = false;

  /**
   * @generated from field: bool allow_multiple_submissions = 9;
   */
  allowMultipleSubmissions = false;

  /**
   * @generated from field: bool show_progress_bar = 10;
   */
  showProgressBar = false;

  /**
   * @generated from field: string custom_thank_you_message = 11;
   */
  customThankYouMessage = "";

  /**
   * @generated from field: string redirect_url = 12;
   */
  redirectUrl = "";

  /**
   * @generated from field: google.protobuf.Struct settings = 13;
   */
  settings?: Struct;

  /**
   * @generated from field: repeated weladee.form.v1.Question questions = 14;
   */
  questions: Question[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 15;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 16;
   */
  updatedAt?: Timestamp;

  constructor(data?: PartialMessage<Form>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.Form";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "theme", kind: "enum", T: proto3.getEnumType(FormTheme) },
    { no: 6, name: "is_published", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "is_accepting_responses", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "require_login", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "allow_multiple_submissions", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "show_progress_bar", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "custom_thank_you_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "redirect_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "settings", kind: "message", T: Struct },
    { no: 14, name: "questions", kind: "message", T: Question, repeated: true },
    { no: 15, name: "created_at", kind: "message", T: Timestamp },
    { no: 16, name: "updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Form {
    return new Form().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Form {
    return new Form().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Form {
    return new Form().fromJsonString(jsonString, options);
  }

  static equals(a: Form | PlainMessage<Form> | undefined, b: Form | PlainMessage<Form> | undefined): boolean {
    return proto3.util.equals(Form, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.FormStats
 */
export class FormStats extends Message<FormStats> {
  /**
   * @generated from field: int64 total_responses = 1;
   */
  totalResponses = protoInt64.zero;

  /**
   * @generated from field: int64 completed_responses = 2;
   */
  completedResponses = protoInt64.zero;

  /**
   * @generated from field: int64 partial_responses = 3;
   */
  partialResponses = protoInt64.zero;

  constructor(data?: PartialMessage<FormStats>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.FormStats";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "total_responses", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "completed_responses", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "partial_responses", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FormStats {
    return new FormStats().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FormStats {
    return new FormStats().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FormStats {
    return new FormStats().fromJsonString(jsonString, options);
  }

  static equals(a: FormStats | PlainMessage<FormStats> | undefined, b: FormStats | PlainMessage<FormStats> | undefined): boolean {
    return proto3.util.equals(FormStats, a, b);
  }
}

/**
 * RPC Requests/Responses
 *
 * @generated from message weladee.form.v1.CreateFormRequest
 */
export class CreateFormRequest extends Message<CreateFormRequest> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: weladee.form.v1.FormTheme theme = 3;
   */
  theme = FormTheme.UNSPECIFIED;

  /**
   * @generated from field: repeated weladee.form.v1.Question questions = 4;
   */
  questions: Question[] = [];

  /**
   * @generated from field: google.protobuf.Struct settings = 5;
   */
  settings?: Struct;

  constructor(data?: PartialMessage<CreateFormRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.CreateFormRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "theme", kind: "enum", T: proto3.getEnumType(FormTheme) },
    { no: 4, name: "questions", kind: "message", T: Question, repeated: true },
    { no: 5, name: "settings", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateFormRequest {
    return new CreateFormRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateFormRequest {
    return new CreateFormRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateFormRequest {
    return new CreateFormRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateFormRequest | PlainMessage<CreateFormRequest> | undefined, b: CreateFormRequest | PlainMessage<CreateFormRequest> | undefined): boolean {
    return proto3.util.equals(CreateFormRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.CreateFormResponse
 */
export class CreateFormResponse extends Message<CreateFormResponse> {
  /**
   * @generated from field: weladee.form.v1.Form form = 1;
   */
  form?: Form;

  constructor(data?: PartialMessage<CreateFormResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.CreateFormResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form", kind: "message", T: Form },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateFormResponse {
    return new CreateFormResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateFormResponse {
    return new CreateFormResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateFormResponse {
    return new CreateFormResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateFormResponse | PlainMessage<CreateFormResponse> | undefined, b: CreateFormResponse | PlainMessage<CreateFormResponse> | undefined): boolean {
    return proto3.util.equals(CreateFormResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetFormRequest
 */
export class GetFormRequest extends Message<GetFormRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: bool include_questions = 2;
   */
  includeQuestions = false;

  constructor(data?: PartialMessage<GetFormRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetFormRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "include_questions", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFormRequest {
    return new GetFormRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFormRequest {
    return new GetFormRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFormRequest {
    return new GetFormRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetFormRequest | PlainMessage<GetFormRequest> | undefined, b: GetFormRequest | PlainMessage<GetFormRequest> | undefined): boolean {
    return proto3.util.equals(GetFormRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetFormResponse
 */
export class GetFormResponse extends Message<GetFormResponse> {
  /**
   * @generated from field: weladee.form.v1.Form form = 1;
   */
  form?: Form;

  constructor(data?: PartialMessage<GetFormResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetFormResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form", kind: "message", T: Form },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFormResponse {
    return new GetFormResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFormResponse {
    return new GetFormResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFormResponse {
    return new GetFormResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetFormResponse | PlainMessage<GetFormResponse> | undefined, b: GetFormResponse | PlainMessage<GetFormResponse> | undefined): boolean {
    return proto3.util.equals(GetFormResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetFormBySlugRequest
 */
export class GetFormBySlugRequest extends Message<GetFormBySlugRequest> {
  /**
   * @generated from field: string slug = 1;
   */
  slug = "";

  constructor(data?: PartialMessage<GetFormBySlugRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetFormBySlugRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFormBySlugRequest {
    return new GetFormBySlugRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFormBySlugRequest {
    return new GetFormBySlugRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFormBySlugRequest {
    return new GetFormBySlugRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetFormBySlugRequest | PlainMessage<GetFormBySlugRequest> | undefined, b: GetFormBySlugRequest | PlainMessage<GetFormBySlugRequest> | undefined): boolean {
    return proto3.util.equals(GetFormBySlugRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetFormBySlugResponse
 */
export class GetFormBySlugResponse extends Message<GetFormBySlugResponse> {
  /**
   * @generated from field: weladee.form.v1.Form form = 1;
   */
  form?: Form;

  constructor(data?: PartialMessage<GetFormBySlugResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetFormBySlugResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form", kind: "message", T: Form },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFormBySlugResponse {
    return new GetFormBySlugResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFormBySlugResponse {
    return new GetFormBySlugResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFormBySlugResponse {
    return new GetFormBySlugResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetFormBySlugResponse | PlainMessage<GetFormBySlugResponse> | undefined, b: GetFormBySlugResponse | PlainMessage<GetFormBySlugResponse> | undefined): boolean {
    return proto3.util.equals(GetFormBySlugResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.UpdateFormRequest
 */
export class UpdateFormRequest extends Message<UpdateFormRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: optional weladee.form.v1.FormTheme theme = 4;
   */
  theme?: FormTheme;

  /**
   * @generated from field: optional bool is_published = 5;
   */
  isPublished?: boolean;

  /**
   * @generated from field: optional bool is_accepting_responses = 6;
   */
  isAcceptingResponses?: boolean;

  /**
   * @generated from field: optional bool require_login = 7;
   */
  requireLogin?: boolean;

  /**
   * @generated from field: optional bool allow_multiple_submissions = 8;
   */
  allowMultipleSubmissions?: boolean;

  /**
   * @generated from field: optional bool show_progress_bar = 9;
   */
  showProgressBar?: boolean;

  /**
   * @generated from field: optional string custom_thank_you_message = 10;
   */
  customThankYouMessage?: string;

  /**
   * @generated from field: optional string redirect_url = 11;
   */
  redirectUrl?: string;

  /**
   * @generated from field: optional google.protobuf.Struct settings = 12;
   */
  settings?: Struct;

  constructor(data?: PartialMessage<UpdateFormRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.UpdateFormRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "theme", kind: "enum", T: proto3.getEnumType(FormTheme), opt: true },
    { no: 5, name: "is_published", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 6, name: "is_accepting_responses", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "require_login", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 8, name: "allow_multiple_submissions", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 9, name: "show_progress_bar", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 10, name: "custom_thank_you_message", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "redirect_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 12, name: "settings", kind: "message", T: Struct, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateFormRequest {
    return new UpdateFormRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateFormRequest {
    return new UpdateFormRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateFormRequest {
    return new UpdateFormRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateFormRequest | PlainMessage<UpdateFormRequest> | undefined, b: UpdateFormRequest | PlainMessage<UpdateFormRequest> | undefined): boolean {
    return proto3.util.equals(UpdateFormRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.UpdateFormResponse
 */
export class UpdateFormResponse extends Message<UpdateFormResponse> {
  /**
   * @generated from field: weladee.form.v1.Form form = 1;
   */
  form?: Form;

  constructor(data?: PartialMessage<UpdateFormResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.UpdateFormResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form", kind: "message", T: Form },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateFormResponse {
    return new UpdateFormResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateFormResponse {
    return new UpdateFormResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateFormResponse {
    return new UpdateFormResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateFormResponse | PlainMessage<UpdateFormResponse> | undefined, b: UpdateFormResponse | PlainMessage<UpdateFormResponse> | undefined): boolean {
    return proto3.util.equals(UpdateFormResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.DeleteFormRequest
 */
export class DeleteFormRequest extends Message<DeleteFormRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteFormRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.DeleteFormRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteFormRequest {
    return new DeleteFormRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteFormRequest {
    return new DeleteFormRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteFormRequest {
    return new DeleteFormRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteFormRequest | PlainMessage<DeleteFormRequest> | undefined, b: DeleteFormRequest | PlainMessage<DeleteFormRequest> | undefined): boolean {
    return proto3.util.equals(DeleteFormRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.DeleteFormResponse
 */
export class DeleteFormResponse extends Message<DeleteFormResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<DeleteFormResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.DeleteFormResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteFormResponse {
    return new DeleteFormResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteFormResponse {
    return new DeleteFormResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteFormResponse {
    return new DeleteFormResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteFormResponse | PlainMessage<DeleteFormResponse> | undefined, b: DeleteFormResponse | PlainMessage<DeleteFormResponse> | undefined): boolean {
    return proto3.util.equals(DeleteFormResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ListFormsRequest
 */
export class ListFormsRequest extends Message<ListFormsRequest> {
  /**
   * @generated from field: weladee.form.v1.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional string search_query = 2;
   */
  searchQuery?: string;

  /**
   * @generated from field: optional bool published_only = 3;
   */
  publishedOnly?: boolean;

  constructor(data?: PartialMessage<ListFormsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ListFormsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pagination", kind: "message", T: PaginationRequest },
    { no: 2, name: "search_query", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "published_only", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListFormsRequest {
    return new ListFormsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListFormsRequest {
    return new ListFormsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListFormsRequest {
    return new ListFormsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListFormsRequest | PlainMessage<ListFormsRequest> | undefined, b: ListFormsRequest | PlainMessage<ListFormsRequest> | undefined): boolean {
    return proto3.util.equals(ListFormsRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ListFormsResponse
 */
export class ListFormsResponse extends Message<ListFormsResponse> {
  /**
   * @generated from field: repeated weladee.form.v1.Form forms = 1;
   */
  forms: Form[] = [];

  /**
   * @generated from field: weladee.form.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;

  constructor(data?: PartialMessage<ListFormsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ListFormsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "forms", kind: "message", T: Form, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PaginationResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListFormsResponse {
    return new ListFormsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListFormsResponse {
    return new ListFormsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListFormsResponse {
    return new ListFormsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListFormsResponse | PlainMessage<ListFormsResponse> | undefined, b: ListFormsResponse | PlainMessage<ListFormsResponse> | undefined): boolean {
    return proto3.util.equals(ListFormsResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.PublishFormRequest
 */
export class PublishFormRequest extends Message<PublishFormRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<PublishFormRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.PublishFormRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishFormRequest {
    return new PublishFormRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishFormRequest {
    return new PublishFormRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishFormRequest {
    return new PublishFormRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PublishFormRequest | PlainMessage<PublishFormRequest> | undefined, b: PublishFormRequest | PlainMessage<PublishFormRequest> | undefined): boolean {
    return proto3.util.equals(PublishFormRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.PublishFormResponse
 */
export class PublishFormResponse extends Message<PublishFormResponse> {
  /**
   * @generated from field: weladee.form.v1.Form form = 1;
   */
  form?: Form;

  constructor(data?: PartialMessage<PublishFormResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.PublishFormResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form", kind: "message", T: Form },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PublishFormResponse {
    return new PublishFormResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PublishFormResponse {
    return new PublishFormResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PublishFormResponse {
    return new PublishFormResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PublishFormResponse | PlainMessage<PublishFormResponse> | undefined, b: PublishFormResponse | PlainMessage<PublishFormResponse> | undefined): boolean {
    return proto3.util.equals(PublishFormResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetFormStatsRequest
 */
export class GetFormStatsRequest extends Message<GetFormStatsRequest> {
  /**
   * @generated from field: string form_id = 1;
   */
  formId = "";

  constructor(data?: PartialMessage<GetFormStatsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetFormStatsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFormStatsRequest {
    return new GetFormStatsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFormStatsRequest {
    return new GetFormStatsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFormStatsRequest {
    return new GetFormStatsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetFormStatsRequest | PlainMessage<GetFormStatsRequest> | undefined, b: GetFormStatsRequest | PlainMessage<GetFormStatsRequest> | undefined): boolean {
    return proto3.util.equals(GetFormStatsRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetFormStatsResponse
 */
export class GetFormStatsResponse extends Message<GetFormStatsResponse> {
  /**
   * @generated from field: weladee.form.v1.FormStats stats = 1;
   */
  stats?: FormStats;

  constructor(data?: PartialMessage<GetFormStatsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetFormStatsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "stats", kind: "message", T: FormStats },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetFormStatsResponse {
    return new GetFormStatsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetFormStatsResponse {
    return new GetFormStatsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetFormStatsResponse {
    return new GetFormStatsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetFormStatsResponse | PlainMessage<GetFormStatsResponse> | undefined, b: GetFormStatsResponse | PlainMessage<GetFormStatsResponse> | undefined): boolean {
    return proto3.util.equals(GetFormStatsResponse, a, b);
  }
}

/**
 * Question RPCs
 *
 * @generated from message weladee.form.v1.CreateQuestionRequest
 */
export class CreateQuestionRequest extends Message<CreateQuestionRequest> {
  /**
   * @generated from field: string form_id = 1;
   */
  formId = "";

  /**
   * @generated from field: weladee.form.v1.QuestionType type = 2;
   */
  type = QuestionType.UNSPECIFIED;

  /**
   * @generated from field: string label = 3;
   */
  label = "";

  /**
   * @generated from field: string description = 4;
   */
  description = "";

  /**
   * @generated from field: string placeholder = 5;
   */
  placeholder = "";

  /**
   * @generated from field: bool required = 6;
   */
  required = false;

  /**
   * @generated from field: int32 order_index = 7;
   */
  orderIndex = 0;

  /**
   * @generated from field: google.protobuf.Struct options = 8;
   */
  options?: Struct;

  /**
   * @generated from field: google.protobuf.Struct validation_rules = 9;
   */
  validationRules?: Struct;

  constructor(data?: PartialMessage<CreateQuestionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.CreateQuestionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "enum", T: proto3.getEnumType(QuestionType) },
    { no: 3, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "placeholder", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "required", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "order_index", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "options", kind: "message", T: Struct },
    { no: 9, name: "validation_rules", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateQuestionRequest {
    return new CreateQuestionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateQuestionRequest {
    return new CreateQuestionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateQuestionRequest {
    return new CreateQuestionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateQuestionRequest | PlainMessage<CreateQuestionRequest> | undefined, b: CreateQuestionRequest | PlainMessage<CreateQuestionRequest> | undefined): boolean {
    return proto3.util.equals(CreateQuestionRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.CreateQuestionResponse
 */
export class CreateQuestionResponse extends Message<CreateQuestionResponse> {
  /**
   * @generated from field: weladee.form.v1.Question question = 1;
   */
  question?: Question;

  constructor(data?: PartialMessage<CreateQuestionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.CreateQuestionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "question", kind: "message", T: Question },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateQuestionResponse {
    return new CreateQuestionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateQuestionResponse {
    return new CreateQuestionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateQuestionResponse {
    return new CreateQuestionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateQuestionResponse | PlainMessage<CreateQuestionResponse> | undefined, b: CreateQuestionResponse | PlainMessage<CreateQuestionResponse> | undefined): boolean {
    return proto3.util.equals(CreateQuestionResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.UpdateQuestionRequest
 */
export class UpdateQuestionRequest extends Message<UpdateQuestionRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: optional weladee.form.v1.QuestionType type = 2;
   */
  type?: QuestionType;

  /**
   * @generated from field: optional string label = 3;
   */
  label?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string placeholder = 5;
   */
  placeholder?: string;

  /**
   * @generated from field: optional bool required = 6;
   */
  required?: boolean;

  /**
   * @generated from field: optional int32 order_index = 7;
   */
  orderIndex?: number;

  /**
   * @generated from field: optional google.protobuf.Struct options = 8;
   */
  options?: Struct;

  /**
   * @generated from field: optional google.protobuf.Struct validation_rules = 9;
   */
  validationRules?: Struct;

  constructor(data?: PartialMessage<UpdateQuestionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.UpdateQuestionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "enum", T: proto3.getEnumType(QuestionType), opt: true },
    { no: 3, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "placeholder", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "required", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 7, name: "order_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 8, name: "options", kind: "message", T: Struct, opt: true },
    { no: 9, name: "validation_rules", kind: "message", T: Struct, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateQuestionRequest {
    return new UpdateQuestionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateQuestionRequest {
    return new UpdateQuestionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateQuestionRequest {
    return new UpdateQuestionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateQuestionRequest | PlainMessage<UpdateQuestionRequest> | undefined, b: UpdateQuestionRequest | PlainMessage<UpdateQuestionRequest> | undefined): boolean {
    return proto3.util.equals(UpdateQuestionRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.UpdateQuestionResponse
 */
export class UpdateQuestionResponse extends Message<UpdateQuestionResponse> {
  /**
   * @generated from field: weladee.form.v1.Question question = 1;
   */
  question?: Question;

  constructor(data?: PartialMessage<UpdateQuestionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.UpdateQuestionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "question", kind: "message", T: Question },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateQuestionResponse {
    return new UpdateQuestionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateQuestionResponse {
    return new UpdateQuestionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateQuestionResponse {
    return new UpdateQuestionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateQuestionResponse | PlainMessage<UpdateQuestionResponse> | undefined, b: UpdateQuestionResponse | PlainMessage<UpdateQuestionResponse> | undefined): boolean {
    return proto3.util.equals(UpdateQuestionResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.DeleteQuestionRequest
 */
export class DeleteQuestionRequest extends Message<DeleteQuestionRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteQuestionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.DeleteQuestionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteQuestionRequest {
    return new DeleteQuestionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteQuestionRequest {
    return new DeleteQuestionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteQuestionRequest {
    return new DeleteQuestionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteQuestionRequest | PlainMessage<DeleteQuestionRequest> | undefined, b: DeleteQuestionRequest | PlainMessage<DeleteQuestionRequest> | undefined): boolean {
    return proto3.util.equals(DeleteQuestionRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.DeleteQuestionResponse
 */
export class DeleteQuestionResponse extends Message<DeleteQuestionResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<DeleteQuestionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.DeleteQuestionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteQuestionResponse {
    return new DeleteQuestionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteQuestionResponse {
    return new DeleteQuestionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteQuestionResponse {
    return new DeleteQuestionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteQuestionResponse | PlainMessage<DeleteQuestionResponse> | undefined, b: DeleteQuestionResponse | PlainMessage<DeleteQuestionResponse> | undefined): boolean {
    return proto3.util.equals(DeleteQuestionResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ReorderQuestionsRequest
 */
export class ReorderQuestionsRequest extends Message<ReorderQuestionsRequest> {
  /**
   * @generated from field: string form_id = 1;
   */
  formId = "";

  /**
   * @generated from field: repeated string question_ids = 2;
   */
  questionIds: string[] = [];

  constructor(data?: PartialMessage<ReorderQuestionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ReorderQuestionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "question_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReorderQuestionsRequest {
    return new ReorderQuestionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReorderQuestionsRequest {
    return new ReorderQuestionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReorderQuestionsRequest {
    return new ReorderQuestionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ReorderQuestionsRequest | PlainMessage<ReorderQuestionsRequest> | undefined, b: ReorderQuestionsRequest | PlainMessage<ReorderQuestionsRequest> | undefined): boolean {
    return proto3.util.equals(ReorderQuestionsRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ReorderQuestionsResponse
 */
export class ReorderQuestionsResponse extends Message<ReorderQuestionsResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<ReorderQuestionsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ReorderQuestionsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReorderQuestionsResponse {
    return new ReorderQuestionsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReorderQuestionsResponse {
    return new ReorderQuestionsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReorderQuestionsResponse {
    return new ReorderQuestionsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ReorderQuestionsResponse | PlainMessage<ReorderQuestionsResponse> | undefined, b: ReorderQuestionsResponse | PlainMessage<ReorderQuestionsResponse> | undefined): boolean {
    return proto3.util.equals(ReorderQuestionsResponse, a, b);
  }
}
