// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file proto/response.proto (package weladee.form.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Struct, Timestamp } from "@bufbuild/protobuf";
import { PaginationRequest, PaginationResponse } from "./common_pb.js";

/**
 * Messages
 *
 * @generated from message weladee.form.v1.Answer
 */
export class Answer extends Message<Answer> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string response_id = 2;
   */
  responseId = "";

  /**
   * @generated from field: string question_id = 3;
   */
  questionId = "";

  /**
   * @generated from field: optional string answer_text = 4;
   */
  answerText?: string;

  /**
   * @generated from field: optional double answer_number = 5;
   */
  answerNumber?: number;

  /**
   * @generated from field: optional string answer_date = 6;
   */
  answerDate?: string;

  /**
   * @generated from field: optional string answer_time = 7;
   */
  answerTime?: string;

  /**
   * @generated from field: optional google.protobuf.Struct answer_choices = 8;
   */
  answerChoices?: Struct;

  /**
   * @generated from field: optional string answer_file_url = 9;
   */
  answerFileUrl?: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Answer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.Answer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "response_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "question_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "answer_text", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "answer_number", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 6, name: "answer_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "answer_time", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "answer_choices", kind: "message", T: Struct, opt: true },
    { no: 9, name: "answer_file_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Answer {
    return new Answer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Answer {
    return new Answer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Answer {
    return new Answer().fromJsonString(jsonString, options);
  }

  static equals(a: Answer | PlainMessage<Answer> | undefined, b: Answer | PlainMessage<Answer> | undefined): boolean {
    return proto3.util.equals(Answer, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.Response
 */
export class Response extends Message<Response> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string form_id = 2;
   */
  formId = "";

  /**
   * @generated from field: optional string respondent_user_id = 3;
   */
  respondentUserId?: string;

  /**
   * @generated from field: optional string respondent_email = 4;
   */
  respondentEmail?: string;

  /**
   * @generated from field: optional string respondent_name = 5;
   */
  respondentName?: string;

  /**
   * @generated from field: bool completed = 7;
   */
  completed = false;

  /**
   * @generated from field: google.protobuf.Timestamp submitted_at = 8;
   */
  submittedAt?: Timestamp;

  /**
   * @generated from field: repeated weladee.form.v1.Answer answers = 9;
   */
  answers: Answer[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Response>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.Response";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "respondent_user_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "respondent_email", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "respondent_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "completed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "submitted_at", kind: "message", T: Timestamp },
    { no: 9, name: "answers", kind: "message", T: Answer, repeated: true },
    { no: 10, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Response {
    return new Response().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Response {
    return new Response().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Response {
    return new Response().fromJsonString(jsonString, options);
  }

  static equals(a: Response | PlainMessage<Response> | undefined, b: Response | PlainMessage<Response> | undefined): boolean {
    return proto3.util.equals(Response, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.AnswerInput
 */
export class AnswerInput extends Message<AnswerInput> {
  /**
   * @generated from field: string question_id = 1;
   */
  questionId = "";

  /**
   * @generated from field: optional string answer_text = 2;
   */
  answerText?: string;

  /**
   * @generated from field: optional double answer_number = 3;
   */
  answerNumber?: number;

  /**
   * @generated from field: optional string answer_date = 4;
   */
  answerDate?: string;

  /**
   * @generated from field: optional string answer_time = 5;
   */
  answerTime?: string;

  /**
   * @generated from field: optional google.protobuf.Struct answer_choices = 6;
   */
  answerChoices?: Struct;

  /**
   * @generated from field: optional string answer_file_url = 7;
   */
  answerFileUrl?: string;

  constructor(data?: PartialMessage<AnswerInput>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.AnswerInput";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "question_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "answer_text", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "answer_number", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 4, name: "answer_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "answer_time", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "answer_choices", kind: "message", T: Struct, opt: true },
    { no: 7, name: "answer_file_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnswerInput {
    return new AnswerInput().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnswerInput {
    return new AnswerInput().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnswerInput {
    return new AnswerInput().fromJsonString(jsonString, options);
  }

  static equals(a: AnswerInput | PlainMessage<AnswerInput> | undefined, b: AnswerInput | PlainMessage<AnswerInput> | undefined): boolean {
    return proto3.util.equals(AnswerInput, a, b);
  }
}

/**
 * RPC Requests/Responses
 *
 * @generated from message weladee.form.v1.SubmitResponseRequest
 */
export class SubmitResponseRequest extends Message<SubmitResponseRequest> {
  /**
   * @generated from field: string form_id = 1;
   */
  formId = "";

  /**
   * @generated from field: optional string respondent_email = 2;
   */
  respondentEmail?: string;

  /**
   * @generated from field: optional string respondent_name = 3;
   */
  respondentName?: string;

  /**
   * @generated from field: repeated weladee.form.v1.AnswerInput answers = 4;
   */
  answers: AnswerInput[] = [];

  /**
   * @generated from field: bool complete = 5;
   */
  complete = false;

  constructor(data?: PartialMessage<SubmitResponseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.SubmitResponseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "respondent_email", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "respondent_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "answers", kind: "message", T: AnswerInput, repeated: true },
    { no: 5, name: "complete", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitResponseRequest {
    return new SubmitResponseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitResponseRequest {
    return new SubmitResponseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitResponseRequest {
    return new SubmitResponseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitResponseRequest | PlainMessage<SubmitResponseRequest> | undefined, b: SubmitResponseRequest | PlainMessage<SubmitResponseRequest> | undefined): boolean {
    return proto3.util.equals(SubmitResponseRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.SubmitResponseResponse
 */
export class SubmitResponseResponse extends Message<SubmitResponseResponse> {
  /**
   * @generated from field: weladee.form.v1.Response response = 1;
   */
  response?: Response;

  constructor(data?: PartialMessage<SubmitResponseResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.SubmitResponseResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "response", kind: "message", T: Response },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitResponseResponse {
    return new SubmitResponseResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitResponseResponse {
    return new SubmitResponseResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitResponseResponse {
    return new SubmitResponseResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitResponseResponse | PlainMessage<SubmitResponseResponse> | undefined, b: SubmitResponseResponse | PlainMessage<SubmitResponseResponse> | undefined): boolean {
    return proto3.util.equals(SubmitResponseResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetResponseRequest
 */
export class GetResponseRequest extends Message<GetResponseRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetResponseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetResponseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResponseRequest {
    return new GetResponseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResponseRequest {
    return new GetResponseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResponseRequest {
    return new GetResponseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetResponseRequest | PlainMessage<GetResponseRequest> | undefined, b: GetResponseRequest | PlainMessage<GetResponseRequest> | undefined): boolean {
    return proto3.util.equals(GetResponseRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.GetResponseResponse
 */
export class GetResponseResponse extends Message<GetResponseResponse> {
  /**
   * @generated from field: weladee.form.v1.Response response = 1;
   */
  response?: Response;

  constructor(data?: PartialMessage<GetResponseResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.GetResponseResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "response", kind: "message", T: Response },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetResponseResponse {
    return new GetResponseResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetResponseResponse {
    return new GetResponseResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetResponseResponse {
    return new GetResponseResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetResponseResponse | PlainMessage<GetResponseResponse> | undefined, b: GetResponseResponse | PlainMessage<GetResponseResponse> | undefined): boolean {
    return proto3.util.equals(GetResponseResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ListResponsesRequest
 */
export class ListResponsesRequest extends Message<ListResponsesRequest> {
  /**
   * @generated from field: string form_id = 1;
   */
  formId = "";

  /**
   * @generated from field: weladee.form.v1.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional bool completed_only = 3;
   */
  completedOnly?: boolean;

  constructor(data?: PartialMessage<ListResponsesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ListResponsesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pagination", kind: "message", T: PaginationRequest },
    { no: 3, name: "completed_only", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponsesRequest {
    return new ListResponsesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponsesRequest {
    return new ListResponsesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponsesRequest {
    return new ListResponsesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListResponsesRequest | PlainMessage<ListResponsesRequest> | undefined, b: ListResponsesRequest | PlainMessage<ListResponsesRequest> | undefined): boolean {
    return proto3.util.equals(ListResponsesRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ListResponsesResponse
 */
export class ListResponsesResponse extends Message<ListResponsesResponse> {
  /**
   * @generated from field: repeated weladee.form.v1.Response responses = 1;
   */
  responses: Response[] = [];

  /**
   * @generated from field: weladee.form.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;

  constructor(data?: PartialMessage<ListResponsesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ListResponsesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "responses", kind: "message", T: Response, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PaginationResponse },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListResponsesResponse {
    return new ListResponsesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListResponsesResponse {
    return new ListResponsesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListResponsesResponse {
    return new ListResponsesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListResponsesResponse | PlainMessage<ListResponsesResponse> | undefined, b: ListResponsesResponse | PlainMessage<ListResponsesResponse> | undefined): boolean {
    return proto3.util.equals(ListResponsesResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.DeleteResponseRequest
 */
export class DeleteResponseRequest extends Message<DeleteResponseRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeleteResponseRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.DeleteResponseRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResponseRequest {
    return new DeleteResponseRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResponseRequest {
    return new DeleteResponseRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResponseRequest {
    return new DeleteResponseRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteResponseRequest | PlainMessage<DeleteResponseRequest> | undefined, b: DeleteResponseRequest | PlainMessage<DeleteResponseRequest> | undefined): boolean {
    return proto3.util.equals(DeleteResponseRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.DeleteResponseResponse
 */
export class DeleteResponseResponse extends Message<DeleteResponseResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<DeleteResponseResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.DeleteResponseResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteResponseResponse {
    return new DeleteResponseResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteResponseResponse {
    return new DeleteResponseResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteResponseResponse {
    return new DeleteResponseResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteResponseResponse | PlainMessage<DeleteResponseResponse> | undefined, b: DeleteResponseResponse | PlainMessage<DeleteResponseResponse> | undefined): boolean {
    return proto3.util.equals(DeleteResponseResponse, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ExportResponsesRequest
 */
export class ExportResponsesRequest extends Message<ExportResponsesRequest> {
  /**
   * @generated from field: string form_id = 1;
   */
  formId = "";

  /**
   * @generated from field: string format = 2;
   */
  format = "";

  constructor(data?: PartialMessage<ExportResponsesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ExportResponsesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "form_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "format", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportResponsesRequest {
    return new ExportResponsesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportResponsesRequest {
    return new ExportResponsesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportResponsesRequest {
    return new ExportResponsesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ExportResponsesRequest | PlainMessage<ExportResponsesRequest> | undefined, b: ExportResponsesRequest | PlainMessage<ExportResponsesRequest> | undefined): boolean {
    return proto3.util.equals(ExportResponsesRequest, a, b);
  }
}

/**
 * @generated from message weladee.form.v1.ExportResponsesResponse
 */
export class ExportResponsesResponse extends Message<ExportResponsesResponse> {
  /**
   * @generated from field: bytes data = 1;
   */
  data = new Uint8Array(0);

  /**
   * @generated from field: string filename = 2;
   */
  filename = "";

  /**
   * @generated from field: string mime_type = 3;
   */
  mimeType = "";

  constructor(data?: PartialMessage<ExportResponsesResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "weladee.form.v1.ExportResponsesResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "mime_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportResponsesResponse {
    return new ExportResponsesResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportResponsesResponse {
    return new ExportResponsesResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportResponsesResponse {
    return new ExportResponsesResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ExportResponsesResponse | PlainMessage<ExportResponsesResponse> | undefined, b: ExportResponsesResponse | PlainMessage<ExportResponsesResponse> | undefined): boolean {
    return proto3.util.equals(ExportResponsesResponse, a, b);
  }
}

