// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const incrementFormCompletions = `-- name: IncrementFormCompletions :exec
/**
 * Increment the total completions for a form on a given date
 * @param {uuid} form_id - The ID of the form
 */
INSERT INTO form.analytics (form_id, date, total_completions)
VALUES ($1::uuid, CURRENT_DATE, 1)
ON CONFLICT (form_id, date)
DO UPDATE SET total_completions = form.analytics.total_completions + 1
`

func (q *Queries) IncrementFormCompletions(ctx context.Context, formID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFormCompletions, formID)
	return err
}

const incrementFormStarts = `-- name: IncrementFormStarts :exec
/**
 * Increment the total starts for a form on a given date
 * @param {uuid} form_id - The ID of the form
 */
INSERT INTO form.analytics (form_id, date, total_starts)
VALUES ($1::uuid, CURRENT_DATE, 1)
ON CONFLICT (form_id, date)
DO UPDATE SET total_starts = form.analytics.total_starts + 1
`

func (q *Queries) IncrementFormStarts(ctx context.Context, formID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFormStarts, formID)
	return err
}

const incrementFormViews = `-- name: IncrementFormViews :exec
/**
 * Increment the total views for a form on a given date
 * @param {uuid} form_id - The ID of the form
 */
INSERT INTO form.analytics (form_id, date, total_views)
VALUES ($1::uuid, CURRENT_DATE, 1)
ON CONFLICT (form_id, date)
DO UPDATE SET total_views = form.analytics.total_views + 1
`

func (q *Queries) IncrementFormViews(ctx context.Context, formID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFormViews, formID)
	return err
}
