// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFileUpload = `-- name: CreateFileUpload :one
INSERT INTO form.file_uploads (
    form_id, question_id, response_id, filename, original_filename,
    mime_type, file_size, s3_key, s3_url
) VALUES (
    $1::uuid, $2::uuid, $3::uuid, $4::text, $5::text,
    $6::text, $7::bigint, $8::text, $9::text
)
RETURNING id
`

type CreateFileUploadParams struct {
	FormID           uuid.UUID `db:"form_id" json:"formId"`
	QuestionID       uuid.UUID `db:"question_id" json:"questionId"`
	ResponseID       uuid.UUID `db:"response_id" json:"responseId"`
	Filename         string    `db:"filename" json:"filename"`
	OriginalFilename string    `db:"original_filename" json:"originalFilename"`
	MimeType         string    `db:"mime_type" json:"mimeType"`
	FileSize         int64     `db:"file_size" json:"fileSize"`
	S3Key            string    `db:"s3_key" json:"s3Key"`
	S3Url            string    `db:"s3_url" json:"s3Url"`
}

func (q *Queries) CreateFileUpload(ctx context.Context, arg CreateFileUploadParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createFileUpload,
		arg.FormID,
		arg.QuestionID,
		arg.ResponseID,
		arg.Filename,
		arg.OriginalFilename,
		arg.MimeType,
		arg.FileSize,
		arg.S3Key,
		arg.S3Url,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFileUpload = `-- name: GetFileUpload :one
SELECT id, form_id, question_id, response_id, filename, original_filename, mime_type, file_size, s3_key, s3_url, uploaded_by_user_id, created_at FROM form.file_uploads
WHERE id = $1::uuid
`

func (q *Queries) GetFileUpload(ctx context.Context, id uuid.UUID) (FormFileUpload, error) {
	row := q.db.QueryRow(ctx, getFileUpload, id)
	var i FormFileUpload
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.QuestionID,
		&i.ResponseID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.S3Key,
		&i.S3Url,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
