// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: form.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserForms = `-- name: CountUserForms :one
SELECT COUNT(*) as count
FROM form.forms
WHERE user_id = $1::uuid
`

func (q *Queries) CountUserForms(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserForms, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :one
INSERT INTO form.forms (
    user_id, title, description, theme, is_published,
    is_accepting_responses, require_login, allow_multiple_submissions,
    show_progress_bar, custom_thank_you_message, redirect_url, settings
)
VALUES (
    $1::uuid, $2::text, $3::text, $4::text, $5::boolean,
    $6::boolean, $7::boolean, $8::boolean,
    $9::boolean, $10::text, $11::text, $12::jsonb
)
RETURNING id, user_id, title, description, slug, theme, is_published, is_accepting_responses, require_login, allow_multiple_submissions, show_progress_bar, custom_thank_you_message, redirect_url, settings, created_at, updated_at
`

type CreateFormParams struct {
	UserID                   uuid.UUID       `db:"user_id" json:"userId"`
	Title                    string          `db:"title" json:"title"`
	Description              string          `db:"description" json:"description"`
	Theme                    string          `db:"theme" json:"theme"`
	IsPublished              bool            `db:"is_published" json:"isPublished"`
	IsAcceptingResponses     bool            `db:"is_accepting_responses" json:"isAcceptingResponses"`
	RequireLogin             bool            `db:"require_login" json:"requireLogin"`
	AllowMultipleSubmissions bool            `db:"allow_multiple_submissions" json:"allowMultipleSubmissions"`
	ShowProgressBar          bool            `db:"show_progress_bar" json:"showProgressBar"`
	CustomThankYouMessage    string          `db:"custom_thank_you_message" json:"customThankYouMessage"`
	RedirectUrl              string          `db:"redirect_url" json:"redirectUrl"`
	Settings                 json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (FormForm, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Theme,
		arg.IsPublished,
		arg.IsAcceptingResponses,
		arg.RequireLogin,
		arg.AllowMultipleSubmissions,
		arg.ShowProgressBar,
		arg.CustomThankYouMessage,
		arg.RedirectUrl,
		arg.Settings,
	)
	var i FormForm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Theme,
		&i.IsPublished,
		&i.IsAcceptingResponses,
		&i.RequireLogin,
		&i.AllowMultipleSubmissions,
		&i.ShowProgressBar,
		&i.CustomThankYouMessage,
		&i.RedirectUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM form.forms
WHERE id = $1::uuid AND user_id = $2::uuid
`

type DeleteFormParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) DeleteForm(ctx context.Context, arg DeleteFormParams) error {
	_, err := q.db.Exec(ctx, deleteForm, arg.ID, arg.UserID)
	return err
}

const getForm = `-- name: GetForm :one
SELECT id, user_id, title, description, slug, theme, is_published, is_accepting_responses, require_login, allow_multiple_submissions, show_progress_bar, custom_thank_you_message, redirect_url, settings, created_at, updated_at FROM form.forms
WHERE id = $1::uuid
`

func (q *Queries) GetForm(ctx context.Context, id uuid.UUID) (FormForm, error) {
	row := q.db.QueryRow(ctx, getForm, id)
	var i FormForm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Theme,
		&i.IsPublished,
		&i.IsAcceptingResponses,
		&i.RequireLogin,
		&i.AllowMultipleSubmissions,
		&i.ShowProgressBar,
		&i.CustomThankYouMessage,
		&i.RedirectUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormBySlug = `-- name: GetFormBySlug :one
SELECT id, user_id, title, description, slug, theme, is_published, is_accepting_responses, require_login, allow_multiple_submissions, show_progress_bar, custom_thank_you_message, redirect_url, settings, created_at, updated_at FROM form.forms
WHERE $1::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND id = $1::uuid
   OR slug = $1::text
`

// Try to look up by ID (if slug is a UUID) or by slug column
func (q *Queries) GetFormBySlug(ctx context.Context, slug string) (FormForm, error) {
	row := q.db.QueryRow(ctx, getFormBySlug, slug)
	var i FormForm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Theme,
		&i.IsPublished,
		&i.IsAcceptingResponses,
		&i.RequireLogin,
		&i.AllowMultipleSubmissions,
		&i.ShowProgressBar,
		&i.CustomThankYouMessage,
		&i.RedirectUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormStats = `-- name: GetFormStats :one
/**
 * Get the statistics for a form.
 *
 * Retrieves the total number of responses, number of completed responses,
 * and number of partial responses for a form.
 *
 * @param form_id The id of the form.
 * @return The statistics for the form.
 */
SELECT
    COUNT(DISTINCT r.id) AS total_responses,
    COUNT(DISTINCT CASE WHEN r.completed = true THEN r.id END) AS completed_responses,
    COUNT(DISTINCT CASE WHEN r.completed = false THEN r.id END) AS partial_responses
FROM form.forms f
LEFT JOIN form.responses r ON f.id = r.form_id
WHERE f.id = $1::uuid
GROUP BY f.id
`

type GetFormStatsRow struct {
	TotalResponses     int64 `db:"total_responses" json:"totalResponses"`
	CompletedResponses int64 `db:"completed_responses" json:"completedResponses"`
	PartialResponses   int64 `db:"partial_responses" json:"partialResponses"`
}

func (q *Queries) GetFormStats(ctx context.Context, formID uuid.UUID) (GetFormStatsRow, error) {
	row := q.db.QueryRow(ctx, getFormStats, formID)
	var i GetFormStatsRow
	err := row.Scan(&i.TotalResponses, &i.CompletedResponses, &i.PartialResponses)
	return i, err
}

const getFormWithQuestions = `-- name: GetFormWithQuestions :one
SELECT
    f.id, f.user_id, f.title, f.description, f.slug, f.theme, f.is_published, f.is_accepting_responses, f.require_login, f.allow_multiple_submissions, f.show_progress_bar, f.custom_thank_you_message, f.redirect_url, f.settings, f.created_at, f.updated_at,
    q.id as question_id,
    q.type as question_type,
    q.label as question_label,
    q.description as question_description,
    q.placeholder as question_placeholder,
    q.required as question_required,
    q.order_index as question_order,
    q.options as question_options,
    q.validation_rules as question_validation_rules,
    q.settings as question_settings,
    q.created_at as question_created_at,
    q.updated_at as question_updated_at
FROM form.forms f
LEFT JOIN form.questions q ON f.id = q.form_id
WHERE f.id = $1::uuid
ORDER BY q.order_index
`

type GetFormWithQuestionsRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"userId"`
	Title                    string             `db:"title" json:"title"`
	Description              pgtype.Text        `db:"description" json:"description"`
	Slug                     pgtype.Text        `db:"slug" json:"slug"`
	Theme                    string             `db:"theme" json:"theme"`
	IsPublished              bool               `db:"is_published" json:"isPublished"`
	IsAcceptingResponses     bool               `db:"is_accepting_responses" json:"isAcceptingResponses"`
	RequireLogin             bool               `db:"require_login" json:"requireLogin"`
	AllowMultipleSubmissions bool               `db:"allow_multiple_submissions" json:"allowMultipleSubmissions"`
	ShowProgressBar          bool               `db:"show_progress_bar" json:"showProgressBar"`
	CustomThankYouMessage    pgtype.Text        `db:"custom_thank_you_message" json:"customThankYouMessage"`
	RedirectUrl              pgtype.Text        `db:"redirect_url" json:"redirectUrl"`
	Settings                 []byte             `db:"settings" json:"settings"`
	CreatedAt                time.Time          `db:"created_at" json:"createdAt"`
	UpdatedAt                time.Time          `db:"updated_at" json:"updatedAt"`
	QuestionID               pgtype.UUID        `db:"question_id" json:"questionId"`
	QuestionType             pgtype.Text        `db:"question_type" json:"questionType"`
	QuestionLabel            pgtype.Text        `db:"question_label" json:"questionLabel"`
	QuestionDescription      pgtype.Text        `db:"question_description" json:"questionDescription"`
	QuestionPlaceholder      pgtype.Text        `db:"question_placeholder" json:"questionPlaceholder"`
	QuestionRequired         pgtype.Bool        `db:"question_required" json:"questionRequired"`
	QuestionOrder            pgtype.Int4        `db:"question_order" json:"questionOrder"`
	QuestionOptions          []byte             `db:"question_options" json:"questionOptions"`
	QuestionValidationRules  []byte             `db:"question_validation_rules" json:"questionValidationRules"`
	QuestionSettings         []byte             `db:"question_settings" json:"questionSettings"`
	QuestionCreatedAt        pgtype.Timestamptz `db:"question_created_at" json:"questionCreatedAt"`
	QuestionUpdatedAt        pgtype.Timestamptz `db:"question_updated_at" json:"questionUpdatedAt"`
}

func (q *Queries) GetFormWithQuestions(ctx context.Context, id uuid.UUID) (GetFormWithQuestionsRow, error) {
	row := q.db.QueryRow(ctx, getFormWithQuestions, id)
	var i GetFormWithQuestionsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Theme,
		&i.IsPublished,
		&i.IsAcceptingResponses,
		&i.RequireLogin,
		&i.AllowMultipleSubmissions,
		&i.ShowProgressBar,
		&i.CustomThankYouMessage,
		&i.RedirectUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuestionID,
		&i.QuestionType,
		&i.QuestionLabel,
		&i.QuestionDescription,
		&i.QuestionPlaceholder,
		&i.QuestionRequired,
		&i.QuestionOrder,
		&i.QuestionOptions,
		&i.QuestionValidationRules,
		&i.QuestionSettings,
		&i.QuestionCreatedAt,
		&i.QuestionUpdatedAt,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, form_id, type, label, description, placeholder, required, order_index, options, validation_rules, settings, created_at, updated_at FROM form.questions
WHERE id = $1::uuid
`

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (FormQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i FormQuestion
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Type,
		&i.Label,
		&i.Description,
		&i.Placeholder,
		&i.Required,
		&i.OrderIndex,
		&i.Options,
		&i.ValidationRules,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFormQuestions = `-- name: ListFormQuestions :many
SELECT id, form_id, type, label, description, placeholder, required, order_index, options, validation_rules, settings, created_at, updated_at FROM form.questions
WHERE form_id = $1::uuid
ORDER BY order_index
`

func (q *Queries) ListFormQuestions(ctx context.Context, formID uuid.UUID) ([]FormQuestion, error) {
	rows, err := q.db.Query(ctx, listFormQuestions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormQuestion{}
	for rows.Next() {
		var i FormQuestion
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Type,
			&i.Label,
			&i.Description,
			&i.Placeholder,
			&i.Required,
			&i.OrderIndex,
			&i.Options,
			&i.ValidationRules,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserForms = `-- name: ListUserForms :many
SELECT f.id, f.user_id, f.title, f.description, f.slug, f.theme, f.is_published, f.is_accepting_responses, f.require_login, f.allow_multiple_submissions, f.show_progress_bar, f.custom_thank_you_message, f.redirect_url, f.settings, f.created_at, f.updated_at FROM form.forms f
WHERE f.user_id = $1::uuid
  AND ($2::int = 0 OR
       ($2::int = 1 AND f.is_published = false) OR
       ($2::int = 2 AND f.is_published = true) OR
       ($2::int = 3 AND f.is_published = false))
  AND ($3::text = '' OR f.title ILIKE '%' || $3::text || '%')
ORDER BY f.updated_at DESC
LIMIT $5::int OFFSET $4::int
`

type ListUserFormsParams struct {
	UserID       uuid.UUID `db:"user_id" json:"userId"`
	StatusFilter int32     `db:"status_filter" json:"statusFilter"`
	SearchQuery  string    `db:"search_query" json:"searchQuery"`
	OffsetCount  int32     `db:"offset_count" json:"offsetCount"`
	LimitCount   int32     `db:"limit_count" json:"limitCount"`
}

func (q *Queries) ListUserForms(ctx context.Context, arg ListUserFormsParams) ([]FormForm, error) {
	rows, err := q.db.Query(ctx, listUserForms,
		arg.UserID,
		arg.StatusFilter,
		arg.SearchQuery,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormForm{}
	for rows.Next() {
		var i FormForm
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.Theme,
			&i.IsPublished,
			&i.IsAcceptingResponses,
			&i.RequireLogin,
			&i.AllowMultipleSubmissions,
			&i.ShowProgressBar,
			&i.CustomThankYouMessage,
			&i.RedirectUrl,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishForm = `-- name: PublishForm :one
/**
 * Publish a form.
 *
 * Updates the form with the given id and user_id to be published.
 *
 * @param id The id of the form to publish.
 * @param user_id The id of the user who owns the form.
 * @return The updated form.
 */
UPDATE form.forms
SET is_published = true
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id, user_id, title, description, slug, theme, is_published, is_accepting_responses, require_login, allow_multiple_submissions, show_progress_bar, custom_thank_you_message, redirect_url, settings, created_at, updated_at
`

type PublishFormParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) PublishForm(ctx context.Context, arg PublishFormParams) (FormForm, error) {
	row := q.db.QueryRow(ctx, publishForm, arg.ID, arg.UserID)
	var i FormForm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Theme,
		&i.IsPublished,
		&i.IsAcceptingResponses,
		&i.RequireLogin,
		&i.AllowMultipleSubmissions,
		&i.ShowProgressBar,
		&i.CustomThankYouMessage,
		&i.RedirectUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateForm = `-- name: UpdateForm :one
UPDATE form.forms
SET
    title = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    theme = COALESCE($3::text, theme),
    is_published = COALESCE($4::boolean, is_published),
    is_accepting_responses = COALESCE($5::boolean, is_accepting_responses),
    require_login = COALESCE($6::boolean, require_login),
    allow_multiple_submissions = COALESCE($7::boolean, allow_multiple_submissions),
    show_progress_bar = COALESCE($8::boolean, show_progress_bar),
    custom_thank_you_message = COALESCE($9::text, custom_thank_you_message),
    redirect_url = COALESCE($10::text, redirect_url),
    settings = COALESCE($11::jsonb, settings)
WHERE id = $12::uuid AND user_id = $13::uuid
RETURNING id, user_id, title, description, slug, theme, is_published, is_accepting_responses, require_login, allow_multiple_submissions, show_progress_bar, custom_thank_you_message, redirect_url, settings, created_at, updated_at
`

type UpdateFormParams struct {
	Title                    string          `db:"title" json:"title"`
	Description              string          `db:"description" json:"description"`
	Theme                    string          `db:"theme" json:"theme"`
	IsPublished              bool            `db:"is_published" json:"isPublished"`
	IsAcceptingResponses     bool            `db:"is_accepting_responses" json:"isAcceptingResponses"`
	RequireLogin             bool            `db:"require_login" json:"requireLogin"`
	AllowMultipleSubmissions bool            `db:"allow_multiple_submissions" json:"allowMultipleSubmissions"`
	ShowProgressBar          bool            `db:"show_progress_bar" json:"showProgressBar"`
	CustomThankYouMessage    string          `db:"custom_thank_you_message" json:"customThankYouMessage"`
	RedirectUrl              string          `db:"redirect_url" json:"redirectUrl"`
	Settings                 json.RawMessage `db:"settings" json:"settings"`
	ID                       uuid.UUID       `db:"id" json:"id"`
	UserID                   uuid.UUID       `db:"user_id" json:"userId"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (FormForm, error) {
	row := q.db.QueryRow(ctx, updateForm,
		arg.Title,
		arg.Description,
		arg.Theme,
		arg.IsPublished,
		arg.IsAcceptingResponses,
		arg.RequireLogin,
		arg.AllowMultipleSubmissions,
		arg.ShowProgressBar,
		arg.CustomThankYouMessage,
		arg.RedirectUrl,
		arg.Settings,
		arg.ID,
		arg.UserID,
	)
	var i FormForm
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Theme,
		&i.IsPublished,
		&i.IsAcceptingResponses,
		&i.RequireLogin,
		&i.AllowMultipleSubmissions,
		&i.ShowProgressBar,
		&i.CustomThankYouMessage,
		&i.RedirectUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
