// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FormAnalytic struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	FormID           uuid.UUID   `db:"form_id" json:"formId"`
	Date             pgtype.Date `db:"date" json:"date"`
	TotalViews       int32       `db:"total_views" json:"totalViews"`
	TotalStarts      int32       `db:"total_starts" json:"totalStarts"`
	TotalCompletions int32       `db:"total_completions" json:"totalCompletions"`
	CreatedAt        time.Time   `db:"created_at" json:"createdAt"`
}

type FormAnswer struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	ResponseID    uuid.UUID      `db:"response_id" json:"responseId"`
	QuestionID    uuid.UUID      `db:"question_id" json:"questionId"`
	AnswerText    pgtype.Text    `db:"answer_text" json:"answerText"`
	AnswerNumber  pgtype.Numeric `db:"answer_number" json:"answerNumber"`
	AnswerDate    pgtype.Date    `db:"answer_date" json:"answerDate"`
	AnswerTime    pgtype.Time    `db:"answer_time" json:"answerTime"`
	AnswerChoices []byte         `db:"answer_choices" json:"answerChoices"`
	AnswerFileUrl pgtype.Text    `db:"answer_file_url" json:"answerFileUrl"`
	CreatedAt     time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updatedAt"`
}

type FormFileUpload struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	FormID           uuid.UUID   `db:"form_id" json:"formId"`
	QuestionID       uuid.UUID   `db:"question_id" json:"questionId"`
	ResponseID       pgtype.UUID `db:"response_id" json:"responseId"`
	Filename         string      `db:"filename" json:"filename"`
	OriginalFilename string      `db:"original_filename" json:"originalFilename"`
	MimeType         string      `db:"mime_type" json:"mimeType"`
	FileSize         int64       `db:"file_size" json:"fileSize"`
	S3Key            string      `db:"s3_key" json:"s3Key"`
	S3Url            string      `db:"s3_url" json:"s3Url"`
	UploadedByUserID pgtype.UUID `db:"uploaded_by_user_id" json:"uploadedByUserId"`
	CreatedAt        time.Time   `db:"created_at" json:"createdAt"`
}

type FormForm struct {
	ID                       uuid.UUID   `db:"id" json:"id"`
	UserID                   uuid.UUID   `db:"user_id" json:"userId"`
	Title                    string      `db:"title" json:"title"`
	Description              pgtype.Text `db:"description" json:"description"`
	Theme                    string      `db:"theme" json:"theme"`
	IsPublished              bool        `db:"is_published" json:"isPublished"`
	IsAcceptingResponses     bool        `db:"is_accepting_responses" json:"isAcceptingResponses"`
	RequireLogin             bool        `db:"require_login" json:"requireLogin"`
	AllowMultipleSubmissions bool        `db:"allow_multiple_submissions" json:"allowMultipleSubmissions"`
	ShowProgressBar          bool        `db:"show_progress_bar" json:"showProgressBar"`
	CustomThankYouMessage    pgtype.Text `db:"custom_thank_you_message" json:"customThankYouMessage"`
	RedirectUrl              pgtype.Text `db:"redirect_url" json:"redirectUrl"`
	Settings                 []byte      `db:"settings" json:"settings"`
	CreatedAt                time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt                time.Time   `db:"updated_at" json:"updatedAt"`
}

type FormQuestion struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	FormID          uuid.UUID   `db:"form_id" json:"formId"`
	Type            string      `db:"type" json:"type"`
	Label           string      `db:"label" json:"label"`
	Description     pgtype.Text `db:"description" json:"description"`
	Placeholder     pgtype.Text `db:"placeholder" json:"placeholder"`
	Required        bool        `db:"required" json:"required"`
	OrderIndex      int32       `db:"order_index" json:"orderIndex"`
	Options         []byte      `db:"options" json:"options"`
	ValidationRules []byte      `db:"validation_rules" json:"validationRules"`
	Settings        []byte      `db:"settings" json:"settings"`
	CreatedAt       time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updatedAt"`
}

type FormResponse struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	FormID           uuid.UUID          `db:"form_id" json:"formId"`
	RespondentUserID pgtype.UUID        `db:"respondent_user_id" json:"respondentUserId"`
	RespondentEmail  pgtype.Text        `db:"respondent_email" json:"respondentEmail"`
	RespondentName   pgtype.Text        `db:"respondent_name" json:"respondentName"`
	IpAddress        *netip.Addr        `db:"ip_address" json:"ipAddress"`
	UserAgent        pgtype.Text        `db:"user_agent" json:"userAgent"`
	Completed        bool               `db:"completed" json:"completed"`
	SubmittedAt      pgtype.Timestamptz `db:"submitted_at" json:"submittedAt"`
	CreatedAt        time.Time          `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time          `db:"updated_at" json:"updatedAt"`
}

type FormUser struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	WeladeeUserID int32       `db:"weladee_user_id" json:"weladeeUserId"`
	Email         string      `db:"email" json:"email"`
	FullName      pgtype.Text `db:"full_name" json:"fullName"`
	AvatarUrl     pgtype.Text `db:"avatar_url" json:"avatarUrl"`
	CreatedAt     time.Time   `db:"created_at" json:"createdAt"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updatedAt"`
}
