// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteResponse(ctx context.Context, id uuid.UUID) (FormResponse, error)
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (FormAnswer, error)
	CreateFileUpload(ctx context.Context, arg CreateFileUploadParams) (uuid.UUID, error)
	CreateForm(ctx context.Context, arg CreateFormParams) (FormForm, error)
	CreateFormUser(ctx context.Context, arg CreateFormUserParams) (FormUser, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (FormQuestion, error)
	CreateResponse(ctx context.Context, arg CreateResponseParams) (FormResponse, error)
	DeleteForm(ctx context.Context, arg DeleteFormParams) error
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteResponse(ctx context.Context, id uuid.UUID) error
	GetFileUpload(ctx context.Context, id uuid.UUID) (FormFileUpload, error)
	GetForm(ctx context.Context, id uuid.UUID) (FormForm, error)
	GetFormBySlug(ctx context.Context, slug string) (FormForm, error)
	GetFormResponsesWithAnswers(ctx context.Context, formID uuid.UUID) ([]GetFormResponsesWithAnswersRow, error)
	GetFormStats(ctx context.Context, formID uuid.UUID) (GetFormStatsRow, error)
	GetFormUser(ctx context.Context, id uuid.UUID) (FormUser, error)
	GetFormUserByWeladeeID(ctx context.Context, weladeeUserID int32) (FormUser, error)
	GetFormWithQuestions(ctx context.Context, id uuid.UUID) (GetFormWithQuestionsRow, error)
	GetQuestion(ctx context.Context, id uuid.UUID) (FormQuestion, error)
	GetResponse(ctx context.Context, id uuid.UUID) (FormResponse, error)
	GetResponseAnswers(ctx context.Context, responseID uuid.UUID) ([]FormAnswer, error)
	IncrementFormCompletions(ctx context.Context, formID uuid.UUID) error
	IncrementFormStarts(ctx context.Context, formID uuid.UUID) error
	IncrementFormViews(ctx context.Context, formID uuid.UUID) error
	ListFormQuestions(ctx context.Context, formID uuid.UUID) ([]FormQuestion, error)
	ListFormResponses(ctx context.Context, arg ListFormResponsesParams) ([]FormResponse, error)
	ListUserForms(ctx context.Context, arg ListUserFormsParams) ([]FormForm, error)
	PublishForm(ctx context.Context, arg PublishFormParams) (FormForm, error)
	ReorderQuestions(ctx context.Context, arg ReorderQuestionsParams) error
	// Note: slug field not in current schema, may need to add
	UpdateForm(ctx context.Context, arg UpdateFormParams) (FormForm, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (FormQuestion, error)
}

var _ Querier = (*Queries)(nil)
