// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteResponse(ctx context.Context, id uuid.UUID) (FormResponse, error)
	CountFormResponses(ctx context.Context, formID uuid.UUID) (int64, error)
	CountNewResponsesSince(ctx context.Context, arg CountNewResponsesSinceParams) (int64, error)
	CountUserForms(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (FormAnswer, error)
	CreateFileUpload(ctx context.Context, arg CreateFileUploadParams) (uuid.UUID, error)
	CreateForm(ctx context.Context, arg CreateFormParams) (FormForm, error)
	CreateFormUser(ctx context.Context, arg CreateFormUserParams) (FormUser, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (FormQuestion, error)
	CreateResponse(ctx context.Context, arg CreateResponseParams) (FormResponse, error)
	DeleteForm(ctx context.Context, arg DeleteFormParams) error
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteResponse(ctx context.Context, id uuid.UUID) error
	GetChoiceQuestionStats(ctx context.Context, questionID uuid.UUID) ([]GetChoiceQuestionStatsRow, error)
	GetCompletionFunnel(ctx context.Context, arg GetCompletionFunnelParams) (GetCompletionFunnelRow, error)
	GetCompletionStatsForDate(ctx context.Context, arg GetCompletionStatsForDateParams) ([]GetCompletionStatsForDateRow, error)
	GetDailyNotificationLog(ctx context.Context, arg GetDailyNotificationLogParams) (FormDailyNotificationLog, error)
	GetDailyStatsRange(ctx context.Context, arg GetDailyStatsRangeParams) ([]FormDailyStat, error)
	GetDayOfWeekDistribution(ctx context.Context, arg GetDayOfWeekDistributionParams) ([]GetDayOfWeekDistributionRow, error)
	GetDeviceBreakdown(ctx context.Context, formID uuid.UUID) ([]GetDeviceBreakdownRow, error)
	GetFileUpload(ctx context.Context, id uuid.UUID) (FormFileUpload, error)
	GetForm(ctx context.Context, id uuid.UUID) (FormForm, error)
	// Try to look up by ID (if slug is a UUID) or by slug column
	GetFormBySlug(ctx context.Context, slug string) (FormForm, error)
	GetFormOverviewStats(ctx context.Context, formID uuid.UUID) (GetFormOverviewStatsRow, error)
	GetFormResponsesWithAnswers(ctx context.Context, formID uuid.UUID) ([]GetFormResponsesWithAnswersRow, error)
	GetFormStats(ctx context.Context, formID uuid.UUID) (GetFormStatsRow, error)
	GetFormUser(ctx context.Context, id uuid.UUID) (FormUser, error)
	GetFormUserByWeladeeID(ctx context.Context, weladeeUserID int32) (FormUser, error)
	GetFormWithQuestions(ctx context.Context, id uuid.UUID) (GetFormWithQuestionsRow, error)
	// ============================================================
	// Daily Digest Queries
	// ============================================================
	GetFormsWithDailyNotifications(ctx context.Context) ([]GetFormsWithDailyNotificationsRow, error)
	GetGeographicDistribution(ctx context.Context, formID uuid.UUID) ([]GetGeographicDistributionRow, error)
	GetHourlyDistribution(ctx context.Context, arg GetHourlyDistributionParams) ([]GetHourlyDistributionRow, error)
	GetNPSScore(ctx context.Context, questionID uuid.UUID) (GetNPSScoreRow, error)
	GetQuestion(ctx context.Context, id uuid.UUID) (FormQuestion, error)
	GetQuestionAnalytics(ctx context.Context, formID uuid.UUID) ([]GetQuestionAnalyticsRow, error)
	GetQuestionDropOff(ctx context.Context, formID uuid.UUID) ([]GetQuestionDropOffRow, error)
	GetRatingQuestionStats(ctx context.Context, questionID uuid.UUID) ([]GetRatingQuestionStatsRow, error)
	GetResponse(ctx context.Context, id uuid.UUID) (FormResponse, error)
	GetResponseAnswers(ctx context.Context, responseID uuid.UUID) ([]FormAnswer, error)
	GetResponseCompletionTrend(ctx context.Context, arg GetResponseCompletionTrendParams) ([]GetResponseCompletionTrendRow, error)
	GetResponseStartsForDate(ctx context.Context, arg GetResponseStartsForDateParams) ([]GetResponseStartsForDateRow, error)
	GetResponseTrend(ctx context.Context, arg GetResponseTrendParams) ([]GetResponseTrendRow, error)
	GetViewStatsForDate(ctx context.Context, arg GetViewStatsForDateParams) ([]GetViewStatsForDateRow, error)
	IncrementFormCompletionCount(ctx context.Context, formID uuid.UUID) error
	IncrementFormResponseCount(ctx context.Context, formID uuid.UUID) error
	IncrementFormViewCount(ctx context.Context, formID uuid.UUID) error
	ListFormQuestions(ctx context.Context, formID uuid.UUID) ([]FormQuestion, error)
	ListFormResponses(ctx context.Context, arg ListFormResponsesParams) ([]FormResponse, error)
	ListUserForms(ctx context.Context, arg ListUserFormsParams) ([]ListUserFormsRow, error)
	PublishForm(ctx context.Context, arg PublishFormParams) (FormForm, error)
	ReorderQuestions(ctx context.Context, arg ReorderQuestionsParams) error
	TrackFormView(ctx context.Context, arg TrackFormViewParams) (FormFormView, error)
	TrackQuestionInteraction(ctx context.Context, arg TrackQuestionInteractionParams) (FormQuestionInteraction, error)
	TrackResponseStart(ctx context.Context, arg TrackResponseStartParams) (FormResponseStart, error)
	UpdateDailyStats(ctx context.Context, arg UpdateDailyStatsParams) (FormDailyStat, error)
	UpdateForm(ctx context.Context, arg UpdateFormParams) (FormForm, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (FormQuestion, error)
	UpsertDailyNotificationLog(ctx context.Context, arg UpsertDailyNotificationLogParams) (FormDailyNotificationLog, error)
}

var _ Querier = (*Queries)(nil)
