// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: response.sql

package sqlc

import (
	"context"
	"encoding/json"
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeResponse = `-- name: CompleteResponse :one
UPDATE form.responses
SET
    completed = true,
    submitted_at = NOW()
WHERE id = $1::uuid
RETURNING id, form_id, respondent_user_id, respondent_email, respondent_name, completed, submitted_at, completion_time_seconds, session_id, device_type, browser, os, country, city, referrer, ip_address, user_agent, created_at, updated_at
`

func (q *Queries) CompleteResponse(ctx context.Context, id uuid.UUID) (FormResponse, error) {
	row := q.db.QueryRow(ctx, completeResponse, id)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.RespondentUserID,
		&i.RespondentEmail,
		&i.RespondentName,
		&i.Completed,
		&i.SubmittedAt,
		&i.CompletionTimeSeconds,
		&i.SessionID,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.Country,
		&i.City,
		&i.Referrer,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFormResponses = `-- name: CountFormResponses :one
SELECT COUNT(*) as count
FROM form.responses
WHERE form_id = $1::uuid
`

func (q *Queries) CountFormResponses(ctx context.Context, formID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFormResponses, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO form.answers (
    response_id, question_id, answer_text, answer_number,
    answer_date, answer_time, answer_choices, answer_file_url
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::float8,
    CASE WHEN NULLIF($5::text, '') IS NULL THEN NULL ELSE $5::date END,
    CASE WHEN NULLIF($6::text, '') IS NULL THEN NULL ELSE $6::time END,
    $7::jsonb,
    $8::text
)
ON CONFLICT (response_id, question_id)
DO UPDATE SET
    answer_text = EXCLUDED.answer_text,
    answer_number = EXCLUDED.answer_number,
    answer_date = EXCLUDED.answer_date,
    answer_time = EXCLUDED.answer_time,
    answer_choices = EXCLUDED.answer_choices,
    answer_file_url = EXCLUDED.answer_file_url,
    updated_at = NOW()
RETURNING id, response_id, question_id, answer_text, answer_number, answer_date, answer_time, answer_choices, answer_file_url, created_at, updated_at
`

type CreateAnswerParams struct {
	ResponseID    uuid.UUID       `db:"response_id" json:"responseId"`
	QuestionID    uuid.UUID       `db:"question_id" json:"questionId"`
	AnswerText    string          `db:"answer_text" json:"answerText"`
	AnswerNumber  float64         `db:"answer_number" json:"answerNumber"`
	AnswerDate    string          `db:"answer_date" json:"answerDate"`
	AnswerTime    string          `db:"answer_time" json:"answerTime"`
	AnswerChoices json.RawMessage `db:"answer_choices" json:"answerChoices"`
	AnswerFileUrl string          `db:"answer_file_url" json:"answerFileUrl"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (FormAnswer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.ResponseID,
		arg.QuestionID,
		arg.AnswerText,
		arg.AnswerNumber,
		arg.AnswerDate,
		arg.AnswerTime,
		arg.AnswerChoices,
		arg.AnswerFileUrl,
	)
	var i FormAnswer
	err := row.Scan(
		&i.ID,
		&i.ResponseID,
		&i.QuestionID,
		&i.AnswerText,
		&i.AnswerNumber,
		&i.AnswerDate,
		&i.AnswerTime,
		&i.AnswerChoices,
		&i.AnswerFileUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResponse = `-- name: CreateResponse :one
INSERT INTO form.responses (
    form_id, respondent_user_id, respondent_email, respondent_name,
    ip_address, user_agent, completed, submitted_at
)
VALUES (
    $1::uuid,
    CASE WHEN $2::uuid = '00000000-0000-0000-0000-000000000000'::uuid THEN NULL ELSE $2::uuid END,
    $3::text,
    $4::text,
    $5::inet,
    $6::text,
    $7::boolean,
    COALESCE($8::timestamptz, NOW())
)
RETURNING id, form_id, respondent_user_id, respondent_email, respondent_name, completed, submitted_at, completion_time_seconds, session_id, device_type, browser, os, country, city, referrer, ip_address, user_agent, created_at, updated_at
`

type CreateResponseParams struct {
	FormID           uuid.UUID `db:"form_id" json:"formId"`
	RespondentUserID uuid.UUID `db:"respondent_user_id" json:"respondentUserId"`
	RespondentEmail  string    `db:"respondent_email" json:"respondentEmail"`
	RespondentName   string    `db:"respondent_name" json:"respondentName"`
	IpAddress        net.IP    `db:"ip_address" json:"ipAddress"`
	UserAgent        string    `db:"user_agent" json:"userAgent"`
	Completed        bool      `db:"completed" json:"completed"`
	SubmittedAt      time.Time `db:"submitted_at" json:"submittedAt"`
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (FormResponse, error) {
	row := q.db.QueryRow(ctx, createResponse,
		arg.FormID,
		arg.RespondentUserID,
		arg.RespondentEmail,
		arg.RespondentName,
		arg.IpAddress,
		arg.UserAgent,
		arg.Completed,
		arg.SubmittedAt,
	)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.RespondentUserID,
		&i.RespondentEmail,
		&i.RespondentName,
		&i.Completed,
		&i.SubmittedAt,
		&i.CompletionTimeSeconds,
		&i.SessionID,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.Country,
		&i.City,
		&i.Referrer,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResponse = `-- name: DeleteResponse :exec
DELETE FROM form.responses
WHERE id = $1::uuid
`

func (q *Queries) DeleteResponse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResponse, id)
	return err
}

const getFormResponsesWithAnswers = `-- name: GetFormResponsesWithAnswers :many
SELECT
    r.id as response_id,
    r.form_id,
    r.respondent_user_id,
    r.respondent_email,
    r.respondent_name,
    r.completed,
    r.submitted_at,
    r.created_at,
    a.id as answer_id,
    a.question_id,
    a.answer_text,
    a.answer_number,
    a.answer_date,
    a.answer_time,
    a.answer_choices,
    a.answer_file_url
FROM form.responses r
LEFT JOIN form.answers a ON r.id = a.response_id
WHERE r.form_id = $1::uuid AND r.completed = true
ORDER BY r.submitted_at DESC, a.question_id
`

type GetFormResponsesWithAnswersRow struct {
	ResponseID       uuid.UUID          `db:"response_id" json:"responseId"`
	FormID           uuid.UUID          `db:"form_id" json:"formId"`
	RespondentUserID pgtype.UUID        `db:"respondent_user_id" json:"respondentUserId"`
	RespondentEmail  pgtype.Text        `db:"respondent_email" json:"respondentEmail"`
	RespondentName   pgtype.Text        `db:"respondent_name" json:"respondentName"`
	Completed        bool               `db:"completed" json:"completed"`
	SubmittedAt      pgtype.Timestamptz `db:"submitted_at" json:"submittedAt"`
	CreatedAt        time.Time          `db:"created_at" json:"createdAt"`
	AnswerID         pgtype.UUID        `db:"answer_id" json:"answerId"`
	QuestionID       pgtype.UUID        `db:"question_id" json:"questionId"`
	AnswerText       pgtype.Text        `db:"answer_text" json:"answerText"`
	AnswerNumber     pgtype.Numeric     `db:"answer_number" json:"answerNumber"`
	AnswerDate       pgtype.Date        `db:"answer_date" json:"answerDate"`
	AnswerTime       pgtype.Time        `db:"answer_time" json:"answerTime"`
	AnswerChoices    []byte             `db:"answer_choices" json:"answerChoices"`
	AnswerFileUrl    pgtype.Text        `db:"answer_file_url" json:"answerFileUrl"`
}

func (q *Queries) GetFormResponsesWithAnswers(ctx context.Context, formID uuid.UUID) ([]GetFormResponsesWithAnswersRow, error) {
	rows, err := q.db.Query(ctx, getFormResponsesWithAnswers, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFormResponsesWithAnswersRow{}
	for rows.Next() {
		var i GetFormResponsesWithAnswersRow
		if err := rows.Scan(
			&i.ResponseID,
			&i.FormID,
			&i.RespondentUserID,
			&i.RespondentEmail,
			&i.RespondentName,
			&i.Completed,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.AnswerID,
			&i.QuestionID,
			&i.AnswerText,
			&i.AnswerNumber,
			&i.AnswerDate,
			&i.AnswerTime,
			&i.AnswerChoices,
			&i.AnswerFileUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResponse = `-- name: GetResponse :one
SELECT id, form_id, respondent_user_id, respondent_email, respondent_name, completed, submitted_at, completion_time_seconds, session_id, device_type, browser, os, country, city, referrer, ip_address, user_agent, created_at, updated_at FROM form.responses
WHERE id = $1::uuid
`

func (q *Queries) GetResponse(ctx context.Context, id uuid.UUID) (FormResponse, error) {
	row := q.db.QueryRow(ctx, getResponse, id)
	var i FormResponse
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.RespondentUserID,
		&i.RespondentEmail,
		&i.RespondentName,
		&i.Completed,
		&i.SubmittedAt,
		&i.CompletionTimeSeconds,
		&i.SessionID,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.Country,
		&i.City,
		&i.Referrer,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResponseAnswers = `-- name: GetResponseAnswers :many
SELECT
    a.id,
    a.response_id,
    a.question_id,
    a.answer_text,
    a.answer_number,
    a.answer_date,
    a.answer_time,
    a.answer_choices,
    a.answer_file_url,
    a.created_at,
    a.updated_at
FROM form.answers a
WHERE a.response_id = $1::uuid
`

func (q *Queries) GetResponseAnswers(ctx context.Context, responseID uuid.UUID) ([]FormAnswer, error) {
	rows, err := q.db.Query(ctx, getResponseAnswers, responseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormAnswer{}
	for rows.Next() {
		var i FormAnswer
		if err := rows.Scan(
			&i.ID,
			&i.ResponseID,
			&i.QuestionID,
			&i.AnswerText,
			&i.AnswerNumber,
			&i.AnswerDate,
			&i.AnswerTime,
			&i.AnswerChoices,
			&i.AnswerFileUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormResponses = `-- name: ListFormResponses :many
SELECT id, form_id, respondent_user_id, respondent_email, respondent_name, completed, submitted_at, completion_time_seconds, session_id, device_type, browser, os, country, city, referrer, ip_address, user_agent, created_at, updated_at FROM form.responses
WHERE form_id = $1::uuid
ORDER BY submitted_at DESC NULLS LAST, created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListFormResponsesParams struct {
	FormID      uuid.UUID `db:"form_id" json:"formId"`
	OffsetCount int32     `db:"offset_count" json:"offsetCount"`
	LimitCount  int32     `db:"limit_count" json:"limitCount"`
}

func (q *Queries) ListFormResponses(ctx context.Context, arg ListFormResponsesParams) ([]FormResponse, error) {
	rows, err := q.db.Query(ctx, listFormResponses, arg.FormID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormResponse{}
	for rows.Next() {
		var i FormResponse
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.RespondentUserID,
			&i.RespondentEmail,
			&i.RespondentName,
			&i.Completed,
			&i.SubmittedAt,
			&i.CompletionTimeSeconds,
			&i.SessionID,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.Referrer,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
