// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFormUser = `-- name: CreateFormUser :one
INSERT INTO form.users (weladee_user_id, email, full_name, avatar_url)
VALUES ($1::int, $2::text, $3::text, $4::text)
ON CONFLICT (weladee_user_id) DO UPDATE
SET
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, weladee_user_id, email, full_name, avatar_url, created_at, updated_at
`

type CreateFormUserParams struct {
	WeladeeUserID int32  `db:"weladee_user_id" json:"weladeeUserId"`
	Email         string `db:"email" json:"email"`
	FullName      string `db:"full_name" json:"fullName"`
	AvatarUrl     string `db:"avatar_url" json:"avatarUrl"`
}

func (q *Queries) CreateFormUser(ctx context.Context, arg CreateFormUserParams) (FormUser, error) {
	row := q.db.QueryRow(ctx, createFormUser,
		arg.WeladeeUserID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
	)
	var i FormUser
	err := row.Scan(
		&i.ID,
		&i.WeladeeUserID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormUser = `-- name: GetFormUser :one
SELECT id, weladee_user_id, email, full_name, avatar_url, created_at, updated_at FROM form.users
WHERE id = $1::uuid
`

func (q *Queries) GetFormUser(ctx context.Context, id uuid.UUID) (FormUser, error) {
	row := q.db.QueryRow(ctx, getFormUser, id)
	var i FormUser
	err := row.Scan(
		&i.ID,
		&i.WeladeeUserID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormUserByWeladeeID = `-- name: GetFormUserByWeladeeID :one
SELECT id, weladee_user_id, email, full_name, avatar_url, created_at, updated_at FROM form.users
WHERE weladee_user_id = $1::int
`

func (q *Queries) GetFormUserByWeladeeID(ctx context.Context, weladeeUserID int32) (FormUser, error) {
	row := q.db.QueryRow(ctx, getFormUserByWeladeeID, weladeeUserID)
	var i FormUser
	err := row.Scan(
		&i.ID,
		&i.WeladeeUserID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
