// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/form.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FormService_CreateForm_FullMethodName       = "/weladee.form.v1.FormService/CreateForm"
	FormService_GetForm_FullMethodName          = "/weladee.form.v1.FormService/GetForm"
	FormService_GetFormBySlug_FullMethodName    = "/weladee.form.v1.FormService/GetFormBySlug"
	FormService_UpdateForm_FullMethodName       = "/weladee.form.v1.FormService/UpdateForm"
	FormService_DeleteForm_FullMethodName       = "/weladee.form.v1.FormService/DeleteForm"
	FormService_ListForms_FullMethodName        = "/weladee.form.v1.FormService/ListForms"
	FormService_PublishForm_FullMethodName      = "/weladee.form.v1.FormService/PublishForm"
	FormService_GetFormStats_FullMethodName     = "/weladee.form.v1.FormService/GetFormStats"
	FormService_CreateQuestion_FullMethodName   = "/weladee.form.v1.FormService/CreateQuestion"
	FormService_UpdateQuestion_FullMethodName   = "/weladee.form.v1.FormService/UpdateQuestion"
	FormService_DeleteQuestion_FullMethodName   = "/weladee.form.v1.FormService/DeleteQuestion"
	FormService_ReorderQuestions_FullMethodName = "/weladee.form.v1.FormService/ReorderQuestions"
)

// FormServiceClient is the client API for FormService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Form Service
type FormServiceClient interface {
	CreateForm(ctx context.Context, in *CreateFormRequest, opts ...grpc.CallOption) (*CreateFormResponse, error)
	GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*GetFormResponse, error)
	GetFormBySlug(ctx context.Context, in *GetFormBySlugRequest, opts ...grpc.CallOption) (*GetFormBySlugResponse, error)
	UpdateForm(ctx context.Context, in *UpdateFormRequest, opts ...grpc.CallOption) (*UpdateFormResponse, error)
	DeleteForm(ctx context.Context, in *DeleteFormRequest, opts ...grpc.CallOption) (*DeleteFormResponse, error)
	ListForms(ctx context.Context, in *ListFormsRequest, opts ...grpc.CallOption) (*ListFormsResponse, error)
	PublishForm(ctx context.Context, in *PublishFormRequest, opts ...grpc.CallOption) (*PublishFormResponse, error)
	GetFormStats(ctx context.Context, in *GetFormStatsRequest, opts ...grpc.CallOption) (*GetFormStatsResponse, error)
	// Question management
	CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error)
	UpdateQuestion(ctx context.Context, in *UpdateQuestionRequest, opts ...grpc.CallOption) (*UpdateQuestionResponse, error)
	DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionResponse, error)
	ReorderQuestions(ctx context.Context, in *ReorderQuestionsRequest, opts ...grpc.CallOption) (*ReorderQuestionsResponse, error)
}

type formServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFormServiceClient(cc grpc.ClientConnInterface) FormServiceClient {
	return &formServiceClient{cc}
}

func (c *formServiceClient) CreateForm(ctx context.Context, in *CreateFormRequest, opts ...grpc.CallOption) (*CreateFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFormResponse)
	err := c.cc.Invoke(ctx, FormService_CreateForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*GetFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFormResponse)
	err := c.cc.Invoke(ctx, FormService_GetForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) GetFormBySlug(ctx context.Context, in *GetFormBySlugRequest, opts ...grpc.CallOption) (*GetFormBySlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFormBySlugResponse)
	err := c.cc.Invoke(ctx, FormService_GetFormBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) UpdateForm(ctx context.Context, in *UpdateFormRequest, opts ...grpc.CallOption) (*UpdateFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFormResponse)
	err := c.cc.Invoke(ctx, FormService_UpdateForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) DeleteForm(ctx context.Context, in *DeleteFormRequest, opts ...grpc.CallOption) (*DeleteFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFormResponse)
	err := c.cc.Invoke(ctx, FormService_DeleteForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) ListForms(ctx context.Context, in *ListFormsRequest, opts ...grpc.CallOption) (*ListFormsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFormsResponse)
	err := c.cc.Invoke(ctx, FormService_ListForms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) PublishForm(ctx context.Context, in *PublishFormRequest, opts ...grpc.CallOption) (*PublishFormResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishFormResponse)
	err := c.cc.Invoke(ctx, FormService_PublishForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) GetFormStats(ctx context.Context, in *GetFormStatsRequest, opts ...grpc.CallOption) (*GetFormStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFormStatsResponse)
	err := c.cc.Invoke(ctx, FormService_GetFormStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuestionResponse)
	err := c.cc.Invoke(ctx, FormService_CreateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) UpdateQuestion(ctx context.Context, in *UpdateQuestionRequest, opts ...grpc.CallOption) (*UpdateQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuestionResponse)
	err := c.cc.Invoke(ctx, FormService_UpdateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQuestionResponse)
	err := c.cc.Invoke(ctx, FormService_DeleteQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formServiceClient) ReorderQuestions(ctx context.Context, in *ReorderQuestionsRequest, opts ...grpc.CallOption) (*ReorderQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReorderQuestionsResponse)
	err := c.cc.Invoke(ctx, FormService_ReorderQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormServiceServer is the server API for FormService service.
// All implementations must embed UnimplementedFormServiceServer
// for forward compatibility.
//
// Form Service
type FormServiceServer interface {
	CreateForm(context.Context, *CreateFormRequest) (*CreateFormResponse, error)
	GetForm(context.Context, *GetFormRequest) (*GetFormResponse, error)
	GetFormBySlug(context.Context, *GetFormBySlugRequest) (*GetFormBySlugResponse, error)
	UpdateForm(context.Context, *UpdateFormRequest) (*UpdateFormResponse, error)
	DeleteForm(context.Context, *DeleteFormRequest) (*DeleteFormResponse, error)
	ListForms(context.Context, *ListFormsRequest) (*ListFormsResponse, error)
	PublishForm(context.Context, *PublishFormRequest) (*PublishFormResponse, error)
	GetFormStats(context.Context, *GetFormStatsRequest) (*GetFormStatsResponse, error)
	// Question management
	CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error)
	UpdateQuestion(context.Context, *UpdateQuestionRequest) (*UpdateQuestionResponse, error)
	DeleteQuestion(context.Context, *DeleteQuestionRequest) (*DeleteQuestionResponse, error)
	ReorderQuestions(context.Context, *ReorderQuestionsRequest) (*ReorderQuestionsResponse, error)
	mustEmbedUnimplementedFormServiceServer()
}

// UnimplementedFormServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFormServiceServer struct{}

func (UnimplementedFormServiceServer) CreateForm(context.Context, *CreateFormRequest) (*CreateFormResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateForm not implemented")
}
func (UnimplementedFormServiceServer) GetForm(context.Context, *GetFormRequest) (*GetFormResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForm not implemented")
}
func (UnimplementedFormServiceServer) GetFormBySlug(context.Context, *GetFormBySlugRequest) (*GetFormBySlugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFormBySlug not implemented")
}
func (UnimplementedFormServiceServer) UpdateForm(context.Context, *UpdateFormRequest) (*UpdateFormResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateForm not implemented")
}
func (UnimplementedFormServiceServer) DeleteForm(context.Context, *DeleteFormRequest) (*DeleteFormResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteForm not implemented")
}
func (UnimplementedFormServiceServer) ListForms(context.Context, *ListFormsRequest) (*ListFormsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListForms not implemented")
}
func (UnimplementedFormServiceServer) PublishForm(context.Context, *PublishFormRequest) (*PublishFormResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishForm not implemented")
}
func (UnimplementedFormServiceServer) GetFormStats(context.Context, *GetFormStatsRequest) (*GetFormStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFormStats not implemented")
}
func (UnimplementedFormServiceServer) CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedFormServiceServer) UpdateQuestion(context.Context, *UpdateQuestionRequest) (*UpdateQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuestion not implemented")
}
func (UnimplementedFormServiceServer) DeleteQuestion(context.Context, *DeleteQuestionRequest) (*DeleteQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuestion not implemented")
}
func (UnimplementedFormServiceServer) ReorderQuestions(context.Context, *ReorderQuestionsRequest) (*ReorderQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReorderQuestions not implemented")
}
func (UnimplementedFormServiceServer) mustEmbedUnimplementedFormServiceServer() {}
func (UnimplementedFormServiceServer) testEmbeddedByValue()                     {}

// UnsafeFormServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormServiceServer will
// result in compilation errors.
type UnsafeFormServiceServer interface {
	mustEmbedUnimplementedFormServiceServer()
}

func RegisterFormServiceServer(s grpc.ServiceRegistrar, srv FormServiceServer) {
	// If the following call panics, it indicates UnimplementedFormServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FormService_ServiceDesc, srv)
}

func _FormService_CreateForm_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CreateFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).CreateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_CreateForm_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).CreateForm(ctx, req.(*CreateFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_GetForm_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).GetForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_GetForm_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).GetForm(ctx, req.(*GetFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_GetFormBySlug_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetFormBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).GetFormBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_GetFormBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).GetFormBySlug(ctx, req.(*GetFormBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_UpdateForm_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(UpdateFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).UpdateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_UpdateForm_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).UpdateForm(ctx, req.(*UpdateFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_DeleteForm_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).DeleteForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_DeleteForm_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).DeleteForm(ctx, req.(*DeleteFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_ListForms_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ListFormsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).ListForms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_ListForms_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).ListForms(ctx, req.(*ListFormsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_PublishForm_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(PublishFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).PublishForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_PublishForm_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).PublishForm(ctx, req.(*PublishFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_GetFormStats_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetFormStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).GetFormStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_GetFormStats_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).GetFormStats(ctx, req.(*GetFormStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_CreateQuestion_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CreateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_CreateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).CreateQuestion(ctx, req.(*CreateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_UpdateQuestion_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(UpdateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).UpdateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_UpdateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).UpdateQuestion(ctx, req.(*UpdateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_DeleteQuestion_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_DeleteQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).DeleteQuestion(ctx, req.(*DeleteQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormService_ReorderQuestions_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ReorderQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormServiceServer).ReorderQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormService_ReorderQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(FormServiceServer).ReorderQuestions(ctx, req.(*ReorderQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormService_ServiceDesc is the grpc.ServiceDesc for FormService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weladee.form.v1.FormService",
	HandlerType: (*FormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForm",
			Handler:    _FormService_CreateForm_Handler,
		},
		{
			MethodName: "GetForm",
			Handler:    _FormService_GetForm_Handler,
		},
		{
			MethodName: "GetFormBySlug",
			Handler:    _FormService_GetFormBySlug_Handler,
		},
		{
			MethodName: "UpdateForm",
			Handler:    _FormService_UpdateForm_Handler,
		},
		{
			MethodName: "DeleteForm",
			Handler:    _FormService_DeleteForm_Handler,
		},
		{
			MethodName: "ListForms",
			Handler:    _FormService_ListForms_Handler,
		},
		{
			MethodName: "PublishForm",
			Handler:    _FormService_PublishForm_Handler,
		},
		{
			MethodName: "GetFormStats",
			Handler:    _FormService_GetFormStats_Handler,
		},
		{
			MethodName: "CreateQuestion",
			Handler:    _FormService_CreateQuestion_Handler,
		},
		{
			MethodName: "UpdateQuestion",
			Handler:    _FormService_UpdateQuestion_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _FormService_DeleteQuestion_Handler,
		},
		{
			MethodName: "ReorderQuestions",
			Handler:    _FormService_ReorderQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/form.proto",
}
