// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/auth.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/weladee/weladee-form/proto/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "weladee.form.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceSendMagicLinkProcedure is the fully-qualified name of the AuthService's SendMagicLink
	// RPC.
	AuthServiceSendMagicLinkProcedure = "/weladee.form.v1.AuthService/SendMagicLink"
	// AuthServiceHandleOAuthCallbackProcedure is the fully-qualified name of the AuthService's
	// HandleOAuthCallback RPC.
	AuthServiceHandleOAuthCallbackProcedure = "/weladee.form.v1.AuthService/HandleOAuthCallback"
	// AuthServiceValidateTokenProcedure is the fully-qualified name of the AuthService's ValidateToken
	// RPC.
	AuthServiceValidateTokenProcedure = "/weladee.form.v1.AuthService/ValidateToken"
	// AuthServiceGetUserSessionProcedure is the fully-qualified name of the AuthService's
	// GetUserSession RPC.
	AuthServiceGetUserSessionProcedure = "/weladee.form.v1.AuthService/GetUserSession"
)

// AuthServiceClient is a client for the weladee.form.v1.AuthService service.
type AuthServiceClient interface {
	SendMagicLink(context.Context, *connect.Request[pb.SendMagicLinkRequest]) (*connect.Response[pb.SendMagicLinkResponse], error)
	HandleOAuthCallback(context.Context, *connect.Request[pb.HandleOAuthCallbackRequest]) (*connect.Response[pb.HandleOAuthCallbackResponse], error)
	ValidateToken(context.Context, *connect.Request[pb.ValidateTokenRequest]) (*connect.Response[pb.ValidateTokenResponse], error)
	GetUserSession(context.Context, *connect.Request[pb.GetUserSessionRequest]) (*connect.Response[pb.GetUserSessionResponse], error)
}

// NewAuthServiceClient constructs a client for the weladee.form.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := pb.File_proto_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		sendMagicLink: connect.NewClient[pb.SendMagicLinkRequest, pb.SendMagicLinkResponse](
			httpClient,
			baseURL+AuthServiceSendMagicLinkProcedure,
			connect.WithSchema(authServiceMethods.ByName("SendMagicLink")),
			connect.WithClientOptions(opts...),
		),
		handleOAuthCallback: connect.NewClient[pb.HandleOAuthCallbackRequest, pb.HandleOAuthCallbackResponse](
			httpClient,
			baseURL+AuthServiceHandleOAuthCallbackProcedure,
			connect.WithSchema(authServiceMethods.ByName("HandleOAuthCallback")),
			connect.WithClientOptions(opts...),
		),
		validateToken: connect.NewClient[pb.ValidateTokenRequest, pb.ValidateTokenResponse](
			httpClient,
			baseURL+AuthServiceValidateTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
			connect.WithClientOptions(opts...),
		),
		getUserSession: connect.NewClient[pb.GetUserSessionRequest, pb.GetUserSessionResponse](
			httpClient,
			baseURL+AuthServiceGetUserSessionProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetUserSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	sendMagicLink       *connect.Client[pb.SendMagicLinkRequest, pb.SendMagicLinkResponse]
	handleOAuthCallback *connect.Client[pb.HandleOAuthCallbackRequest, pb.HandleOAuthCallbackResponse]
	validateToken       *connect.Client[pb.ValidateTokenRequest, pb.ValidateTokenResponse]
	getUserSession      *connect.Client[pb.GetUserSessionRequest, pb.GetUserSessionResponse]
}

// SendMagicLink calls weladee.form.v1.AuthService.SendMagicLink.
func (c *authServiceClient) SendMagicLink(ctx context.Context, req *connect.Request[pb.SendMagicLinkRequest]) (*connect.Response[pb.SendMagicLinkResponse], error) {
	return c.sendMagicLink.CallUnary(ctx, req)
}

// HandleOAuthCallback calls weladee.form.v1.AuthService.HandleOAuthCallback.
func (c *authServiceClient) HandleOAuthCallback(ctx context.Context, req *connect.Request[pb.HandleOAuthCallbackRequest]) (*connect.Response[pb.HandleOAuthCallbackResponse], error) {
	return c.handleOAuthCallback.CallUnary(ctx, req)
}

// ValidateToken calls weladee.form.v1.AuthService.ValidateToken.
func (c *authServiceClient) ValidateToken(ctx context.Context, req *connect.Request[pb.ValidateTokenRequest]) (*connect.Response[pb.ValidateTokenResponse], error) {
	return c.validateToken.CallUnary(ctx, req)
}

// GetUserSession calls weladee.form.v1.AuthService.GetUserSession.
func (c *authServiceClient) GetUserSession(ctx context.Context, req *connect.Request[pb.GetUserSessionRequest]) (*connect.Response[pb.GetUserSessionResponse], error) {
	return c.getUserSession.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the weladee.form.v1.AuthService service.
type AuthServiceHandler interface {
	SendMagicLink(context.Context, *connect.Request[pb.SendMagicLinkRequest]) (*connect.Response[pb.SendMagicLinkResponse], error)
	HandleOAuthCallback(context.Context, *connect.Request[pb.HandleOAuthCallbackRequest]) (*connect.Response[pb.HandleOAuthCallbackResponse], error)
	ValidateToken(context.Context, *connect.Request[pb.ValidateTokenRequest]) (*connect.Response[pb.ValidateTokenResponse], error)
	GetUserSession(context.Context, *connect.Request[pb.GetUserSessionRequest]) (*connect.Response[pb.GetUserSessionResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := pb.File_proto_auth_proto.Services().ByName("AuthService").Methods()
	authServiceSendMagicLinkHandler := connect.NewUnaryHandler(
		AuthServiceSendMagicLinkProcedure,
		svc.SendMagicLink,
		connect.WithSchema(authServiceMethods.ByName("SendMagicLink")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceHandleOAuthCallbackHandler := connect.NewUnaryHandler(
		AuthServiceHandleOAuthCallbackProcedure,
		svc.HandleOAuthCallback,
		connect.WithSchema(authServiceMethods.ByName("HandleOAuthCallback")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceValidateTokenHandler := connect.NewUnaryHandler(
		AuthServiceValidateTokenProcedure,
		svc.ValidateToken,
		connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetUserSessionHandler := connect.NewUnaryHandler(
		AuthServiceGetUserSessionProcedure,
		svc.GetUserSession,
		connect.WithSchema(authServiceMethods.ByName("GetUserSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/weladee.form.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceSendMagicLinkProcedure:
			authServiceSendMagicLinkHandler.ServeHTTP(w, r)
		case AuthServiceHandleOAuthCallbackProcedure:
			authServiceHandleOAuthCallbackHandler.ServeHTTP(w, r)
		case AuthServiceValidateTokenProcedure:
			authServiceValidateTokenHandler.ServeHTTP(w, r)
		case AuthServiceGetUserSessionProcedure:
			authServiceGetUserSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) SendMagicLink(context.Context, *connect.Request[pb.SendMagicLinkRequest]) (*connect.Response[pb.SendMagicLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.AuthService.SendMagicLink is not implemented"))
}

func (UnimplementedAuthServiceHandler) HandleOAuthCallback(context.Context, *connect.Request[pb.HandleOAuthCallbackRequest]) (*connect.Response[pb.HandleOAuthCallbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.AuthService.HandleOAuthCallback is not implemented"))
}

func (UnimplementedAuthServiceHandler) ValidateToken(context.Context, *connect.Request[pb.ValidateTokenRequest]) (*connect.Response[pb.ValidateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.AuthService.ValidateToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetUserSession(context.Context, *connect.Request[pb.GetUserSessionRequest]) (*connect.Response[pb.GetUserSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.AuthService.GetUserSession is not implemented"))
}
