// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/form.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/weladee/weladee-form/proto/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FormServiceName is the fully-qualified name of the FormService service.
	FormServiceName = "weladee.form.v1.FormService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FormServiceCreateFormProcedure is the fully-qualified name of the FormService's CreateForm RPC.
	FormServiceCreateFormProcedure = "/weladee.form.v1.FormService/CreateForm"
	// FormServiceGetFormProcedure is the fully-qualified name of the FormService's GetForm RPC.
	FormServiceGetFormProcedure = "/weladee.form.v1.FormService/GetForm"
	// FormServiceGetFormBySlugProcedure is the fully-qualified name of the FormService's GetFormBySlug
	// RPC.
	FormServiceGetFormBySlugProcedure = "/weladee.form.v1.FormService/GetFormBySlug"
	// FormServiceUpdateFormProcedure is the fully-qualified name of the FormService's UpdateForm RPC.
	FormServiceUpdateFormProcedure = "/weladee.form.v1.FormService/UpdateForm"
	// FormServiceDeleteFormProcedure is the fully-qualified name of the FormService's DeleteForm RPC.
	FormServiceDeleteFormProcedure = "/weladee.form.v1.FormService/DeleteForm"
	// FormServiceListFormsProcedure is the fully-qualified name of the FormService's ListForms RPC.
	FormServiceListFormsProcedure = "/weladee.form.v1.FormService/ListForms"
	// FormServicePublishFormProcedure is the fully-qualified name of the FormService's PublishForm RPC.
	FormServicePublishFormProcedure = "/weladee.form.v1.FormService/PublishForm"
	// FormServiceGetFormStatsProcedure is the fully-qualified name of the FormService's GetFormStats
	// RPC.
	FormServiceGetFormStatsProcedure = "/weladee.form.v1.FormService/GetFormStats"
	// FormServiceCreateQuestionProcedure is the fully-qualified name of the FormService's
	// CreateQuestion RPC.
	FormServiceCreateQuestionProcedure = "/weladee.form.v1.FormService/CreateQuestion"
	// FormServiceUpdateQuestionProcedure is the fully-qualified name of the FormService's
	// UpdateQuestion RPC.
	FormServiceUpdateQuestionProcedure = "/weladee.form.v1.FormService/UpdateQuestion"
	// FormServiceDeleteQuestionProcedure is the fully-qualified name of the FormService's
	// DeleteQuestion RPC.
	FormServiceDeleteQuestionProcedure = "/weladee.form.v1.FormService/DeleteQuestion"
	// FormServiceReorderQuestionsProcedure is the fully-qualified name of the FormService's
	// ReorderQuestions RPC.
	FormServiceReorderQuestionsProcedure = "/weladee.form.v1.FormService/ReorderQuestions"
)

// FormServiceClient is a client for the weladee.form.v1.FormService service.
type FormServiceClient interface {
	CreateForm(context.Context, *connect.Request[pb.CreateFormRequest]) (*connect.Response[pb.CreateFormResponse], error)
	GetForm(context.Context, *connect.Request[pb.GetFormRequest]) (*connect.Response[pb.GetFormResponse], error)
	GetFormBySlug(context.Context, *connect.Request[pb.GetFormBySlugRequest]) (*connect.Response[pb.GetFormBySlugResponse], error)
	UpdateForm(context.Context, *connect.Request[pb.UpdateFormRequest]) (*connect.Response[pb.UpdateFormResponse], error)
	DeleteForm(context.Context, *connect.Request[pb.DeleteFormRequest]) (*connect.Response[pb.DeleteFormResponse], error)
	ListForms(context.Context, *connect.Request[pb.ListFormsRequest]) (*connect.Response[pb.ListFormsResponse], error)
	PublishForm(context.Context, *connect.Request[pb.PublishFormRequest]) (*connect.Response[pb.PublishFormResponse], error)
	GetFormStats(context.Context, *connect.Request[pb.GetFormStatsRequest]) (*connect.Response[pb.GetFormStatsResponse], error)
	// Question management
	CreateQuestion(context.Context, *connect.Request[pb.CreateQuestionRequest]) (*connect.Response[pb.CreateQuestionResponse], error)
	UpdateQuestion(context.Context, *connect.Request[pb.UpdateQuestionRequest]) (*connect.Response[pb.UpdateQuestionResponse], error)
	DeleteQuestion(context.Context, *connect.Request[pb.DeleteQuestionRequest]) (*connect.Response[pb.DeleteQuestionResponse], error)
	ReorderQuestions(context.Context, *connect.Request[pb.ReorderQuestionsRequest]) (*connect.Response[pb.ReorderQuestionsResponse], error)
}

// NewFormServiceClient constructs a client for the weladee.form.v1.FormService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFormServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FormServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	formServiceMethods := pb.File_proto_form_proto.Services().ByName("FormService").Methods()
	return &formServiceClient{
		createForm: connect.NewClient[pb.CreateFormRequest, pb.CreateFormResponse](
			httpClient,
			baseURL+FormServiceCreateFormProcedure,
			connect.WithSchema(formServiceMethods.ByName("CreateForm")),
			connect.WithClientOptions(opts...),
		),
		getForm: connect.NewClient[pb.GetFormRequest, pb.GetFormResponse](
			httpClient,
			baseURL+FormServiceGetFormProcedure,
			connect.WithSchema(formServiceMethods.ByName("GetForm")),
			connect.WithClientOptions(opts...),
		),
		getFormBySlug: connect.NewClient[pb.GetFormBySlugRequest, pb.GetFormBySlugResponse](
			httpClient,
			baseURL+FormServiceGetFormBySlugProcedure,
			connect.WithSchema(formServiceMethods.ByName("GetFormBySlug")),
			connect.WithClientOptions(opts...),
		),
		updateForm: connect.NewClient[pb.UpdateFormRequest, pb.UpdateFormResponse](
			httpClient,
			baseURL+FormServiceUpdateFormProcedure,
			connect.WithSchema(formServiceMethods.ByName("UpdateForm")),
			connect.WithClientOptions(opts...),
		),
		deleteForm: connect.NewClient[pb.DeleteFormRequest, pb.DeleteFormResponse](
			httpClient,
			baseURL+FormServiceDeleteFormProcedure,
			connect.WithSchema(formServiceMethods.ByName("DeleteForm")),
			connect.WithClientOptions(opts...),
		),
		listForms: connect.NewClient[pb.ListFormsRequest, pb.ListFormsResponse](
			httpClient,
			baseURL+FormServiceListFormsProcedure,
			connect.WithSchema(formServiceMethods.ByName("ListForms")),
			connect.WithClientOptions(opts...),
		),
		publishForm: connect.NewClient[pb.PublishFormRequest, pb.PublishFormResponse](
			httpClient,
			baseURL+FormServicePublishFormProcedure,
			connect.WithSchema(formServiceMethods.ByName("PublishForm")),
			connect.WithClientOptions(opts...),
		),
		getFormStats: connect.NewClient[pb.GetFormStatsRequest, pb.GetFormStatsResponse](
			httpClient,
			baseURL+FormServiceGetFormStatsProcedure,
			connect.WithSchema(formServiceMethods.ByName("GetFormStats")),
			connect.WithClientOptions(opts...),
		),
		createQuestion: connect.NewClient[pb.CreateQuestionRequest, pb.CreateQuestionResponse](
			httpClient,
			baseURL+FormServiceCreateQuestionProcedure,
			connect.WithSchema(formServiceMethods.ByName("CreateQuestion")),
			connect.WithClientOptions(opts...),
		),
		updateQuestion: connect.NewClient[pb.UpdateQuestionRequest, pb.UpdateQuestionResponse](
			httpClient,
			baseURL+FormServiceUpdateQuestionProcedure,
			connect.WithSchema(formServiceMethods.ByName("UpdateQuestion")),
			connect.WithClientOptions(opts...),
		),
		deleteQuestion: connect.NewClient[pb.DeleteQuestionRequest, pb.DeleteQuestionResponse](
			httpClient,
			baseURL+FormServiceDeleteQuestionProcedure,
			connect.WithSchema(formServiceMethods.ByName("DeleteQuestion")),
			connect.WithClientOptions(opts...),
		),
		reorderQuestions: connect.NewClient[pb.ReorderQuestionsRequest, pb.ReorderQuestionsResponse](
			httpClient,
			baseURL+FormServiceReorderQuestionsProcedure,
			connect.WithSchema(formServiceMethods.ByName("ReorderQuestions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// formServiceClient implements FormServiceClient.
type formServiceClient struct {
	createForm       *connect.Client[pb.CreateFormRequest, pb.CreateFormResponse]
	getForm          *connect.Client[pb.GetFormRequest, pb.GetFormResponse]
	getFormBySlug    *connect.Client[pb.GetFormBySlugRequest, pb.GetFormBySlugResponse]
	updateForm       *connect.Client[pb.UpdateFormRequest, pb.UpdateFormResponse]
	deleteForm       *connect.Client[pb.DeleteFormRequest, pb.DeleteFormResponse]
	listForms        *connect.Client[pb.ListFormsRequest, pb.ListFormsResponse]
	publishForm      *connect.Client[pb.PublishFormRequest, pb.PublishFormResponse]
	getFormStats     *connect.Client[pb.GetFormStatsRequest, pb.GetFormStatsResponse]
	createQuestion   *connect.Client[pb.CreateQuestionRequest, pb.CreateQuestionResponse]
	updateQuestion   *connect.Client[pb.UpdateQuestionRequest, pb.UpdateQuestionResponse]
	deleteQuestion   *connect.Client[pb.DeleteQuestionRequest, pb.DeleteQuestionResponse]
	reorderQuestions *connect.Client[pb.ReorderQuestionsRequest, pb.ReorderQuestionsResponse]
}

// CreateForm calls weladee.form.v1.FormService.CreateForm.
func (c *formServiceClient) CreateForm(ctx context.Context, req *connect.Request[pb.CreateFormRequest]) (*connect.Response[pb.CreateFormResponse], error) {
	return c.createForm.CallUnary(ctx, req)
}

// GetForm calls weladee.form.v1.FormService.GetForm.
func (c *formServiceClient) GetForm(ctx context.Context, req *connect.Request[pb.GetFormRequest]) (*connect.Response[pb.GetFormResponse], error) {
	return c.getForm.CallUnary(ctx, req)
}

// GetFormBySlug calls weladee.form.v1.FormService.GetFormBySlug.
func (c *formServiceClient) GetFormBySlug(ctx context.Context, req *connect.Request[pb.GetFormBySlugRequest]) (*connect.Response[pb.GetFormBySlugResponse], error) {
	return c.getFormBySlug.CallUnary(ctx, req)
}

// UpdateForm calls weladee.form.v1.FormService.UpdateForm.
func (c *formServiceClient) UpdateForm(ctx context.Context, req *connect.Request[pb.UpdateFormRequest]) (*connect.Response[pb.UpdateFormResponse], error) {
	return c.updateForm.CallUnary(ctx, req)
}

// DeleteForm calls weladee.form.v1.FormService.DeleteForm.
func (c *formServiceClient) DeleteForm(ctx context.Context, req *connect.Request[pb.DeleteFormRequest]) (*connect.Response[pb.DeleteFormResponse], error) {
	return c.deleteForm.CallUnary(ctx, req)
}

// ListForms calls weladee.form.v1.FormService.ListForms.
func (c *formServiceClient) ListForms(ctx context.Context, req *connect.Request[pb.ListFormsRequest]) (*connect.Response[pb.ListFormsResponse], error) {
	return c.listForms.CallUnary(ctx, req)
}

// PublishForm calls weladee.form.v1.FormService.PublishForm.
func (c *formServiceClient) PublishForm(ctx context.Context, req *connect.Request[pb.PublishFormRequest]) (*connect.Response[pb.PublishFormResponse], error) {
	return c.publishForm.CallUnary(ctx, req)
}

// GetFormStats calls weladee.form.v1.FormService.GetFormStats.
func (c *formServiceClient) GetFormStats(ctx context.Context, req *connect.Request[pb.GetFormStatsRequest]) (*connect.Response[pb.GetFormStatsResponse], error) {
	return c.getFormStats.CallUnary(ctx, req)
}

// CreateQuestion calls weladee.form.v1.FormService.CreateQuestion.
func (c *formServiceClient) CreateQuestion(ctx context.Context, req *connect.Request[pb.CreateQuestionRequest]) (*connect.Response[pb.CreateQuestionResponse], error) {
	return c.createQuestion.CallUnary(ctx, req)
}

// UpdateQuestion calls weladee.form.v1.FormService.UpdateQuestion.
func (c *formServiceClient) UpdateQuestion(ctx context.Context, req *connect.Request[pb.UpdateQuestionRequest]) (*connect.Response[pb.UpdateQuestionResponse], error) {
	return c.updateQuestion.CallUnary(ctx, req)
}

// DeleteQuestion calls weladee.form.v1.FormService.DeleteQuestion.
func (c *formServiceClient) DeleteQuestion(ctx context.Context, req *connect.Request[pb.DeleteQuestionRequest]) (*connect.Response[pb.DeleteQuestionResponse], error) {
	return c.deleteQuestion.CallUnary(ctx, req)
}

// ReorderQuestions calls weladee.form.v1.FormService.ReorderQuestions.
func (c *formServiceClient) ReorderQuestions(ctx context.Context, req *connect.Request[pb.ReorderQuestionsRequest]) (*connect.Response[pb.ReorderQuestionsResponse], error) {
	return c.reorderQuestions.CallUnary(ctx, req)
}

// FormServiceHandler is an implementation of the weladee.form.v1.FormService service.
type FormServiceHandler interface {
	CreateForm(context.Context, *connect.Request[pb.CreateFormRequest]) (*connect.Response[pb.CreateFormResponse], error)
	GetForm(context.Context, *connect.Request[pb.GetFormRequest]) (*connect.Response[pb.GetFormResponse], error)
	GetFormBySlug(context.Context, *connect.Request[pb.GetFormBySlugRequest]) (*connect.Response[pb.GetFormBySlugResponse], error)
	UpdateForm(context.Context, *connect.Request[pb.UpdateFormRequest]) (*connect.Response[pb.UpdateFormResponse], error)
	DeleteForm(context.Context, *connect.Request[pb.DeleteFormRequest]) (*connect.Response[pb.DeleteFormResponse], error)
	ListForms(context.Context, *connect.Request[pb.ListFormsRequest]) (*connect.Response[pb.ListFormsResponse], error)
	PublishForm(context.Context, *connect.Request[pb.PublishFormRequest]) (*connect.Response[pb.PublishFormResponse], error)
	GetFormStats(context.Context, *connect.Request[pb.GetFormStatsRequest]) (*connect.Response[pb.GetFormStatsResponse], error)
	// Question management
	CreateQuestion(context.Context, *connect.Request[pb.CreateQuestionRequest]) (*connect.Response[pb.CreateQuestionResponse], error)
	UpdateQuestion(context.Context, *connect.Request[pb.UpdateQuestionRequest]) (*connect.Response[pb.UpdateQuestionResponse], error)
	DeleteQuestion(context.Context, *connect.Request[pb.DeleteQuestionRequest]) (*connect.Response[pb.DeleteQuestionResponse], error)
	ReorderQuestions(context.Context, *connect.Request[pb.ReorderQuestionsRequest]) (*connect.Response[pb.ReorderQuestionsResponse], error)
}

// NewFormServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFormServiceHandler(svc FormServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	formServiceMethods := pb.File_proto_form_proto.Services().ByName("FormService").Methods()
	formServiceCreateFormHandler := connect.NewUnaryHandler(
		FormServiceCreateFormProcedure,
		svc.CreateForm,
		connect.WithSchema(formServiceMethods.ByName("CreateForm")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceGetFormHandler := connect.NewUnaryHandler(
		FormServiceGetFormProcedure,
		svc.GetForm,
		connect.WithSchema(formServiceMethods.ByName("GetForm")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceGetFormBySlugHandler := connect.NewUnaryHandler(
		FormServiceGetFormBySlugProcedure,
		svc.GetFormBySlug,
		connect.WithSchema(formServiceMethods.ByName("GetFormBySlug")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceUpdateFormHandler := connect.NewUnaryHandler(
		FormServiceUpdateFormProcedure,
		svc.UpdateForm,
		connect.WithSchema(formServiceMethods.ByName("UpdateForm")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceDeleteFormHandler := connect.NewUnaryHandler(
		FormServiceDeleteFormProcedure,
		svc.DeleteForm,
		connect.WithSchema(formServiceMethods.ByName("DeleteForm")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceListFormsHandler := connect.NewUnaryHandler(
		FormServiceListFormsProcedure,
		svc.ListForms,
		connect.WithSchema(formServiceMethods.ByName("ListForms")),
		connect.WithHandlerOptions(opts...),
	)
	formServicePublishFormHandler := connect.NewUnaryHandler(
		FormServicePublishFormProcedure,
		svc.PublishForm,
		connect.WithSchema(formServiceMethods.ByName("PublishForm")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceGetFormStatsHandler := connect.NewUnaryHandler(
		FormServiceGetFormStatsProcedure,
		svc.GetFormStats,
		connect.WithSchema(formServiceMethods.ByName("GetFormStats")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceCreateQuestionHandler := connect.NewUnaryHandler(
		FormServiceCreateQuestionProcedure,
		svc.CreateQuestion,
		connect.WithSchema(formServiceMethods.ByName("CreateQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceUpdateQuestionHandler := connect.NewUnaryHandler(
		FormServiceUpdateQuestionProcedure,
		svc.UpdateQuestion,
		connect.WithSchema(formServiceMethods.ByName("UpdateQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceDeleteQuestionHandler := connect.NewUnaryHandler(
		FormServiceDeleteQuestionProcedure,
		svc.DeleteQuestion,
		connect.WithSchema(formServiceMethods.ByName("DeleteQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	formServiceReorderQuestionsHandler := connect.NewUnaryHandler(
		FormServiceReorderQuestionsProcedure,
		svc.ReorderQuestions,
		connect.WithSchema(formServiceMethods.ByName("ReorderQuestions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/weladee.form.v1.FormService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FormServiceCreateFormProcedure:
			formServiceCreateFormHandler.ServeHTTP(w, r)
		case FormServiceGetFormProcedure:
			formServiceGetFormHandler.ServeHTTP(w, r)
		case FormServiceGetFormBySlugProcedure:
			formServiceGetFormBySlugHandler.ServeHTTP(w, r)
		case FormServiceUpdateFormProcedure:
			formServiceUpdateFormHandler.ServeHTTP(w, r)
		case FormServiceDeleteFormProcedure:
			formServiceDeleteFormHandler.ServeHTTP(w, r)
		case FormServiceListFormsProcedure:
			formServiceListFormsHandler.ServeHTTP(w, r)
		case FormServicePublishFormProcedure:
			formServicePublishFormHandler.ServeHTTP(w, r)
		case FormServiceGetFormStatsProcedure:
			formServiceGetFormStatsHandler.ServeHTTP(w, r)
		case FormServiceCreateQuestionProcedure:
			formServiceCreateQuestionHandler.ServeHTTP(w, r)
		case FormServiceUpdateQuestionProcedure:
			formServiceUpdateQuestionHandler.ServeHTTP(w, r)
		case FormServiceDeleteQuestionProcedure:
			formServiceDeleteQuestionHandler.ServeHTTP(w, r)
		case FormServiceReorderQuestionsProcedure:
			formServiceReorderQuestionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFormServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFormServiceHandler struct{}

func (UnimplementedFormServiceHandler) CreateForm(context.Context, *connect.Request[pb.CreateFormRequest]) (*connect.Response[pb.CreateFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.CreateForm is not implemented"))
}

func (UnimplementedFormServiceHandler) GetForm(context.Context, *connect.Request[pb.GetFormRequest]) (*connect.Response[pb.GetFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.GetForm is not implemented"))
}

func (UnimplementedFormServiceHandler) GetFormBySlug(context.Context, *connect.Request[pb.GetFormBySlugRequest]) (*connect.Response[pb.GetFormBySlugResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.GetFormBySlug is not implemented"))
}

func (UnimplementedFormServiceHandler) UpdateForm(context.Context, *connect.Request[pb.UpdateFormRequest]) (*connect.Response[pb.UpdateFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.UpdateForm is not implemented"))
}

func (UnimplementedFormServiceHandler) DeleteForm(context.Context, *connect.Request[pb.DeleteFormRequest]) (*connect.Response[pb.DeleteFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.DeleteForm is not implemented"))
}

func (UnimplementedFormServiceHandler) ListForms(context.Context, *connect.Request[pb.ListFormsRequest]) (*connect.Response[pb.ListFormsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.ListForms is not implemented"))
}

func (UnimplementedFormServiceHandler) PublishForm(context.Context, *connect.Request[pb.PublishFormRequest]) (*connect.Response[pb.PublishFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.PublishForm is not implemented"))
}

func (UnimplementedFormServiceHandler) GetFormStats(context.Context, *connect.Request[pb.GetFormStatsRequest]) (*connect.Response[pb.GetFormStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.GetFormStats is not implemented"))
}

func (UnimplementedFormServiceHandler) CreateQuestion(context.Context, *connect.Request[pb.CreateQuestionRequest]) (*connect.Response[pb.CreateQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.CreateQuestion is not implemented"))
}

func (UnimplementedFormServiceHandler) UpdateQuestion(context.Context, *connect.Request[pb.UpdateQuestionRequest]) (*connect.Response[pb.UpdateQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.UpdateQuestion is not implemented"))
}

func (UnimplementedFormServiceHandler) DeleteQuestion(context.Context, *connect.Request[pb.DeleteQuestionRequest]) (*connect.Response[pb.DeleteQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.DeleteQuestion is not implemented"))
}

func (UnimplementedFormServiceHandler) ReorderQuestions(context.Context, *connect.Request[pb.ReorderQuestionsRequest]) (*connect.Response[pb.ReorderQuestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.FormService.ReorderQuestions is not implemented"))
}
