// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/response.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/weladee/weladee-form/proto/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResponseServiceName is the fully-qualified name of the ResponseService service.
	ResponseServiceName = "weladee.form.v1.ResponseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResponseServiceSubmitResponseProcedure is the fully-qualified name of the ResponseService's
	// SubmitResponse RPC.
	ResponseServiceSubmitResponseProcedure = "/weladee.form.v1.ResponseService/SubmitResponse"
	// ResponseServiceGetResponseProcedure is the fully-qualified name of the ResponseService's
	// GetResponse RPC.
	ResponseServiceGetResponseProcedure = "/weladee.form.v1.ResponseService/GetResponse"
	// ResponseServiceListResponsesProcedure is the fully-qualified name of the ResponseService's
	// ListResponses RPC.
	ResponseServiceListResponsesProcedure = "/weladee.form.v1.ResponseService/ListResponses"
	// ResponseServiceDeleteResponseProcedure is the fully-qualified name of the ResponseService's
	// DeleteResponse RPC.
	ResponseServiceDeleteResponseProcedure = "/weladee.form.v1.ResponseService/DeleteResponse"
	// ResponseServiceExportResponsesProcedure is the fully-qualified name of the ResponseService's
	// ExportResponses RPC.
	ResponseServiceExportResponsesProcedure = "/weladee.form.v1.ResponseService/ExportResponses"
)

// ResponseServiceClient is a client for the weladee.form.v1.ResponseService service.
type ResponseServiceClient interface {
	SubmitResponse(context.Context, *connect.Request[pb.SubmitResponseRequest]) (*connect.Response[pb.SubmitResponseResponse], error)
	GetResponse(context.Context, *connect.Request[pb.GetResponseRequest]) (*connect.Response[pb.GetResponseResponse], error)
	ListResponses(context.Context, *connect.Request[pb.ListResponsesRequest]) (*connect.Response[pb.ListResponsesResponse], error)
	DeleteResponse(context.Context, *connect.Request[pb.DeleteResponseRequest]) (*connect.Response[pb.DeleteResponseResponse], error)
	ExportResponses(context.Context, *connect.Request[pb.ExportResponsesRequest]) (*connect.Response[pb.ExportResponsesResponse], error)
}

// NewResponseServiceClient constructs a client for the weladee.form.v1.ResponseService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResponseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResponseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	responseServiceMethods := pb.File_proto_response_proto.Services().ByName("ResponseService").Methods()
	return &responseServiceClient{
		submitResponse: connect.NewClient[pb.SubmitResponseRequest, pb.SubmitResponseResponse](
			httpClient,
			baseURL+ResponseServiceSubmitResponseProcedure,
			connect.WithSchema(responseServiceMethods.ByName("SubmitResponse")),
			connect.WithClientOptions(opts...),
		),
		getResponse: connect.NewClient[pb.GetResponseRequest, pb.GetResponseResponse](
			httpClient,
			baseURL+ResponseServiceGetResponseProcedure,
			connect.WithSchema(responseServiceMethods.ByName("GetResponse")),
			connect.WithClientOptions(opts...),
		),
		listResponses: connect.NewClient[pb.ListResponsesRequest, pb.ListResponsesResponse](
			httpClient,
			baseURL+ResponseServiceListResponsesProcedure,
			connect.WithSchema(responseServiceMethods.ByName("ListResponses")),
			connect.WithClientOptions(opts...),
		),
		deleteResponse: connect.NewClient[pb.DeleteResponseRequest, pb.DeleteResponseResponse](
			httpClient,
			baseURL+ResponseServiceDeleteResponseProcedure,
			connect.WithSchema(responseServiceMethods.ByName("DeleteResponse")),
			connect.WithClientOptions(opts...),
		),
		exportResponses: connect.NewClient[pb.ExportResponsesRequest, pb.ExportResponsesResponse](
			httpClient,
			baseURL+ResponseServiceExportResponsesProcedure,
			connect.WithSchema(responseServiceMethods.ByName("ExportResponses")),
			connect.WithClientOptions(opts...),
		),
	}
}

// responseServiceClient implements ResponseServiceClient.
type responseServiceClient struct {
	submitResponse  *connect.Client[pb.SubmitResponseRequest, pb.SubmitResponseResponse]
	getResponse     *connect.Client[pb.GetResponseRequest, pb.GetResponseResponse]
	listResponses   *connect.Client[pb.ListResponsesRequest, pb.ListResponsesResponse]
	deleteResponse  *connect.Client[pb.DeleteResponseRequest, pb.DeleteResponseResponse]
	exportResponses *connect.Client[pb.ExportResponsesRequest, pb.ExportResponsesResponse]
}

// SubmitResponse calls weladee.form.v1.ResponseService.SubmitResponse.
func (c *responseServiceClient) SubmitResponse(ctx context.Context, req *connect.Request[pb.SubmitResponseRequest]) (*connect.Response[pb.SubmitResponseResponse], error) {
	return c.submitResponse.CallUnary(ctx, req)
}

// GetResponse calls weladee.form.v1.ResponseService.GetResponse.
func (c *responseServiceClient) GetResponse(ctx context.Context, req *connect.Request[pb.GetResponseRequest]) (*connect.Response[pb.GetResponseResponse], error) {
	return c.getResponse.CallUnary(ctx, req)
}

// ListResponses calls weladee.form.v1.ResponseService.ListResponses.
func (c *responseServiceClient) ListResponses(ctx context.Context, req *connect.Request[pb.ListResponsesRequest]) (*connect.Response[pb.ListResponsesResponse], error) {
	return c.listResponses.CallUnary(ctx, req)
}

// DeleteResponse calls weladee.form.v1.ResponseService.DeleteResponse.
func (c *responseServiceClient) DeleteResponse(ctx context.Context, req *connect.Request[pb.DeleteResponseRequest]) (*connect.Response[pb.DeleteResponseResponse], error) {
	return c.deleteResponse.CallUnary(ctx, req)
}

// ExportResponses calls weladee.form.v1.ResponseService.ExportResponses.
func (c *responseServiceClient) ExportResponses(ctx context.Context, req *connect.Request[pb.ExportResponsesRequest]) (*connect.Response[pb.ExportResponsesResponse], error) {
	return c.exportResponses.CallUnary(ctx, req)
}

// ResponseServiceHandler is an implementation of the weladee.form.v1.ResponseService service.
type ResponseServiceHandler interface {
	SubmitResponse(context.Context, *connect.Request[pb.SubmitResponseRequest]) (*connect.Response[pb.SubmitResponseResponse], error)
	GetResponse(context.Context, *connect.Request[pb.GetResponseRequest]) (*connect.Response[pb.GetResponseResponse], error)
	ListResponses(context.Context, *connect.Request[pb.ListResponsesRequest]) (*connect.Response[pb.ListResponsesResponse], error)
	DeleteResponse(context.Context, *connect.Request[pb.DeleteResponseRequest]) (*connect.Response[pb.DeleteResponseResponse], error)
	ExportResponses(context.Context, *connect.Request[pb.ExportResponsesRequest]) (*connect.Response[pb.ExportResponsesResponse], error)
}

// NewResponseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResponseServiceHandler(svc ResponseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	responseServiceMethods := pb.File_proto_response_proto.Services().ByName("ResponseService").Methods()
	responseServiceSubmitResponseHandler := connect.NewUnaryHandler(
		ResponseServiceSubmitResponseProcedure,
		svc.SubmitResponse,
		connect.WithSchema(responseServiceMethods.ByName("SubmitResponse")),
		connect.WithHandlerOptions(opts...),
	)
	responseServiceGetResponseHandler := connect.NewUnaryHandler(
		ResponseServiceGetResponseProcedure,
		svc.GetResponse,
		connect.WithSchema(responseServiceMethods.ByName("GetResponse")),
		connect.WithHandlerOptions(opts...),
	)
	responseServiceListResponsesHandler := connect.NewUnaryHandler(
		ResponseServiceListResponsesProcedure,
		svc.ListResponses,
		connect.WithSchema(responseServiceMethods.ByName("ListResponses")),
		connect.WithHandlerOptions(opts...),
	)
	responseServiceDeleteResponseHandler := connect.NewUnaryHandler(
		ResponseServiceDeleteResponseProcedure,
		svc.DeleteResponse,
		connect.WithSchema(responseServiceMethods.ByName("DeleteResponse")),
		connect.WithHandlerOptions(opts...),
	)
	responseServiceExportResponsesHandler := connect.NewUnaryHandler(
		ResponseServiceExportResponsesProcedure,
		svc.ExportResponses,
		connect.WithSchema(responseServiceMethods.ByName("ExportResponses")),
		connect.WithHandlerOptions(opts...),
	)
	return "/weladee.form.v1.ResponseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResponseServiceSubmitResponseProcedure:
			responseServiceSubmitResponseHandler.ServeHTTP(w, r)
		case ResponseServiceGetResponseProcedure:
			responseServiceGetResponseHandler.ServeHTTP(w, r)
		case ResponseServiceListResponsesProcedure:
			responseServiceListResponsesHandler.ServeHTTP(w, r)
		case ResponseServiceDeleteResponseProcedure:
			responseServiceDeleteResponseHandler.ServeHTTP(w, r)
		case ResponseServiceExportResponsesProcedure:
			responseServiceExportResponsesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResponseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResponseServiceHandler struct{}

func (UnimplementedResponseServiceHandler) SubmitResponse(context.Context, *connect.Request[pb.SubmitResponseRequest]) (*connect.Response[pb.SubmitResponseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.ResponseService.SubmitResponse is not implemented"))
}

func (UnimplementedResponseServiceHandler) GetResponse(context.Context, *connect.Request[pb.GetResponseRequest]) (*connect.Response[pb.GetResponseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.ResponseService.GetResponse is not implemented"))
}

func (UnimplementedResponseServiceHandler) ListResponses(context.Context, *connect.Request[pb.ListResponsesRequest]) (*connect.Response[pb.ListResponsesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.ResponseService.ListResponses is not implemented"))
}

func (UnimplementedResponseServiceHandler) DeleteResponse(context.Context, *connect.Request[pb.DeleteResponseRequest]) (*connect.Response[pb.DeleteResponseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.ResponseService.DeleteResponse is not implemented"))
}

func (UnimplementedResponseServiceHandler) ExportResponses(context.Context, *connect.Request[pb.ExportResponsesRequest]) (*connect.Response[pb.ExportResponsesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("weladee.form.v1.ResponseService.ExportResponses is not implemented"))
}
