// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/analytics.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetOverviewStats_FullMethodName          = "/weladee.form.v1.AnalyticsService/GetOverviewStats"
	AnalyticsService_GetResponseTrend_FullMethodName          = "/weladee.form.v1.AnalyticsService/GetResponseTrend"
	AnalyticsService_GetDeviceBreakdown_FullMethodName        = "/weladee.form.v1.AnalyticsService/GetDeviceBreakdown"
	AnalyticsService_GetCompletionFunnel_FullMethodName       = "/weladee.form.v1.AnalyticsService/GetCompletionFunnel"
	AnalyticsService_GetQuestionAnalytics_FullMethodName      = "/weladee.form.v1.AnalyticsService/GetQuestionAnalytics"
	AnalyticsService_GetQuestionDropOff_FullMethodName        = "/weladee.form.v1.AnalyticsService/GetQuestionDropOff"
	AnalyticsService_GetGeographicDistribution_FullMethodName = "/weladee.form.v1.AnalyticsService/GetGeographicDistribution"
	AnalyticsService_GetTimeDistribution_FullMethodName       = "/weladee.form.v1.AnalyticsService/GetTimeDistribution"
	AnalyticsService_TrackView_FullMethodName                 = "/weladee.form.v1.AnalyticsService/TrackView"
	AnalyticsService_TrackResponseStart_FullMethodName        = "/weladee.form.v1.AnalyticsService/TrackResponseStart"
	AnalyticsService_ExportAnalytics_FullMethodName           = "/weladee.form.v1.AnalyticsService/ExportAnalytics"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analytics Service
type AnalyticsServiceClient interface {
	GetOverviewStats(ctx context.Context, in *GetOverviewStatsRequest, opts ...grpc.CallOption) (*GetOverviewStatsResponse, error)
	GetResponseTrend(ctx context.Context, in *GetResponseTrendRequest, opts ...grpc.CallOption) (*GetResponseTrendResponse, error)
	GetDeviceBreakdown(ctx context.Context, in *GetDeviceBreakdownRequest, opts ...grpc.CallOption) (*GetDeviceBreakdownResponse, error)
	GetCompletionFunnel(ctx context.Context, in *GetCompletionFunnelRequest, opts ...grpc.CallOption) (*GetCompletionFunnelResponse, error)
	GetQuestionAnalytics(ctx context.Context, in *GetQuestionAnalyticsRequest, opts ...grpc.CallOption) (*GetQuestionAnalyticsResponse, error)
	GetQuestionDropOff(ctx context.Context, in *GetQuestionDropOffRequest, opts ...grpc.CallOption) (*GetQuestionDropOffResponse, error)
	GetGeographicDistribution(ctx context.Context, in *GetGeographicDistributionRequest, opts ...grpc.CallOption) (*GetGeographicDistributionResponse, error)
	GetTimeDistribution(ctx context.Context, in *GetTimeDistributionRequest, opts ...grpc.CallOption) (*GetTimeDistributionResponse, error)
	TrackView(ctx context.Context, in *TrackViewRequest, opts ...grpc.CallOption) (*TrackViewResponse, error)
	TrackResponseStart(ctx context.Context, in *TrackResponseStartRequest, opts ...grpc.CallOption) (*TrackResponseStartResponse, error)
	ExportAnalytics(ctx context.Context, in *ExportAnalyticsRequest, opts ...grpc.CallOption) (*ExportAnalyticsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetOverviewStats(ctx context.Context, in *GetOverviewStatsRequest, opts ...grpc.CallOption) (*GetOverviewStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverviewStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOverviewStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetResponseTrend(ctx context.Context, in *GetResponseTrendRequest, opts ...grpc.CallOption) (*GetResponseTrendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponseTrendResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetResponseTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDeviceBreakdown(ctx context.Context, in *GetDeviceBreakdownRequest, opts ...grpc.CallOption) (*GetDeviceBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceBreakdownResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDeviceBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCompletionFunnel(ctx context.Context, in *GetCompletionFunnelRequest, opts ...grpc.CallOption) (*GetCompletionFunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompletionFunnelResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCompletionFunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetQuestionAnalytics(ctx context.Context, in *GetQuestionAnalyticsRequest, opts ...grpc.CallOption) (*GetQuestionAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetQuestionAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetQuestionDropOff(ctx context.Context, in *GetQuestionDropOffRequest, opts ...grpc.CallOption) (*GetQuestionDropOffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuestionDropOffResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetQuestionDropOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetGeographicDistribution(ctx context.Context, in *GetGeographicDistributionRequest, opts ...grpc.CallOption) (*GetGeographicDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGeographicDistributionResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetGeographicDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTimeDistribution(ctx context.Context, in *GetTimeDistributionRequest, opts ...grpc.CallOption) (*GetTimeDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeDistributionResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTimeDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) TrackView(ctx context.Context, in *TrackViewRequest, opts ...grpc.CallOption) (*TrackViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackViewResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_TrackView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) TrackResponseStart(ctx context.Context, in *TrackResponseStartRequest, opts ...grpc.CallOption) (*TrackResponseStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackResponseStartResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_TrackResponseStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ExportAnalytics(ctx context.Context, in *ExportAnalyticsRequest, opts ...grpc.CallOption) (*ExportAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ExportAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// Analytics Service
type AnalyticsServiceServer interface {
	GetOverviewStats(context.Context, *GetOverviewStatsRequest) (*GetOverviewStatsResponse, error)
	GetResponseTrend(context.Context, *GetResponseTrendRequest) (*GetResponseTrendResponse, error)
	GetDeviceBreakdown(context.Context, *GetDeviceBreakdownRequest) (*GetDeviceBreakdownResponse, error)
	GetCompletionFunnel(context.Context, *GetCompletionFunnelRequest) (*GetCompletionFunnelResponse, error)
	GetQuestionAnalytics(context.Context, *GetQuestionAnalyticsRequest) (*GetQuestionAnalyticsResponse, error)
	GetQuestionDropOff(context.Context, *GetQuestionDropOffRequest) (*GetQuestionDropOffResponse, error)
	GetGeographicDistribution(context.Context, *GetGeographicDistributionRequest) (*GetGeographicDistributionResponse, error)
	GetTimeDistribution(context.Context, *GetTimeDistributionRequest) (*GetTimeDistributionResponse, error)
	TrackView(context.Context, *TrackViewRequest) (*TrackViewResponse, error)
	TrackResponseStart(context.Context, *TrackResponseStartRequest) (*TrackResponseStartResponse, error)
	ExportAnalytics(context.Context, *ExportAnalyticsRequest) (*ExportAnalyticsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetOverviewStats(context.Context, *GetOverviewStatsRequest) (*GetOverviewStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverviewStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetResponseTrend(context.Context, *GetResponseTrendRequest) (*GetResponseTrendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResponseTrend not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDeviceBreakdown(context.Context, *GetDeviceBreakdownRequest) (*GetDeviceBreakdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceBreakdown not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCompletionFunnel(context.Context, *GetCompletionFunnelRequest) (*GetCompletionFunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompletionFunnel not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetQuestionAnalytics(context.Context, *GetQuestionAnalyticsRequest) (*GetQuestionAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuestionAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetQuestionDropOff(context.Context, *GetQuestionDropOffRequest) (*GetQuestionDropOffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuestionDropOff not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetGeographicDistribution(context.Context, *GetGeographicDistributionRequest) (*GetGeographicDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGeographicDistribution not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTimeDistribution(context.Context, *GetTimeDistributionRequest) (*GetTimeDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeDistribution not implemented")
}
func (UnimplementedAnalyticsServiceServer) TrackView(context.Context, *TrackViewRequest) (*TrackViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackView not implemented")
}
func (UnimplementedAnalyticsServiceServer) TrackResponseStart(context.Context, *TrackResponseStartRequest) (*TrackResponseStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackResponseStart not implemented")
}
func (UnimplementedAnalyticsServiceServer) ExportAnalytics(context.Context, *ExportAnalyticsRequest) (*ExportAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetOverviewStats_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetOverviewStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOverviewStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOverviewStats_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetOverviewStats(ctx, req.(*GetOverviewStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetResponseTrend_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetResponseTrendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetResponseTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetResponseTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetResponseTrend(ctx, req.(*GetResponseTrendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDeviceBreakdown_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetDeviceBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDeviceBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDeviceBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetDeviceBreakdown(ctx, req.(*GetDeviceBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCompletionFunnel_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetCompletionFunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCompletionFunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCompletionFunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetCompletionFunnel(ctx, req.(*GetCompletionFunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetQuestionAnalytics_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetQuestionAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetQuestionAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetQuestionAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetQuestionAnalytics(ctx, req.(*GetQuestionAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetQuestionDropOff_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetQuestionDropOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetQuestionDropOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetQuestionDropOff_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetQuestionDropOff(ctx, req.(*GetQuestionDropOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetGeographicDistribution_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetGeographicDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetGeographicDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetGeographicDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetGeographicDistribution(ctx, req.(*GetGeographicDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTimeDistribution_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetTimeDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTimeDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTimeDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).GetTimeDistribution(ctx, req.(*GetTimeDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_TrackView_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TrackViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).TrackView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_TrackView_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).TrackView(ctx, req.(*TrackViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_TrackResponseStart_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TrackResponseStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).TrackResponseStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_TrackResponseStart_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).TrackResponseStart(ctx, req.(*TrackResponseStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ExportAnalytics_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ExportAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ExportAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ExportAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AnalyticsServiceServer).ExportAnalytics(ctx, req.(*ExportAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weladee.form.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverviewStats",
			Handler:    _AnalyticsService_GetOverviewStats_Handler,
		},
		{
			MethodName: "GetResponseTrend",
			Handler:    _AnalyticsService_GetResponseTrend_Handler,
		},
		{
			MethodName: "GetDeviceBreakdown",
			Handler:    _AnalyticsService_GetDeviceBreakdown_Handler,
		},
		{
			MethodName: "GetCompletionFunnel",
			Handler:    _AnalyticsService_GetCompletionFunnel_Handler,
		},
		{
			MethodName: "GetQuestionAnalytics",
			Handler:    _AnalyticsService_GetQuestionAnalytics_Handler,
		},
		{
			MethodName: "GetQuestionDropOff",
			Handler:    _AnalyticsService_GetQuestionDropOff_Handler,
		},
		{
			MethodName: "GetGeographicDistribution",
			Handler:    _AnalyticsService_GetGeographicDistribution_Handler,
		},
		{
			MethodName: "GetTimeDistribution",
			Handler:    _AnalyticsService_GetTimeDistribution_Handler,
		},
		{
			MethodName: "TrackView",
			Handler:    _AnalyticsService_TrackView_Handler,
		},
		{
			MethodName: "TrackResponseStart",
			Handler:    _AnalyticsService_TrackResponseStart_Handler,
		},
		{
			MethodName: "ExportAnalytics",
			Handler:    _AnalyticsService_ExportAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics.proto",
}
