// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/form.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type FormStatus int32

const (
	FormStatus_FORM_STATUS_UNSPECIFIED FormStatus = 0
	FormStatus_FORM_STATUS_DRAFT       FormStatus = 1
	FormStatus_FORM_STATUS_PUBLISHED   FormStatus = 2
	FormStatus_FORM_STATUS_CLOSED      FormStatus = 3
)

// Enum value maps for FormStatus.
var (
	FormStatus_name = map[int32]string{
		0: "FORM_STATUS_UNSPECIFIED",
		1: "FORM_STATUS_DRAFT",
		2: "FORM_STATUS_PUBLISHED",
		3: "FORM_STATUS_CLOSED",
	}
	FormStatus_value = map[string]int32{
		"FORM_STATUS_UNSPECIFIED": 0,
		"FORM_STATUS_DRAFT":       1,
		"FORM_STATUS_PUBLISHED":   2,
		"FORM_STATUS_CLOSED":      3,
	}
)

func (x FormStatus) Enum() *FormStatus {
	p := new(FormStatus)
	*p = x
	return p
}

func (x FormStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[0].Descriptor()
}

func (FormStatus) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[0]
}

func (x FormStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormStatus.Descriptor instead.
func (FormStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{0}
}

type FormTheme int32

const (
	FormTheme_FORM_THEME_UNSPECIFIED FormTheme = 0
	FormTheme_FORM_THEME_MINIMAL     FormTheme = 1
	FormTheme_FORM_THEME_MIDNIGHT    FormTheme = 2
	FormTheme_FORM_THEME_OCEAN       FormTheme = 3
	FormTheme_FORM_THEME_SUNSET      FormTheme = 4
	FormTheme_FORM_THEME_FOREST      FormTheme = 5
	FormTheme_FORM_THEME_LAVENDER    FormTheme = 6
	FormTheme_FORM_THEME_WELADEE     FormTheme = 7
	FormTheme_FORM_THEME_AURORA      FormTheme = 8
	FormTheme_FORM_THEME_CYBERPUNK   FormTheme = 9
	FormTheme_FORM_THEME_DESERT      FormTheme = 10
)

// Enum value maps for FormTheme.
var (
	FormTheme_name = map[int32]string{
		0:  "FORM_THEME_UNSPECIFIED",
		1:  "FORM_THEME_MINIMAL",
		2:  "FORM_THEME_MIDNIGHT",
		3:  "FORM_THEME_OCEAN",
		4:  "FORM_THEME_SUNSET",
		5:  "FORM_THEME_FOREST",
		6:  "FORM_THEME_LAVENDER",
		7:  "FORM_THEME_WELADEE",
		8:  "FORM_THEME_AURORA",
		9:  "FORM_THEME_CYBERPUNK",
		10: "FORM_THEME_DESERT",
	}
	FormTheme_value = map[string]int32{
		"FORM_THEME_UNSPECIFIED": 0,
		"FORM_THEME_MINIMAL":     1,
		"FORM_THEME_MIDNIGHT":    2,
		"FORM_THEME_OCEAN":       3,
		"FORM_THEME_SUNSET":      4,
		"FORM_THEME_FOREST":      5,
		"FORM_THEME_LAVENDER":    6,
		"FORM_THEME_WELADEE":     7,
		"FORM_THEME_AURORA":      8,
		"FORM_THEME_CYBERPUNK":   9,
		"FORM_THEME_DESERT":      10,
	}
)

func (x FormTheme) Enum() *FormTheme {
	p := new(FormTheme)
	*p = x
	return p
}

func (x FormTheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormTheme) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[1].Descriptor()
}

func (FormTheme) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[1]
}

func (x FormTheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormTheme.Descriptor instead.
func (FormTheme) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{1}
}

type QuestionType int32

const (
	QuestionType_QUESTION_TYPE_UNSPECIFIED   QuestionType = 0
	QuestionType_QUESTION_TYPE_SHORT_TEXT    QuestionType = 1
	QuestionType_QUESTION_TYPE_LONG_TEXT     QuestionType = 2
	QuestionType_QUESTION_TYPE_DROPDOWN      QuestionType = 3
	QuestionType_QUESTION_TYPE_CHECKBOXES    QuestionType = 4
	QuestionType_QUESTION_TYPE_EMAIL         QuestionType = 5
	QuestionType_QUESTION_TYPE_PHONE         QuestionType = 6
	QuestionType_QUESTION_TYPE_NUMBER        QuestionType = 7
	QuestionType_QUESTION_TYPE_DATE          QuestionType = 8
	QuestionType_QUESTION_TYPE_RATING        QuestionType = 9
	QuestionType_QUESTION_TYPE_OPINION_SCALE QuestionType = 10
	QuestionType_QUESTION_TYPE_YES_NO        QuestionType = 11
	// Only for enterprise plans
	QuestionType_QUESTION_TYPE_FILE_UPLOAD QuestionType = 12
	QuestionType_QUESTION_TYPE_URL         QuestionType = 13
	// Not available to SME plans
	QuestionType_QUESTION_TYPE_MATRIX QuestionType = 14
	// Only for enterprise plans
	QuestionType_QUESTION_TYPE_RANKING QuestionType = 15
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0:  "QUESTION_TYPE_UNSPECIFIED",
		1:  "QUESTION_TYPE_SHORT_TEXT",
		2:  "QUESTION_TYPE_LONG_TEXT",
		3:  "QUESTION_TYPE_DROPDOWN",
		4:  "QUESTION_TYPE_CHECKBOXES",
		5:  "QUESTION_TYPE_EMAIL",
		6:  "QUESTION_TYPE_PHONE",
		7:  "QUESTION_TYPE_NUMBER",
		8:  "QUESTION_TYPE_DATE",
		9:  "QUESTION_TYPE_RATING",
		10: "QUESTION_TYPE_OPINION_SCALE",
		11: "QUESTION_TYPE_YES_NO",
		12: "QUESTION_TYPE_FILE_UPLOAD",
		13: "QUESTION_TYPE_URL",
		14: "QUESTION_TYPE_MATRIX",
		15: "QUESTION_TYPE_RANKING",
	}
	QuestionType_value = map[string]int32{
		"QUESTION_TYPE_UNSPECIFIED":   0,
		"QUESTION_TYPE_SHORT_TEXT":    1,
		"QUESTION_TYPE_LONG_TEXT":     2,
		"QUESTION_TYPE_DROPDOWN":      3,
		"QUESTION_TYPE_CHECKBOXES":    4,
		"QUESTION_TYPE_EMAIL":         5,
		"QUESTION_TYPE_PHONE":         6,
		"QUESTION_TYPE_NUMBER":        7,
		"QUESTION_TYPE_DATE":          8,
		"QUESTION_TYPE_RATING":        9,
		"QUESTION_TYPE_OPINION_SCALE": 10,
		"QUESTION_TYPE_YES_NO":        11,
		"QUESTION_TYPE_FILE_UPLOAD":   12,
		"QUESTION_TYPE_URL":           13,
		"QUESTION_TYPE_MATRIX":        14,
		"QUESTION_TYPE_RANKING":       15,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[2].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[2]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{2}
}

type ProgressBarStyle int32

const (
	ProgressBarStyle_PROGRESS_BAR_STYLE_UNSPECIFIED ProgressBarStyle = 0
	ProgressBarStyle_PROGRESS_BAR_STYLE_NONE        ProgressBarStyle = 1
	ProgressBarStyle_PROGRESS_BAR_STYLE_LINEAR      ProgressBarStyle = 2
	ProgressBarStyle_PROGRESS_BAR_STYLE_STEPS       ProgressBarStyle = 3
	ProgressBarStyle_PROGRESS_BAR_STYLE_CIRCULAR    ProgressBarStyle = 4
)

// Enum value maps for ProgressBarStyle.
var (
	ProgressBarStyle_name = map[int32]string{
		0: "PROGRESS_BAR_STYLE_UNSPECIFIED",
		1: "PROGRESS_BAR_STYLE_NONE",
		2: "PROGRESS_BAR_STYLE_LINEAR",
		3: "PROGRESS_BAR_STYLE_STEPS",
		4: "PROGRESS_BAR_STYLE_CIRCULAR",
	}
	ProgressBarStyle_value = map[string]int32{
		"PROGRESS_BAR_STYLE_UNSPECIFIED": 0,
		"PROGRESS_BAR_STYLE_NONE":        1,
		"PROGRESS_BAR_STYLE_LINEAR":      2,
		"PROGRESS_BAR_STYLE_STEPS":       3,
		"PROGRESS_BAR_STYLE_CIRCULAR":    4,
	}
)

func (x ProgressBarStyle) Enum() *ProgressBarStyle {
	p := new(ProgressBarStyle)
	*p = x
	return p
}

func (x ProgressBarStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressBarStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[3].Descriptor()
}

func (ProgressBarStyle) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[3]
}

func (x ProgressBarStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressBarStyle.Descriptor instead.
func (ProgressBarStyle) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{3}
}

// Sort options for ListForms
type FormSortBy int32

const (
	FormSortBy_FORM_SORT_BY_UNSPECIFIED    FormSortBy = 0
	FormSortBy_FORM_SORT_BY_UPDATED_AT     FormSortBy = 1
	FormSortBy_FORM_SORT_BY_CREATED_AT     FormSortBy = 2
	FormSortBy_FORM_SORT_BY_TITLE          FormSortBy = 3
	FormSortBy_FORM_SORT_BY_RESPONSE_COUNT FormSortBy = 4
)

// Enum value maps for FormSortBy.
var (
	FormSortBy_name = map[int32]string{
		0: "FORM_SORT_BY_UNSPECIFIED",
		1: "FORM_SORT_BY_UPDATED_AT",
		2: "FORM_SORT_BY_CREATED_AT",
		3: "FORM_SORT_BY_TITLE",
		4: "FORM_SORT_BY_RESPONSE_COUNT",
	}
	FormSortBy_value = map[string]int32{
		"FORM_SORT_BY_UNSPECIFIED":    0,
		"FORM_SORT_BY_UPDATED_AT":     1,
		"FORM_SORT_BY_CREATED_AT":     2,
		"FORM_SORT_BY_TITLE":          3,
		"FORM_SORT_BY_RESPONSE_COUNT": 4,
	}
)

func (x FormSortBy) Enum() *FormSortBy {
	p := new(FormSortBy)
	*p = x
	return p
}

func (x FormSortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormSortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[4].Descriptor()
}

func (FormSortBy) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[4]
}

func (x FormSortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormSortBy.Descriptor instead.
func (FormSortBy) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{4}
}

type FormSortOrder int32

const (
	FormSortOrder_FORM_SORT_ORDER_UNSPECIFIED FormSortOrder = 0
	FormSortOrder_FORM_SORT_ORDER_ASC         FormSortOrder = 1
	FormSortOrder_FORM_SORT_ORDER_DESC        FormSortOrder = 2
)

// Enum value maps for FormSortOrder.
var (
	FormSortOrder_name = map[int32]string{
		0: "FORM_SORT_ORDER_UNSPECIFIED",
		1: "FORM_SORT_ORDER_ASC",
		2: "FORM_SORT_ORDER_DESC",
	}
	FormSortOrder_value = map[string]int32{
		"FORM_SORT_ORDER_UNSPECIFIED": 0,
		"FORM_SORT_ORDER_ASC":         1,
		"FORM_SORT_ORDER_DESC":        2,
	}
)

func (x FormSortOrder) Enum() *FormSortOrder {
	p := new(FormSortOrder)
	*p = x
	return p
}

func (x FormSortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormSortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[5].Descriptor()
}

func (FormSortOrder) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[5]
}

func (x FormSortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormSortOrder.Descriptor instead.
func (FormSortOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{5}
}

type FormStatusFilter int32

const (
	FormStatusFilter_FORM_STATUS_FILTER_UNSPECIFIED FormStatusFilter = 0
	FormStatusFilter_FORM_STATUS_FILTER_DRAFT       FormStatusFilter = 1
	FormStatusFilter_FORM_STATUS_FILTER_PUBLISHED   FormStatusFilter = 2
	FormStatusFilter_FORM_STATUS_FILTER_CLOSED      FormStatusFilter = 3
)

// Enum value maps for FormStatusFilter.
var (
	FormStatusFilter_name = map[int32]string{
		0: "FORM_STATUS_FILTER_UNSPECIFIED",
		1: "FORM_STATUS_FILTER_DRAFT",
		2: "FORM_STATUS_FILTER_PUBLISHED",
		3: "FORM_STATUS_FILTER_CLOSED",
	}
	FormStatusFilter_value = map[string]int32{
		"FORM_STATUS_FILTER_UNSPECIFIED": 0,
		"FORM_STATUS_FILTER_DRAFT":       1,
		"FORM_STATUS_FILTER_PUBLISHED":   2,
		"FORM_STATUS_FILTER_CLOSED":      3,
	}
)

func (x FormStatusFilter) Enum() *FormStatusFilter {
	p := new(FormStatusFilter)
	*p = x
	return p
}

func (x FormStatusFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormStatusFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_form_proto_enumTypes[6].Descriptor()
}

func (FormStatusFilter) Type() protoreflect.EnumType {
	return &file_proto_form_proto_enumTypes[6]
}

func (x FormStatusFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormStatusFilter.Descriptor instead.
func (FormStatusFilter) EnumDescriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{6}
}

// Messages
type Question struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FormId          string                 `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Type            QuestionType           `protobuf:"varint,3,opt,name=type,proto3,enum=weladee.form.v1.QuestionType" json:"type,omitempty"`
	Label           string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Placeholder     string                 `protobuf:"bytes,6,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Required        bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	OrderIndex      int32                  `protobuf:"varint,8,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	Options         *structpb.Struct       `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	ValidationRules *structpb.Struct       `protobuf:"bytes,10,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	Settings        *structpb.Struct       `protobuf:"bytes,11,opt,name=settings,proto3" json:"settings,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_form_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Question) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *Question) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Question) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Question) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *Question) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Question) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Question) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetValidationRules() *structpb.Struct {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

func (x *Question) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Question) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Question) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Form struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                   string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                    string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description              string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Theme                    FormTheme              `protobuf:"varint,5,opt,name=theme,proto3,enum=weladee.form.v1.FormTheme" json:"theme,omitempty"`
	IsPublished              bool                   `protobuf:"varint,6,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	IsAcceptingResponses     bool                   `protobuf:"varint,7,opt,name=is_accepting_responses,json=isAcceptingResponses,proto3" json:"is_accepting_responses,omitempty"`
	RequireLogin             bool                   `protobuf:"varint,8,opt,name=require_login,json=requireLogin,proto3" json:"require_login,omitempty"`
	AllowMultipleSubmissions bool                   `protobuf:"varint,9,opt,name=allow_multiple_submissions,json=allowMultipleSubmissions,proto3" json:"allow_multiple_submissions,omitempty"`
	ProgressBarStyle         ProgressBarStyle       `protobuf:"varint,10,opt,name=progress_bar_style,json=progressBarStyle,proto3,enum=weladee.form.v1.ProgressBarStyle" json:"progress_bar_style,omitempty"`
	CustomThankYouMessage    string                 `protobuf:"bytes,11,opt,name=custom_thank_you_message,json=customThankYouMessage,proto3" json:"custom_thank_you_message,omitempty"`
	RedirectUrl              string                 `protobuf:"bytes,12,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	ForceCaptcha             bool                   `protobuf:"varint,13,opt,name=force_captcha,json=forceCaptcha,proto3" json:"force_captcha,omitempty"`
	Settings                 *structpb.Struct       `protobuf:"bytes,14,opt,name=settings,proto3" json:"settings,omitempty"`
	Questions                []*Question            `protobuf:"bytes,15,rep,name=questions,proto3" json:"questions,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Form) Reset() {
	*x = Form{}
	mi := &file_proto_form_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{1}
}

func (x *Form) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Form) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Form) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Form) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Form) GetTheme() FormTheme {
	if x != nil {
		return x.Theme
	}
	return FormTheme_FORM_THEME_UNSPECIFIED
}

func (x *Form) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Form) GetIsAcceptingResponses() bool {
	if x != nil {
		return x.IsAcceptingResponses
	}
	return false
}

func (x *Form) GetRequireLogin() bool {
	if x != nil {
		return x.RequireLogin
	}
	return false
}

func (x *Form) GetAllowMultipleSubmissions() bool {
	if x != nil {
		return x.AllowMultipleSubmissions
	}
	return false
}

func (x *Form) GetProgressBarStyle() ProgressBarStyle {
	if x != nil {
		return x.ProgressBarStyle
	}
	return ProgressBarStyle_PROGRESS_BAR_STYLE_UNSPECIFIED
}

func (x *Form) GetCustomThankYouMessage() string {
	if x != nil {
		return x.CustomThankYouMessage
	}
	return ""
}

func (x *Form) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *Form) GetForceCaptcha() bool {
	if x != nil {
		return x.ForceCaptcha
	}
	return false
}

func (x *Form) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Form) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Form) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Form) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FormStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalResponses     int64                  `protobuf:"varint,1,opt,name=total_responses,json=totalResponses,proto3" json:"total_responses,omitempty"`
	CompletedResponses int64                  `protobuf:"varint,2,opt,name=completed_responses,json=completedResponses,proto3" json:"completed_responses,omitempty"`
	PartialResponses   int64                  `protobuf:"varint,3,opt,name=partial_responses,json=partialResponses,proto3" json:"partial_responses,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FormStats) Reset() {
	*x = FormStats{}
	mi := &file_proto_form_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormStats) ProtoMessage() {}

func (x *FormStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormStats.ProtoReflect.Descriptor instead.
func (*FormStats) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{2}
}

func (x *FormStats) GetTotalResponses() int64 {
	if x != nil {
		return x.TotalResponses
	}
	return 0
}

func (x *FormStats) GetCompletedResponses() int64 {
	if x != nil {
		return x.CompletedResponses
	}
	return 0
}

func (x *FormStats) GetPartialResponses() int64 {
	if x != nil {
		return x.PartialResponses
	}
	return 0
}

// RPC Requests/Responses
type CreateFormRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Theme            FormTheme              `protobuf:"varint,3,opt,name=theme,proto3,enum=weladee.form.v1.FormTheme" json:"theme,omitempty"`
	ProgressBarStyle ProgressBarStyle       `protobuf:"varint,4,opt,name=progress_bar_style,json=progressBarStyle,proto3,enum=weladee.form.v1.ProgressBarStyle" json:"progress_bar_style,omitempty"`
	Questions        []*Question            `protobuf:"bytes,5,rep,name=questions,proto3" json:"questions,omitempty"`
	Settings         *structpb.Struct       `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateFormRequest) Reset() {
	*x = CreateFormRequest{}
	mi := &file_proto_form_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormRequest) ProtoMessage() {}

func (x *CreateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormRequest.ProtoReflect.Descriptor instead.
func (*CreateFormRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFormRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateFormRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFormRequest) GetTheme() FormTheme {
	if x != nil {
		return x.Theme
	}
	return FormTheme_FORM_THEME_UNSPECIFIED
}

func (x *CreateFormRequest) GetProgressBarStyle() ProgressBarStyle {
	if x != nil {
		return x.ProgressBarStyle
	}
	return ProgressBarStyle_PROGRESS_BAR_STYLE_UNSPECIFIED
}

func (x *CreateFormRequest) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *CreateFormRequest) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CreateFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFormResponse) Reset() {
	*x = CreateFormResponse{}
	mi := &file_proto_form_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFormResponse) ProtoMessage() {}

func (x *CreateFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFormResponse.ProtoReflect.Descriptor instead.
func (*CreateFormResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type GetFormRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeQuestions bool                   `protobuf:"varint,2,opt,name=include_questions,json=includeQuestions,proto3" json:"include_questions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFormRequest) Reset() {
	*x = GetFormRequest{}
	mi := &file_proto_form_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormRequest) ProtoMessage() {}

func (x *GetFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormRequest.ProtoReflect.Descriptor instead.
func (*GetFormRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{5}
}

func (x *GetFormRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetFormRequest) GetIncludeQuestions() bool {
	if x != nil {
		return x.IncludeQuestions
	}
	return false
}

type GetFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormResponse) Reset() {
	*x = GetFormResponse{}
	mi := &file_proto_form_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormResponse) ProtoMessage() {}

func (x *GetFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormResponse.ProtoReflect.Descriptor instead.
func (*GetFormResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{6}
}

func (x *GetFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type GetFormBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormBySlugRequest) Reset() {
	*x = GetFormBySlugRequest{}
	mi := &file_proto_form_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormBySlugRequest) ProtoMessage() {}

func (x *GetFormBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetFormBySlugRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{7}
}

func (x *GetFormBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetFormBySlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormBySlugResponse) Reset() {
	*x = GetFormBySlugResponse{}
	mi := &file_proto_form_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormBySlugResponse) ProtoMessage() {}

func (x *GetFormBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetFormBySlugResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{8}
}

func (x *GetFormBySlugResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type UpdateFormRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                    *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description              *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Theme                    *FormTheme             `protobuf:"varint,4,opt,name=theme,proto3,enum=weladee.form.v1.FormTheme,oneof" json:"theme,omitempty"`
	IsPublished              *bool                  `protobuf:"varint,5,opt,name=is_published,json=isPublished,proto3,oneof" json:"is_published,omitempty"`
	IsAcceptingResponses     *bool                  `protobuf:"varint,6,opt,name=is_accepting_responses,json=isAcceptingResponses,proto3,oneof" json:"is_accepting_responses,omitempty"`
	RequireLogin             *bool                  `protobuf:"varint,7,opt,name=require_login,json=requireLogin,proto3,oneof" json:"require_login,omitempty"`
	AllowMultipleSubmissions *bool                  `protobuf:"varint,8,opt,name=allow_multiple_submissions,json=allowMultipleSubmissions,proto3,oneof" json:"allow_multiple_submissions,omitempty"`
	ProgressBarStyle         *ProgressBarStyle      `protobuf:"varint,9,opt,name=progress_bar_style,json=progressBarStyle,proto3,enum=weladee.form.v1.ProgressBarStyle,oneof" json:"progress_bar_style,omitempty"`
	CustomThankYouMessage    *string                `protobuf:"bytes,10,opt,name=custom_thank_you_message,json=customThankYouMessage,proto3,oneof" json:"custom_thank_you_message,omitempty"`
	RedirectUrl              *string                `protobuf:"bytes,11,opt,name=redirect_url,json=redirectUrl,proto3,oneof" json:"redirect_url,omitempty"`
	ForceCaptcha             *bool                  `protobuf:"varint,12,opt,name=force_captcha,json=forceCaptcha,proto3,oneof" json:"force_captcha,omitempty"`
	Settings                 *structpb.Struct       `protobuf:"bytes,13,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateFormRequest) Reset() {
	*x = UpdateFormRequest{}
	mi := &file_proto_form_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormRequest) ProtoMessage() {}

func (x *UpdateFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormRequest.ProtoReflect.Descriptor instead.
func (*UpdateFormRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateFormRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFormRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateFormRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateFormRequest) GetTheme() FormTheme {
	if x != nil && x.Theme != nil {
		return *x.Theme
	}
	return FormTheme_FORM_THEME_UNSPECIFIED
}

func (x *UpdateFormRequest) GetIsPublished() bool {
	if x != nil && x.IsPublished != nil {
		return *x.IsPublished
	}
	return false
}

func (x *UpdateFormRequest) GetIsAcceptingResponses() bool {
	if x != nil && x.IsAcceptingResponses != nil {
		return *x.IsAcceptingResponses
	}
	return false
}

func (x *UpdateFormRequest) GetRequireLogin() bool {
	if x != nil && x.RequireLogin != nil {
		return *x.RequireLogin
	}
	return false
}

func (x *UpdateFormRequest) GetAllowMultipleSubmissions() bool {
	if x != nil && x.AllowMultipleSubmissions != nil {
		return *x.AllowMultipleSubmissions
	}
	return false
}

func (x *UpdateFormRequest) GetProgressBarStyle() ProgressBarStyle {
	if x != nil && x.ProgressBarStyle != nil {
		return *x.ProgressBarStyle
	}
	return ProgressBarStyle_PROGRESS_BAR_STYLE_UNSPECIFIED
}

func (x *UpdateFormRequest) GetCustomThankYouMessage() string {
	if x != nil && x.CustomThankYouMessage != nil {
		return *x.CustomThankYouMessage
	}
	return ""
}

func (x *UpdateFormRequest) GetRedirectUrl() string {
	if x != nil && x.RedirectUrl != nil {
		return *x.RedirectUrl
	}
	return ""
}

func (x *UpdateFormRequest) GetForceCaptcha() bool {
	if x != nil && x.ForceCaptcha != nil {
		return *x.ForceCaptcha
	}
	return false
}

func (x *UpdateFormRequest) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFormResponse) Reset() {
	*x = UpdateFormResponse{}
	mi := &file_proto_form_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFormResponse) ProtoMessage() {}

func (x *UpdateFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFormResponse.ProtoReflect.Descriptor instead.
func (*UpdateFormResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type DeleteFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormRequest) Reset() {
	*x = DeleteFormRequest{}
	mi := &file_proto_form_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormRequest) ProtoMessage() {}

func (x *DeleteFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormRequest.ProtoReflect.Descriptor instead.
func (*DeleteFormRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFormRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFormResponse) Reset() {
	*x = DeleteFormResponse{}
	mi := &file_proto_form_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFormResponse) ProtoMessage() {}

func (x *DeleteFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFormResponse.ProtoReflect.Descriptor instead.
func (*DeleteFormResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFormResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListFormsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *PaginationRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SearchQuery   *string                `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3,oneof" json:"search_query,omitempty"`
	PublishedOnly *bool                  `protobuf:"varint,3,opt,name=published_only,json=publishedOnly,proto3,oneof" json:"published_only,omitempty"`
	SortBy        *FormSortBy            `protobuf:"varint,4,opt,name=sort_by,json=sortBy,proto3,enum=weladee.form.v1.FormSortBy,oneof" json:"sort_by,omitempty"`
	SortOrder     *FormSortOrder         `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=weladee.form.v1.FormSortOrder,oneof" json:"sort_order,omitempty"`
	StatusFilter  *FormStatusFilter      `protobuf:"varint,6,opt,name=status_filter,json=statusFilter,proto3,enum=weladee.form.v1.FormStatusFilter,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormsRequest) Reset() {
	*x = ListFormsRequest{}
	mi := &file_proto_form_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormsRequest) ProtoMessage() {}

func (x *ListFormsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormsRequest.ProtoReflect.Descriptor instead.
func (*ListFormsRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{13}
}

func (x *ListFormsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListFormsRequest) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

func (x *ListFormsRequest) GetPublishedOnly() bool {
	if x != nil && x.PublishedOnly != nil {
		return *x.PublishedOnly
	}
	return false
}

func (x *ListFormsRequest) GetSortBy() FormSortBy {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return FormSortBy_FORM_SORT_BY_UNSPECIFIED
}

func (x *ListFormsRequest) GetSortOrder() FormSortOrder {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return FormSortOrder_FORM_SORT_ORDER_UNSPECIFIED
}

func (x *ListFormsRequest) GetStatusFilter() FormStatusFilter {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return FormStatusFilter_FORM_STATUS_FILTER_UNSPECIFIED
}

type ListFormsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forms         []*Form                `protobuf:"bytes,1,rep,name=forms,proto3" json:"forms,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFormsResponse) Reset() {
	*x = ListFormsResponse{}
	mi := &file_proto_form_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFormsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFormsResponse) ProtoMessage() {}

func (x *ListFormsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFormsResponse.ProtoReflect.Descriptor instead.
func (*ListFormsResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{14}
}

func (x *ListFormsResponse) GetForms() []*Form {
	if x != nil {
		return x.Forms
	}
	return nil
}

func (x *ListFormsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PublishFormRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishFormRequest) Reset() {
	*x = PublishFormRequest{}
	mi := &file_proto_form_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishFormRequest) ProtoMessage() {}

func (x *PublishFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishFormRequest.ProtoReflect.Descriptor instead.
func (*PublishFormRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{15}
}

func (x *PublishFormRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PublishFormResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Form          *Form                  `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishFormResponse) Reset() {
	*x = PublishFormResponse{}
	mi := &file_proto_form_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishFormResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishFormResponse) ProtoMessage() {}

func (x *PublishFormResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishFormResponse.ProtoReflect.Descriptor instead.
func (*PublishFormResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{16}
}

func (x *PublishFormResponse) GetForm() *Form {
	if x != nil {
		return x.Form
	}
	return nil
}

type GetFormStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormStatsRequest) Reset() {
	*x = GetFormStatsRequest{}
	mi := &file_proto_form_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormStatsRequest) ProtoMessage() {}

func (x *GetFormStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormStatsRequest.ProtoReflect.Descriptor instead.
func (*GetFormStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{17}
}

func (x *GetFormStatsRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

type GetFormStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *FormStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormStatsResponse) Reset() {
	*x = GetFormStatsResponse{}
	mi := &file_proto_form_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormStatsResponse) ProtoMessage() {}

func (x *GetFormStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormStatsResponse.ProtoReflect.Descriptor instead.
func (*GetFormStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{18}
}

func (x *GetFormStatsResponse) GetStats() *FormStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Question RPCs
type CreateQuestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FormId          string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Type            QuestionType           `protobuf:"varint,2,opt,name=type,proto3,enum=weladee.form.v1.QuestionType" json:"type,omitempty"`
	Label           string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Placeholder     string                 `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Required        bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	OrderIndex      int32                  `protobuf:"varint,7,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	Options         *structpb.Struct       `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	ValidationRules *structpb.Struct       `protobuf:"bytes,9,opt,name=validation_rules,json=validationRules,proto3" json:"validation_rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_proto_form_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{19}
}

func (x *CreateQuestionRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *CreateQuestionRequest) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *CreateQuestionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateQuestionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateQuestionRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *CreateQuestionRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CreateQuestionRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *CreateQuestionRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateQuestionRequest) GetValidationRules() *structpb.Struct {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_proto_form_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{20}
}

func (x *CreateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type UpdateQuestionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            *QuestionType          `protobuf:"varint,2,opt,name=type,proto3,enum=weladee.form.v1.QuestionType,oneof" json:"type,omitempty"`
	Label           *string                `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Description     *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Placeholder     *string                `protobuf:"bytes,5,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	Required        *bool                  `protobuf:"varint,6,opt,name=required,proto3,oneof" json:"required,omitempty"`
	OrderIndex      *int32                 `protobuf:"varint,7,opt,name=order_index,json=orderIndex,proto3,oneof" json:"order_index,omitempty"`
	Options         *structpb.Struct       `protobuf:"bytes,8,opt,name=options,proto3,oneof" json:"options,omitempty"`
	ValidationRules *structpb.Struct       `protobuf:"bytes,9,opt,name=validation_rules,json=validationRules,proto3,oneof" json:"validation_rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_proto_form_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateQuestionRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *UpdateQuestionRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateQuestionRequest) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

func (x *UpdateQuestionRequest) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *UpdateQuestionRequest) GetOrderIndex() int32 {
	if x != nil && x.OrderIndex != nil {
		return *x.OrderIndex
	}
	return 0
}

func (x *UpdateQuestionRequest) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateQuestionRequest) GetValidationRules() *structpb.Struct {
	if x != nil {
		return x.ValidationRules
	}
	return nil
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_proto_form_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_proto_form_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteQuestionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_proto_form_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReorderQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	QuestionIds   []string               `protobuf:"bytes,2,rep,name=question_ids,json=questionIds,proto3" json:"question_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderQuestionsRequest) Reset() {
	*x = ReorderQuestionsRequest{}
	mi := &file_proto_form_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderQuestionsRequest) ProtoMessage() {}

func (x *ReorderQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ReorderQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{25}
}

func (x *ReorderQuestionsRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ReorderQuestionsRequest) GetQuestionIds() []string {
	if x != nil {
		return x.QuestionIds
	}
	return nil
}

type ReorderQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderQuestionsResponse) Reset() {
	*x = ReorderQuestionsResponse{}
	mi := &file_proto_form_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderQuestionsResponse) ProtoMessage() {}

func (x *ReorderQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_form_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ReorderQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_form_proto_rawDescGZIP(), []int{26}
}

func (x *ReorderQuestionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_form_proto protoreflect.FileDescriptor

const file_proto_form_proto_rawDesc = "" +
	"\n" +
	"\x10proto/form.proto\x12\x0fweladee.form.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x12proto/common.proto\"\x9f\x04\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\tR\x06formId\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.weladee.form.v1.QuestionTypeR\x04type\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12 \n" +
	"\vplaceholder\x18\x06 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x12\x1f\n" +
	"\vorder_index\x18\b \x01(\x05R\n" +
	"orderIndex\x121\n" +
	"\aoptions\x18\t \x01(\v2\x17.google.protobuf.StructR\aoptions\x12B\n" +
	"\x10validation_rules\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x0fvalidationRules\x123\n" +
	"\bsettings\x18\v \x01(\v2\x17.google.protobuf.StructR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x06\n" +
	"\x04Form\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\x05theme\x18\x05 \x01(\x0e2\x1a.weladee.form.v1.FormThemeR\x05theme\x12!\n" +
	"\fis_published\x18\x06 \x01(\bR\visPublished\x124\n" +
	"\x16is_accepting_responses\x18\a \x01(\bR\x14isAcceptingResponses\x12#\n" +
	"\rrequire_login\x18\b \x01(\bR\frequireLogin\x12<\n" +
	"\x1aallow_multiple_submissions\x18\t \x01(\bR\x18allowMultipleSubmissions\x12O\n" +
	"\x12progress_bar_style\x18\n" +
	" \x01(\x0e2!.weladee.form.v1.ProgressBarStyleR\x10progressBarStyle\x127\n" +
	"\x18custom_thank_you_message\x18\v \x01(\tR\x15customThankYouMessage\x12!\n" +
	"\fredirect_url\x18\f \x01(\tR\vredirectUrl\x12#\n" +
	"\rforce_captcha\x18\r \x01(\bR\fforceCaptcha\x123\n" +
	"\bsettings\x18\x0e \x01(\v2\x17.google.protobuf.StructR\bsettings\x127\n" +
	"\tquestions\x18\x0f \x03(\v2\x19.weladee.form.v1.QuestionR\tquestions\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x01\n" +
	"\tFormStats\x12'\n" +
	"\x0ftotal_responses\x18\x01 \x01(\x03R\x0etotalResponses\x12/\n" +
	"\x13completed_responses\x18\x02 \x01(\x03R\x12completedResponses\x12+\n" +
	"\x11partial_responses\x18\x03 \x01(\x03R\x10partialResponses\"\xbc\x02\n" +
	"\x11CreateFormRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x05theme\x18\x03 \x01(\x0e2\x1a.weladee.form.v1.FormThemeR\x05theme\x12O\n" +
	"\x12progress_bar_style\x18\x04 \x01(\x0e2!.weladee.form.v1.ProgressBarStyleR\x10progressBarStyle\x127\n" +
	"\tquestions\x18\x05 \x03(\v2\x19.weladee.form.v1.QuestionR\tquestions\x123\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bsettings\"?\n" +
	"\x12CreateFormResponse\x12)\n" +
	"\x04form\x18\x01 \x01(\v2\x15.weladee.form.v1.FormR\x04form\"M\n" +
	"\x0eGetFormRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11include_questions\x18\x02 \x01(\bR\x10includeQuestions\"<\n" +
	"\x0fGetFormResponse\x12)\n" +
	"\x04form\x18\x01 \x01(\v2\x15.weladee.form.v1.FormR\x04form\"*\n" +
	"\x14GetFormBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"B\n" +
	"\x15GetFormBySlugResponse\x12)\n" +
	"\x04form\x18\x01 \x01(\v2\x15.weladee.form.v1.FormR\x04form\"\xf1\x06\n" +
	"\x11UpdateFormRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x125\n" +
	"\x05theme\x18\x04 \x01(\x0e2\x1a.weladee.form.v1.FormThemeH\x02R\x05theme\x88\x01\x01\x12&\n" +
	"\fis_published\x18\x05 \x01(\bH\x03R\visPublished\x88\x01\x01\x129\n" +
	"\x16is_accepting_responses\x18\x06 \x01(\bH\x04R\x14isAcceptingResponses\x88\x01\x01\x12(\n" +
	"\rrequire_login\x18\a \x01(\bH\x05R\frequireLogin\x88\x01\x01\x12A\n" +
	"\x1aallow_multiple_submissions\x18\b \x01(\bH\x06R\x18allowMultipleSubmissions\x88\x01\x01\x12T\n" +
	"\x12progress_bar_style\x18\t \x01(\x0e2!.weladee.form.v1.ProgressBarStyleH\aR\x10progressBarStyle\x88\x01\x01\x12<\n" +
	"\x18custom_thank_you_message\x18\n" +
	" \x01(\tH\bR\x15customThankYouMessage\x88\x01\x01\x12&\n" +
	"\fredirect_url\x18\v \x01(\tH\tR\vredirectUrl\x88\x01\x01\x12(\n" +
	"\rforce_captcha\x18\f \x01(\bH\n" +
	"R\fforceCaptcha\x88\x01\x01\x128\n" +
	"\bsettings\x18\r \x01(\v2\x17.google.protobuf.StructH\vR\bsettings\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_themeB\x0f\n" +
	"\r_is_publishedB\x19\n" +
	"\x17_is_accepting_responsesB\x10\n" +
	"\x0e_require_loginB\x1d\n" +
	"\x1b_allow_multiple_submissionsB\x15\n" +
	"\x13_progress_bar_styleB\x1b\n" +
	"\x19_custom_thank_you_messageB\x0f\n" +
	"\r_redirect_urlB\x10\n" +
	"\x0e_force_captchaB\v\n" +
	"\t_settings\"?\n" +
	"\x12UpdateFormResponse\x12)\n" +
	"\x04form\x18\x01 \x01(\v2\x15.weladee.form.v1.FormR\x04form\"#\n" +
	"\x11DeleteFormRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteFormResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc7\x03\n" +
	"\x10ListFormsRequest\x12B\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\".weladee.form.v1.PaginationRequestR\n" +
	"pagination\x12&\n" +
	"\fsearch_query\x18\x02 \x01(\tH\x00R\vsearchQuery\x88\x01\x01\x12*\n" +
	"\x0epublished_only\x18\x03 \x01(\bH\x01R\rpublishedOnly\x88\x01\x01\x129\n" +
	"\asort_by\x18\x04 \x01(\x0e2\x1b.weladee.form.v1.FormSortByH\x02R\x06sortBy\x88\x01\x01\x12B\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x1e.weladee.form.v1.FormSortOrderH\x03R\tsortOrder\x88\x01\x01\x12K\n" +
	"\rstatus_filter\x18\x06 \x01(\x0e2!.weladee.form.v1.FormStatusFilterH\x04R\fstatusFilter\x88\x01\x01B\x0f\n" +
	"\r_search_queryB\x11\n" +
	"\x0f_published_onlyB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_orderB\x10\n" +
	"\x0e_status_filter\"\x85\x01\n" +
	"\x11ListFormsResponse\x12+\n" +
	"\x05forms\x18\x01 \x03(\v2\x15.weladee.form.v1.FormR\x05forms\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.weladee.form.v1.PaginationResponseR\n" +
	"pagination\"$\n" +
	"\x12PublishFormRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x13PublishFormResponse\x12)\n" +
	"\x04form\x18\x01 \x01(\v2\x15.weladee.form.v1.FormR\x04form\".\n" +
	"\x13GetFormStatsRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\"H\n" +
	"\x14GetFormStatsResponse\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.weladee.form.v1.FormStatsR\x05stats\"\xf1\x02\n" +
	"\x15CreateQuestionRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.weladee.form.v1.QuestionTypeR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12\x1f\n" +
	"\vorder_index\x18\a \x01(\x05R\n" +
	"orderIndex\x121\n" +
	"\aoptions\x18\b \x01(\v2\x17.google.protobuf.StructR\aoptions\x12B\n" +
	"\x10validation_rules\x18\t \x01(\v2\x17.google.protobuf.StructR\x0fvalidationRules\"O\n" +
	"\x16CreateQuestionResponse\x125\n" +
	"\bquestion\x18\x01 \x01(\v2\x19.weladee.form.v1.QuestionR\bquestion\"\x81\x04\n" +
	"\x15UpdateQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.weladee.form.v1.QuestionTypeH\x00R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\x03 \x01(\tH\x01R\x05label\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12%\n" +
	"\vplaceholder\x18\x05 \x01(\tH\x03R\vplaceholder\x88\x01\x01\x12\x1f\n" +
	"\brequired\x18\x06 \x01(\bH\x04R\brequired\x88\x01\x01\x12$\n" +
	"\vorder_index\x18\a \x01(\x05H\x05R\n" +
	"orderIndex\x88\x01\x01\x126\n" +
	"\aoptions\x18\b \x01(\v2\x17.google.protobuf.StructH\x06R\aoptions\x88\x01\x01\x12G\n" +
	"\x10validation_rules\x18\t \x01(\v2\x17.google.protobuf.StructH\aR\x0fvalidationRules\x88\x01\x01B\a\n" +
	"\x05_typeB\b\n" +
	"\x06_labelB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_placeholderB\v\n" +
	"\t_requiredB\x0e\n" +
	"\f_order_indexB\n" +
	"\n" +
	"\b_optionsB\x13\n" +
	"\x11_validation_rules\"O\n" +
	"\x16UpdateQuestionResponse\x125\n" +
	"\bquestion\x18\x01 \x01(\v2\x19.weladee.form.v1.QuestionR\bquestion\"'\n" +
	"\x15DeleteQuestionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x17ReorderQuestionsRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12!\n" +
	"\fquestion_ids\x18\x02 \x03(\tR\vquestionIds\"4\n" +
	"\x18ReorderQuestionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*s\n" +
	"\n" +
	"FormStatus\x12\x1b\n" +
	"\x17FORM_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FORM_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15FORM_STATUS_PUBLISHED\x10\x02\x12\x16\n" +
	"\x12FORM_STATUS_CLOSED\x10\x03*\x95\x02\n" +
	"\tFormTheme\x12\x1a\n" +
	"\x16FORM_THEME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FORM_THEME_MINIMAL\x10\x01\x12\x17\n" +
	"\x13FORM_THEME_MIDNIGHT\x10\x02\x12\x14\n" +
	"\x10FORM_THEME_OCEAN\x10\x03\x12\x15\n" +
	"\x11FORM_THEME_SUNSET\x10\x04\x12\x15\n" +
	"\x11FORM_THEME_FOREST\x10\x05\x12\x17\n" +
	"\x13FORM_THEME_LAVENDER\x10\x06\x12\x16\n" +
	"\x12FORM_THEME_WELADEE\x10\a\x12\x15\n" +
	"\x11FORM_THEME_AURORA\x10\b\x12\x18\n" +
	"\x14FORM_THEME_CYBERPUNK\x10\t\x12\x15\n" +
	"\x11FORM_THEME_DESERT\x10\n" +
	"*\xc6\x03\n" +
	"\fQuestionType\x12\x1d\n" +
	"\x19QUESTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18QUESTION_TYPE_SHORT_TEXT\x10\x01\x12\x1b\n" +
	"\x17QUESTION_TYPE_LONG_TEXT\x10\x02\x12\x1a\n" +
	"\x16QUESTION_TYPE_DROPDOWN\x10\x03\x12\x1c\n" +
	"\x18QUESTION_TYPE_CHECKBOXES\x10\x04\x12\x17\n" +
	"\x13QUESTION_TYPE_EMAIL\x10\x05\x12\x17\n" +
	"\x13QUESTION_TYPE_PHONE\x10\x06\x12\x18\n" +
	"\x14QUESTION_TYPE_NUMBER\x10\a\x12\x16\n" +
	"\x12QUESTION_TYPE_DATE\x10\b\x12\x18\n" +
	"\x14QUESTION_TYPE_RATING\x10\t\x12\x1f\n" +
	"\x1bQUESTION_TYPE_OPINION_SCALE\x10\n" +
	"\x12\x18\n" +
	"\x14QUESTION_TYPE_YES_NO\x10\v\x12\x1d\n" +
	"\x19QUESTION_TYPE_FILE_UPLOAD\x10\f\x12\x15\n" +
	"\x11QUESTION_TYPE_URL\x10\r\x12\x18\n" +
	"\x14QUESTION_TYPE_MATRIX\x10\x0e\x12\x19\n" +
	"\x15QUESTION_TYPE_RANKING\x10\x0f*\xb1\x01\n" +
	"\x10ProgressBarStyle\x12\"\n" +
	"\x1ePROGRESS_BAR_STYLE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROGRESS_BAR_STYLE_NONE\x10\x01\x12\x1d\n" +
	"\x19PROGRESS_BAR_STYLE_LINEAR\x10\x02\x12\x1c\n" +
	"\x18PROGRESS_BAR_STYLE_STEPS\x10\x03\x12\x1f\n" +
	"\x1bPROGRESS_BAR_STYLE_CIRCULAR\x10\x04*\x9d\x01\n" +
	"\n" +
	"FormSortBy\x12\x1c\n" +
	"\x18FORM_SORT_BY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FORM_SORT_BY_UPDATED_AT\x10\x01\x12\x1b\n" +
	"\x17FORM_SORT_BY_CREATED_AT\x10\x02\x12\x16\n" +
	"\x12FORM_SORT_BY_TITLE\x10\x03\x12\x1f\n" +
	"\x1bFORM_SORT_BY_RESPONSE_COUNT\x10\x04*c\n" +
	"\rFormSortOrder\x12\x1f\n" +
	"\x1bFORM_SORT_ORDER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FORM_SORT_ORDER_ASC\x10\x01\x12\x18\n" +
	"\x14FORM_SORT_ORDER_DESC\x10\x02*\x95\x01\n" +
	"\x10FormStatusFilter\x12\"\n" +
	"\x1eFORM_STATUS_FILTER_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FORM_STATUS_FILTER_DRAFT\x10\x01\x12 \n" +
	"\x1cFORM_STATUS_FILTER_PUBLISHED\x10\x02\x12\x1d\n" +
	"\x19FORM_STATUS_FILTER_CLOSED\x10\x032\xdd\b\n" +
	"\vFormService\x12U\n" +
	"\n" +
	"CreateForm\x12\".weladee.form.v1.CreateFormRequest\x1a#.weladee.form.v1.CreateFormResponse\x12L\n" +
	"\aGetForm\x12\x1f.weladee.form.v1.GetFormRequest\x1a .weladee.form.v1.GetFormResponse\x12^\n" +
	"\rGetFormBySlug\x12%.weladee.form.v1.GetFormBySlugRequest\x1a&.weladee.form.v1.GetFormBySlugResponse\x12U\n" +
	"\n" +
	"UpdateForm\x12\".weladee.form.v1.UpdateFormRequest\x1a#.weladee.form.v1.UpdateFormResponse\x12U\n" +
	"\n" +
	"DeleteForm\x12\".weladee.form.v1.DeleteFormRequest\x1a#.weladee.form.v1.DeleteFormResponse\x12R\n" +
	"\tListForms\x12!.weladee.form.v1.ListFormsRequest\x1a\".weladee.form.v1.ListFormsResponse\x12X\n" +
	"\vPublishForm\x12#.weladee.form.v1.PublishFormRequest\x1a$.weladee.form.v1.PublishFormResponse\x12[\n" +
	"\fGetFormStats\x12$.weladee.form.v1.GetFormStatsRequest\x1a%.weladee.form.v1.GetFormStatsResponse\x12a\n" +
	"\x0eCreateQuestion\x12&.weladee.form.v1.CreateQuestionRequest\x1a'.weladee.form.v1.CreateQuestionResponse\x12a\n" +
	"\x0eUpdateQuestion\x12&.weladee.form.v1.UpdateQuestionRequest\x1a'.weladee.form.v1.UpdateQuestionResponse\x12a\n" +
	"\x0eDeleteQuestion\x12&.weladee.form.v1.DeleteQuestionRequest\x1a'.weladee.form.v1.DeleteQuestionResponse\x12g\n" +
	"\x10ReorderQuestions\x12(.weladee.form.v1.ReorderQuestionsRequest\x1a).weladee.form.v1.ReorderQuestionsResponseB*Z(github.com/weladee/weladee-form/proto/pbb\x06proto3"

var (
	file_proto_form_proto_rawDescOnce sync.Once
	file_proto_form_proto_rawDescData []byte
)

func file_proto_form_proto_rawDescGZIP() []byte {
	file_proto_form_proto_rawDescOnce.Do(func() {
		file_proto_form_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_form_proto_rawDesc), len(file_proto_form_proto_rawDesc)))
	})
	return file_proto_form_proto_rawDescData
}

var file_proto_form_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_form_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_form_proto_goTypes = []any{
	(FormStatus)(0),                  // 0: weladee.form.v1.FormStatus
	(FormTheme)(0),                   // 1: weladee.form.v1.FormTheme
	(QuestionType)(0),                // 2: weladee.form.v1.QuestionType
	(ProgressBarStyle)(0),            // 3: weladee.form.v1.ProgressBarStyle
	(FormSortBy)(0),                  // 4: weladee.form.v1.FormSortBy
	(FormSortOrder)(0),               // 5: weladee.form.v1.FormSortOrder
	(FormStatusFilter)(0),            // 6: weladee.form.v1.FormStatusFilter
	(*Question)(nil),                 // 7: weladee.form.v1.Question
	(*Form)(nil),                     // 8: weladee.form.v1.Form
	(*FormStats)(nil),                // 9: weladee.form.v1.FormStats
	(*CreateFormRequest)(nil),        // 10: weladee.form.v1.CreateFormRequest
	(*CreateFormResponse)(nil),       // 11: weladee.form.v1.CreateFormResponse
	(*GetFormRequest)(nil),           // 12: weladee.form.v1.GetFormRequest
	(*GetFormResponse)(nil),          // 13: weladee.form.v1.GetFormResponse
	(*GetFormBySlugRequest)(nil),     // 14: weladee.form.v1.GetFormBySlugRequest
	(*GetFormBySlugResponse)(nil),    // 15: weladee.form.v1.GetFormBySlugResponse
	(*UpdateFormRequest)(nil),        // 16: weladee.form.v1.UpdateFormRequest
	(*UpdateFormResponse)(nil),       // 17: weladee.form.v1.UpdateFormResponse
	(*DeleteFormRequest)(nil),        // 18: weladee.form.v1.DeleteFormRequest
	(*DeleteFormResponse)(nil),       // 19: weladee.form.v1.DeleteFormResponse
	(*ListFormsRequest)(nil),         // 20: weladee.form.v1.ListFormsRequest
	(*ListFormsResponse)(nil),        // 21: weladee.form.v1.ListFormsResponse
	(*PublishFormRequest)(nil),       // 22: weladee.form.v1.PublishFormRequest
	(*PublishFormResponse)(nil),      // 23: weladee.form.v1.PublishFormResponse
	(*GetFormStatsRequest)(nil),      // 24: weladee.form.v1.GetFormStatsRequest
	(*GetFormStatsResponse)(nil),     // 25: weladee.form.v1.GetFormStatsResponse
	(*CreateQuestionRequest)(nil),    // 26: weladee.form.v1.CreateQuestionRequest
	(*CreateQuestionResponse)(nil),   // 27: weladee.form.v1.CreateQuestionResponse
	(*UpdateQuestionRequest)(nil),    // 28: weladee.form.v1.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil),   // 29: weladee.form.v1.UpdateQuestionResponse
	(*DeleteQuestionRequest)(nil),    // 30: weladee.form.v1.DeleteQuestionRequest
	(*DeleteQuestionResponse)(nil),   // 31: weladee.form.v1.DeleteQuestionResponse
	(*ReorderQuestionsRequest)(nil),  // 32: weladee.form.v1.ReorderQuestionsRequest
	(*ReorderQuestionsResponse)(nil), // 33: weladee.form.v1.ReorderQuestionsResponse
	(*structpb.Struct)(nil),          // 34: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 35: google.protobuf.Timestamp
	(*PaginationRequest)(nil),        // 36: weladee.form.v1.PaginationRequest
	(*PaginationResponse)(nil),       // 37: weladee.form.v1.PaginationResponse
}
var file_proto_form_proto_depIdxs = []int32{
	2,  // 0: weladee.form.v1.Question.type:type_name -> weladee.form.v1.QuestionType
	34, // 1: weladee.form.v1.Question.options:type_name -> google.protobuf.Struct
	34, // 2: weladee.form.v1.Question.validation_rules:type_name -> google.protobuf.Struct
	34, // 3: weladee.form.v1.Question.settings:type_name -> google.protobuf.Struct
	35, // 4: weladee.form.v1.Question.created_at:type_name -> google.protobuf.Timestamp
	35, // 5: weladee.form.v1.Question.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: weladee.form.v1.Form.theme:type_name -> weladee.form.v1.FormTheme
	3,  // 7: weladee.form.v1.Form.progress_bar_style:type_name -> weladee.form.v1.ProgressBarStyle
	34, // 8: weladee.form.v1.Form.settings:type_name -> google.protobuf.Struct
	7,  // 9: weladee.form.v1.Form.questions:type_name -> weladee.form.v1.Question
	35, // 10: weladee.form.v1.Form.created_at:type_name -> google.protobuf.Timestamp
	35, // 11: weladee.form.v1.Form.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 12: weladee.form.v1.CreateFormRequest.theme:type_name -> weladee.form.v1.FormTheme
	3,  // 13: weladee.form.v1.CreateFormRequest.progress_bar_style:type_name -> weladee.form.v1.ProgressBarStyle
	7,  // 14: weladee.form.v1.CreateFormRequest.questions:type_name -> weladee.form.v1.Question
	34, // 15: weladee.form.v1.CreateFormRequest.settings:type_name -> google.protobuf.Struct
	8,  // 16: weladee.form.v1.CreateFormResponse.form:type_name -> weladee.form.v1.Form
	8,  // 17: weladee.form.v1.GetFormResponse.form:type_name -> weladee.form.v1.Form
	8,  // 18: weladee.form.v1.GetFormBySlugResponse.form:type_name -> weladee.form.v1.Form
	1,  // 19: weladee.form.v1.UpdateFormRequest.theme:type_name -> weladee.form.v1.FormTheme
	3,  // 20: weladee.form.v1.UpdateFormRequest.progress_bar_style:type_name -> weladee.form.v1.ProgressBarStyle
	34, // 21: weladee.form.v1.UpdateFormRequest.settings:type_name -> google.protobuf.Struct
	8,  // 22: weladee.form.v1.UpdateFormResponse.form:type_name -> weladee.form.v1.Form
	36, // 23: weladee.form.v1.ListFormsRequest.pagination:type_name -> weladee.form.v1.PaginationRequest
	4,  // 24: weladee.form.v1.ListFormsRequest.sort_by:type_name -> weladee.form.v1.FormSortBy
	5,  // 25: weladee.form.v1.ListFormsRequest.sort_order:type_name -> weladee.form.v1.FormSortOrder
	6,  // 26: weladee.form.v1.ListFormsRequest.status_filter:type_name -> weladee.form.v1.FormStatusFilter
	8,  // 27: weladee.form.v1.ListFormsResponse.forms:type_name -> weladee.form.v1.Form
	37, // 28: weladee.form.v1.ListFormsResponse.pagination:type_name -> weladee.form.v1.PaginationResponse
	8,  // 29: weladee.form.v1.PublishFormResponse.form:type_name -> weladee.form.v1.Form
	9,  // 30: weladee.form.v1.GetFormStatsResponse.stats:type_name -> weladee.form.v1.FormStats
	2,  // 31: weladee.form.v1.CreateQuestionRequest.type:type_name -> weladee.form.v1.QuestionType
	34, // 32: weladee.form.v1.CreateQuestionRequest.options:type_name -> google.protobuf.Struct
	34, // 33: weladee.form.v1.CreateQuestionRequest.validation_rules:type_name -> google.protobuf.Struct
	7,  // 34: weladee.form.v1.CreateQuestionResponse.question:type_name -> weladee.form.v1.Question
	2,  // 35: weladee.form.v1.UpdateQuestionRequest.type:type_name -> weladee.form.v1.QuestionType
	34, // 36: weladee.form.v1.UpdateQuestionRequest.options:type_name -> google.protobuf.Struct
	34, // 37: weladee.form.v1.UpdateQuestionRequest.validation_rules:type_name -> google.protobuf.Struct
	7,  // 38: weladee.form.v1.UpdateQuestionResponse.question:type_name -> weladee.form.v1.Question
	10, // 39: weladee.form.v1.FormService.CreateForm:input_type -> weladee.form.v1.CreateFormRequest
	12, // 40: weladee.form.v1.FormService.GetForm:input_type -> weladee.form.v1.GetFormRequest
	14, // 41: weladee.form.v1.FormService.GetFormBySlug:input_type -> weladee.form.v1.GetFormBySlugRequest
	16, // 42: weladee.form.v1.FormService.UpdateForm:input_type -> weladee.form.v1.UpdateFormRequest
	18, // 43: weladee.form.v1.FormService.DeleteForm:input_type -> weladee.form.v1.DeleteFormRequest
	20, // 44: weladee.form.v1.FormService.ListForms:input_type -> weladee.form.v1.ListFormsRequest
	22, // 45: weladee.form.v1.FormService.PublishForm:input_type -> weladee.form.v1.PublishFormRequest
	24, // 46: weladee.form.v1.FormService.GetFormStats:input_type -> weladee.form.v1.GetFormStatsRequest
	26, // 47: weladee.form.v1.FormService.CreateQuestion:input_type -> weladee.form.v1.CreateQuestionRequest
	28, // 48: weladee.form.v1.FormService.UpdateQuestion:input_type -> weladee.form.v1.UpdateQuestionRequest
	30, // 49: weladee.form.v1.FormService.DeleteQuestion:input_type -> weladee.form.v1.DeleteQuestionRequest
	32, // 50: weladee.form.v1.FormService.ReorderQuestions:input_type -> weladee.form.v1.ReorderQuestionsRequest
	11, // 51: weladee.form.v1.FormService.CreateForm:output_type -> weladee.form.v1.CreateFormResponse
	13, // 52: weladee.form.v1.FormService.GetForm:output_type -> weladee.form.v1.GetFormResponse
	15, // 53: weladee.form.v1.FormService.GetFormBySlug:output_type -> weladee.form.v1.GetFormBySlugResponse
	17, // 54: weladee.form.v1.FormService.UpdateForm:output_type -> weladee.form.v1.UpdateFormResponse
	19, // 55: weladee.form.v1.FormService.DeleteForm:output_type -> weladee.form.v1.DeleteFormResponse
	21, // 56: weladee.form.v1.FormService.ListForms:output_type -> weladee.form.v1.ListFormsResponse
	23, // 57: weladee.form.v1.FormService.PublishForm:output_type -> weladee.form.v1.PublishFormResponse
	25, // 58: weladee.form.v1.FormService.GetFormStats:output_type -> weladee.form.v1.GetFormStatsResponse
	27, // 59: weladee.form.v1.FormService.CreateQuestion:output_type -> weladee.form.v1.CreateQuestionResponse
	29, // 60: weladee.form.v1.FormService.UpdateQuestion:output_type -> weladee.form.v1.UpdateQuestionResponse
	31, // 61: weladee.form.v1.FormService.DeleteQuestion:output_type -> weladee.form.v1.DeleteQuestionResponse
	33, // 62: weladee.form.v1.FormService.ReorderQuestions:output_type -> weladee.form.v1.ReorderQuestionsResponse
	51, // [51:63] is the sub-list for method output_type
	39, // [39:51] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_proto_form_proto_init() }
func file_proto_form_proto_init() {
	if File_proto_form_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_form_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_form_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_form_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_form_proto_rawDesc), len(file_proto_form_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_form_proto_goTypes,
		DependencyIndexes: file_proto_form_proto_depIdxs,
		EnumInfos:         file_proto_form_proto_enumTypes,
		MessageInfos:      file_proto_form_proto_msgTypes,
	}.Build()
	File_proto_form_proto = out.File
	file_proto_form_proto_goTypes = nil
	file_proto_form_proto_depIdxs = nil
}
