// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseId    string                 `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText    *string                `protobuf:"bytes,4,opt,name=answer_text,json=answerText,proto3,oneof" json:"answer_text,omitempty"`
	AnswerNumber  *float64               `protobuf:"fixed64,5,opt,name=answer_number,json=answerNumber,proto3,oneof" json:"answer_number,omitempty"`
	AnswerDate    *string                `protobuf:"bytes,6,opt,name=answer_date,json=answerDate,proto3,oneof" json:"answer_date,omitempty"`
	AnswerTime    *string                `protobuf:"bytes,7,opt,name=answer_time,json=answerTime,proto3,oneof" json:"answer_time,omitempty"`
	AnswerChoices *structpb.Struct       `protobuf:"bytes,8,opt,name=answer_choices,json=answerChoices,proto3,oneof" json:"answer_choices,omitempty"`
	AnswerFileUrl *string                `protobuf:"bytes,9,opt,name=answer_file_url,json=answerFileUrl,proto3,oneof" json:"answer_file_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_proto_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Answer) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetAnswerText() string {
	if x != nil && x.AnswerText != nil {
		return *x.AnswerText
	}
	return ""
}

func (x *Answer) GetAnswerNumber() float64 {
	if x != nil && x.AnswerNumber != nil {
		return *x.AnswerNumber
	}
	return 0
}

func (x *Answer) GetAnswerDate() string {
	if x != nil && x.AnswerDate != nil {
		return *x.AnswerDate
	}
	return ""
}

func (x *Answer) GetAnswerTime() string {
	if x != nil && x.AnswerTime != nil {
		return *x.AnswerTime
	}
	return ""
}

func (x *Answer) GetAnswerChoices() *structpb.Struct {
	if x != nil {
		return x.AnswerChoices
	}
	return nil
}

func (x *Answer) GetAnswerFileUrl() string {
	if x != nil && x.AnswerFileUrl != nil {
		return *x.AnswerFileUrl
	}
	return ""
}

func (x *Answer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Response struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FormId           string                 `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	RespondentUserId *string                `protobuf:"bytes,3,opt,name=respondent_user_id,json=respondentUserId,proto3,oneof" json:"respondent_user_id,omitempty"`
	RespondentEmail  *string                `protobuf:"bytes,4,opt,name=respondent_email,json=respondentEmail,proto3,oneof" json:"respondent_email,omitempty"`
	RespondentName   *string                `protobuf:"bytes,5,opt,name=respondent_name,json=respondentName,proto3,oneof" json:"respondent_name,omitempty"`
	Completed        bool                   `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
	SubmittedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	Answers          []*Answer              `protobuf:"bytes,9,rep,name=answers,proto3" json:"answers,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *Response) GetRespondentUserId() string {
	if x != nil && x.RespondentUserId != nil {
		return *x.RespondentUserId
	}
	return ""
}

func (x *Response) GetRespondentEmail() string {
	if x != nil && x.RespondentEmail != nil {
		return *x.RespondentEmail
	}
	return ""
}

func (x *Response) GetRespondentName() string {
	if x != nil && x.RespondentName != nil {
		return *x.RespondentName
	}
	return ""
}

func (x *Response) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Response) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Response) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *Response) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AnswerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText    *string                `protobuf:"bytes,2,opt,name=answer_text,json=answerText,proto3,oneof" json:"answer_text,omitempty"`
	AnswerNumber  *float64               `protobuf:"fixed64,3,opt,name=answer_number,json=answerNumber,proto3,oneof" json:"answer_number,omitempty"`
	AnswerDate    *string                `protobuf:"bytes,4,opt,name=answer_date,json=answerDate,proto3,oneof" json:"answer_date,omitempty"`
	AnswerTime    *string                `protobuf:"bytes,5,opt,name=answer_time,json=answerTime,proto3,oneof" json:"answer_time,omitempty"`
	AnswerChoices *structpb.Struct       `protobuf:"bytes,6,opt,name=answer_choices,json=answerChoices,proto3,oneof" json:"answer_choices,omitempty"`
	AnswerFileUrl *string                `protobuf:"bytes,7,opt,name=answer_file_url,json=answerFileUrl,proto3,oneof" json:"answer_file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerInput) Reset() {
	*x = AnswerInput{}
	mi := &file_proto_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerInput) ProtoMessage() {}

func (x *AnswerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerInput.ProtoReflect.Descriptor instead.
func (*AnswerInput) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerInput) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AnswerInput) GetAnswerText() string {
	if x != nil && x.AnswerText != nil {
		return *x.AnswerText
	}
	return ""
}

func (x *AnswerInput) GetAnswerNumber() float64 {
	if x != nil && x.AnswerNumber != nil {
		return *x.AnswerNumber
	}
	return 0
}

func (x *AnswerInput) GetAnswerDate() string {
	if x != nil && x.AnswerDate != nil {
		return *x.AnswerDate
	}
	return ""
}

func (x *AnswerInput) GetAnswerTime() string {
	if x != nil && x.AnswerTime != nil {
		return *x.AnswerTime
	}
	return ""
}

func (x *AnswerInput) GetAnswerChoices() *structpb.Struct {
	if x != nil {
		return x.AnswerChoices
	}
	return nil
}

func (x *AnswerInput) GetAnswerFileUrl() string {
	if x != nil && x.AnswerFileUrl != nil {
		return *x.AnswerFileUrl
	}
	return ""
}

// RPC Requests/Responses
type SubmitResponseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FormId          string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	RespondentEmail *string                `protobuf:"bytes,2,opt,name=respondent_email,json=respondentEmail,proto3,oneof" json:"respondent_email,omitempty"`
	RespondentName  *string                `protobuf:"bytes,3,opt,name=respondent_name,json=respondentName,proto3,oneof" json:"respondent_name,omitempty"`
	Answers         []*AnswerInput         `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	Complete        bool                   `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	RecaptchaToken  *string                `protobuf:"bytes,6,opt,name=recaptcha_token,json=recaptchaToken,proto3,oneof" json:"recaptcha_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitResponseRequest) Reset() {
	*x = SubmitResponseRequest{}
	mi := &file_proto_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseRequest) ProtoMessage() {}

func (x *SubmitResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseRequest.ProtoReflect.Descriptor instead.
func (*SubmitResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitResponseRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *SubmitResponseRequest) GetRespondentEmail() string {
	if x != nil && x.RespondentEmail != nil {
		return *x.RespondentEmail
	}
	return ""
}

func (x *SubmitResponseRequest) GetRespondentName() string {
	if x != nil && x.RespondentName != nil {
		return *x.RespondentName
	}
	return ""
}

func (x *SubmitResponseRequest) GetAnswers() []*AnswerInput {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *SubmitResponseRequest) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *SubmitResponseRequest) GetRecaptchaToken() string {
	if x != nil && x.RecaptchaToken != nil {
		return *x.RecaptchaToken
	}
	return ""
}

type SubmitResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseResponse) Reset() {
	*x = SubmitResponseResponse{}
	mi := &file_proto_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseResponse) ProtoMessage() {}

func (x *SubmitResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponseResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitResponseResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponseRequest) Reset() {
	*x = GetResponseRequest{}
	mi := &file_proto_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseRequest) ProtoMessage() {}

func (x *GetResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseRequest.ProtoReflect.Descriptor instead.
func (*GetResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponseResponse) Reset() {
	*x = GetResponseResponse{}
	mi := &file_proto_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseResponse) ProtoMessage() {}

func (x *GetResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseResponse.ProtoReflect.Descriptor instead.
func (*GetResponseResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponseResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListResponsesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	CompletedOnly *bool                  `protobuf:"varint,3,opt,name=completed_only,json=completedOnly,proto3,oneof" json:"completed_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponsesRequest) Reset() {
	*x = ListResponsesRequest{}
	mi := &file_proto_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponsesRequest) ProtoMessage() {}

func (x *ListResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponsesRequest.ProtoReflect.Descriptor instead.
func (*ListResponsesRequest) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponsesRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ListResponsesRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListResponsesRequest) GetCompletedOnly() bool {
	if x != nil && x.CompletedOnly != nil {
		return *x.CompletedOnly
	}
	return false
}

type ListResponsesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*Response            `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponsesResponse) Reset() {
	*x = ListResponsesResponse{}
	mi := &file_proto_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponsesResponse) ProtoMessage() {}

func (x *ListResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponsesResponse.ProtoReflect.Descriptor instead.
func (*ListResponsesResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponsesResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *ListResponsesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponseRequest) Reset() {
	*x = DeleteResponseRequest{}
	mi := &file_proto_response_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponseRequest) ProtoMessage() {}

func (x *DeleteResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponseRequest.ProtoReflect.Descriptor instead.
func (*DeleteResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponseResponse) Reset() {
	*x = DeleteResponseResponse{}
	mi := &file_proto_response_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponseResponse) ProtoMessage() {}

func (x *DeleteResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponseResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponseResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ExportResponsesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponsesRequest) Reset() {
	*x = ExportResponsesRequest{}
	mi := &file_proto_response_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponsesRequest) ProtoMessage() {}

func (x *ExportResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponsesRequest.ProtoReflect.Descriptor instead.
func (*ExportResponsesRequest) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{11}
}

func (x *ExportResponsesRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *ExportResponsesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportResponsesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponsesResponse) Reset() {
	*x = ExportResponsesResponse{}
	mi := &file_proto_response_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponsesResponse) ProtoMessage() {}

func (x *ExportResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponsesResponse.ProtoReflect.Descriptor instead.
func (*ExportResponsesResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{12}
}

func (x *ExportResponsesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportResponsesResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportResponsesResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_proto_response_proto protoreflect.FileDescriptor

const file_proto_response_proto_rawDesc = "" +
	"\n" +
	"\x14proto/response.proto\x12\x0fweladee.form.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x12proto/common.proto\"\x8c\x04\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\tR\n" +
	"responseId\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\tR\n" +
	"questionId\x12$\n" +
	"\vanswer_text\x18\x04 \x01(\tH\x00R\n" +
	"answerText\x88\x01\x01\x12(\n" +
	"\ranswer_number\x18\x05 \x01(\x01H\x01R\fanswerNumber\x88\x01\x01\x12$\n" +
	"\vanswer_date\x18\x06 \x01(\tH\x02R\n" +
	"answerDate\x88\x01\x01\x12$\n" +
	"\vanswer_time\x18\a \x01(\tH\x03R\n" +
	"answerTime\x88\x01\x01\x12C\n" +
	"\x0eanswer_choices\x18\b \x01(\v2\x17.google.protobuf.StructH\x04R\ranswerChoices\x88\x01\x01\x12+\n" +
	"\x0fanswer_file_url\x18\t \x01(\tH\x05R\ranswerFileUrl\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_answer_textB\x10\n" +
	"\x0e_answer_numberB\x0e\n" +
	"\f_answer_dateB\x0e\n" +
	"\f_answer_timeB\x11\n" +
	"\x0f_answer_choicesB\x12\n" +
	"\x10_answer_file_url\"\xcf\x03\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aform_id\x18\x02 \x01(\tR\x06formId\x121\n" +
	"\x12respondent_user_id\x18\x03 \x01(\tH\x00R\x10respondentUserId\x88\x01\x01\x12.\n" +
	"\x10respondent_email\x18\x04 \x01(\tH\x01R\x0frespondentEmail\x88\x01\x01\x12,\n" +
	"\x0frespondent_name\x18\x05 \x01(\tH\x02R\x0erespondentName\x88\x01\x01\x12\x1c\n" +
	"\tcompleted\x18\a \x01(\bR\tcompleted\x12=\n" +
	"\fsubmitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x121\n" +
	"\aanswers\x18\t \x03(\v2\x17.weladee.form.v1.AnswerR\aanswers\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x15\n" +
	"\x13_respondent_user_idB\x13\n" +
	"\x11_respondent_emailB\x12\n" +
	"\x10_respondent_name\"\xa5\x03\n" +
	"\vAnswerInput\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12$\n" +
	"\vanswer_text\x18\x02 \x01(\tH\x00R\n" +
	"answerText\x88\x01\x01\x12(\n" +
	"\ranswer_number\x18\x03 \x01(\x01H\x01R\fanswerNumber\x88\x01\x01\x12$\n" +
	"\vanswer_date\x18\x04 \x01(\tH\x02R\n" +
	"answerDate\x88\x01\x01\x12$\n" +
	"\vanswer_time\x18\x05 \x01(\tH\x03R\n" +
	"answerTime\x88\x01\x01\x12C\n" +
	"\x0eanswer_choices\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x04R\ranswerChoices\x88\x01\x01\x12+\n" +
	"\x0fanswer_file_url\x18\a \x01(\tH\x05R\ranswerFileUrl\x88\x01\x01B\x0e\n" +
	"\f_answer_textB\x10\n" +
	"\x0e_answer_numberB\x0e\n" +
	"\f_answer_dateB\x0e\n" +
	"\f_answer_timeB\x11\n" +
	"\x0f_answer_choicesB\x12\n" +
	"\x10_answer_file_url\"\xcd\x02\n" +
	"\x15SubmitResponseRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12.\n" +
	"\x10respondent_email\x18\x02 \x01(\tH\x00R\x0frespondentEmail\x88\x01\x01\x12,\n" +
	"\x0frespondent_name\x18\x03 \x01(\tH\x01R\x0erespondentName\x88\x01\x01\x126\n" +
	"\aanswers\x18\x04 \x03(\v2\x1c.weladee.form.v1.AnswerInputR\aanswers\x12\x1a\n" +
	"\bcomplete\x18\x05 \x01(\bR\bcomplete\x12,\n" +
	"\x0frecaptcha_token\x18\x06 \x01(\tH\x02R\x0erecaptchaToken\x88\x01\x01B\x13\n" +
	"\x11_respondent_emailB\x12\n" +
	"\x10_respondent_nameB\x12\n" +
	"\x10_recaptcha_token\"O\n" +
	"\x16SubmitResponseResponse\x125\n" +
	"\bresponse\x18\x01 \x01(\v2\x19.weladee.form.v1.ResponseR\bresponse\"$\n" +
	"\x12GetResponseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x13GetResponseResponse\x125\n" +
	"\bresponse\x18\x01 \x01(\v2\x19.weladee.form.v1.ResponseR\bresponse\"\xb2\x01\n" +
	"\x14ListResponsesRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".weladee.form.v1.PaginationRequestR\n" +
	"pagination\x12*\n" +
	"\x0ecompleted_only\x18\x03 \x01(\bH\x00R\rcompletedOnly\x88\x01\x01B\x11\n" +
	"\x0f_completed_only\"\x95\x01\n" +
	"\x15ListResponsesResponse\x127\n" +
	"\tresponses\x18\x01 \x03(\v2\x19.weladee.form.v1.ResponseR\tresponses\x12C\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2#.weladee.form.v1.PaginationResponseR\n" +
	"pagination\"'\n" +
	"\x15DeleteResponseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteResponseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x16ExportResponsesRequest\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"f\n" +
	"\x17ExportResponsesResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType2\xf7\x03\n" +
	"\x0fResponseService\x12a\n" +
	"\x0eSubmitResponse\x12&.weladee.form.v1.SubmitResponseRequest\x1a'.weladee.form.v1.SubmitResponseResponse\x12X\n" +
	"\vGetResponse\x12#.weladee.form.v1.GetResponseRequest\x1a$.weladee.form.v1.GetResponseResponse\x12^\n" +
	"\rListResponses\x12%.weladee.form.v1.ListResponsesRequest\x1a&.weladee.form.v1.ListResponsesResponse\x12a\n" +
	"\x0eDeleteResponse\x12&.weladee.form.v1.DeleteResponseRequest\x1a'.weladee.form.v1.DeleteResponseResponse\x12d\n" +
	"\x0fExportResponses\x12'.weladee.form.v1.ExportResponsesRequest\x1a(.weladee.form.v1.ExportResponsesResponseB*Z(github.com/weladee/weladee-form/proto/pbb\x06proto3"

var (
	file_proto_response_proto_rawDescOnce sync.Once
	file_proto_response_proto_rawDescData []byte
)

func file_proto_response_proto_rawDescGZIP() []byte {
	file_proto_response_proto_rawDescOnce.Do(func() {
		file_proto_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_response_proto_rawDesc), len(file_proto_response_proto_rawDesc)))
	})
	return file_proto_response_proto_rawDescData
}

var file_proto_response_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_response_proto_goTypes = []any{
	(*Answer)(nil),                  // 0: weladee.form.v1.Answer
	(*Response)(nil),                // 1: weladee.form.v1.Response
	(*AnswerInput)(nil),             // 2: weladee.form.v1.AnswerInput
	(*SubmitResponseRequest)(nil),   // 3: weladee.form.v1.SubmitResponseRequest
	(*SubmitResponseResponse)(nil),  // 4: weladee.form.v1.SubmitResponseResponse
	(*GetResponseRequest)(nil),      // 5: weladee.form.v1.GetResponseRequest
	(*GetResponseResponse)(nil),     // 6: weladee.form.v1.GetResponseResponse
	(*ListResponsesRequest)(nil),    // 7: weladee.form.v1.ListResponsesRequest
	(*ListResponsesResponse)(nil),   // 8: weladee.form.v1.ListResponsesResponse
	(*DeleteResponseRequest)(nil),   // 9: weladee.form.v1.DeleteResponseRequest
	(*DeleteResponseResponse)(nil),  // 10: weladee.form.v1.DeleteResponseResponse
	(*ExportResponsesRequest)(nil),  // 11: weladee.form.v1.ExportResponsesRequest
	(*ExportResponsesResponse)(nil), // 12: weladee.form.v1.ExportResponsesResponse
	(*structpb.Struct)(nil),         // 13: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*PaginationRequest)(nil),       // 15: weladee.form.v1.PaginationRequest
	(*PaginationResponse)(nil),      // 16: weladee.form.v1.PaginationResponse
}
var file_proto_response_proto_depIdxs = []int32{
	13, // 0: weladee.form.v1.Answer.answer_choices:type_name -> google.protobuf.Struct
	14, // 1: weladee.form.v1.Answer.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: weladee.form.v1.Response.submitted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: weladee.form.v1.Response.answers:type_name -> weladee.form.v1.Answer
	14, // 4: weladee.form.v1.Response.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: weladee.form.v1.AnswerInput.answer_choices:type_name -> google.protobuf.Struct
	2,  // 6: weladee.form.v1.SubmitResponseRequest.answers:type_name -> weladee.form.v1.AnswerInput
	1,  // 7: weladee.form.v1.SubmitResponseResponse.response:type_name -> weladee.form.v1.Response
	1,  // 8: weladee.form.v1.GetResponseResponse.response:type_name -> weladee.form.v1.Response
	15, // 9: weladee.form.v1.ListResponsesRequest.pagination:type_name -> weladee.form.v1.PaginationRequest
	1,  // 10: weladee.form.v1.ListResponsesResponse.responses:type_name -> weladee.form.v1.Response
	16, // 11: weladee.form.v1.ListResponsesResponse.pagination:type_name -> weladee.form.v1.PaginationResponse
	3,  // 12: weladee.form.v1.ResponseService.SubmitResponse:input_type -> weladee.form.v1.SubmitResponseRequest
	5,  // 13: weladee.form.v1.ResponseService.GetResponse:input_type -> weladee.form.v1.GetResponseRequest
	7,  // 14: weladee.form.v1.ResponseService.ListResponses:input_type -> weladee.form.v1.ListResponsesRequest
	9,  // 15: weladee.form.v1.ResponseService.DeleteResponse:input_type -> weladee.form.v1.DeleteResponseRequest
	11, // 16: weladee.form.v1.ResponseService.ExportResponses:input_type -> weladee.form.v1.ExportResponsesRequest
	4,  // 17: weladee.form.v1.ResponseService.SubmitResponse:output_type -> weladee.form.v1.SubmitResponseResponse
	6,  // 18: weladee.form.v1.ResponseService.GetResponse:output_type -> weladee.form.v1.GetResponseResponse
	8,  // 19: weladee.form.v1.ResponseService.ListResponses:output_type -> weladee.form.v1.ListResponsesResponse
	10, // 20: weladee.form.v1.ResponseService.DeleteResponse:output_type -> weladee.form.v1.DeleteResponseResponse
	12, // 21: weladee.form.v1.ResponseService.ExportResponses:output_type -> weladee.form.v1.ExportResponsesResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_response_proto_init() }
func file_proto_response_proto_init() {
	if File_proto_response_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_response_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_response_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_response_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_response_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_response_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_response_proto_rawDesc), len(file_proto_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_response_proto_goTypes,
		DependencyIndexes: file_proto_response_proto_depIdxs,
		MessageInfos:      file_proto_response_proto_msgTypes,
	}.Build()
	File_proto_response_proto = out.File
	file_proto_response_proto_goTypes = nil
	file_proto_response_proto_depIdxs = nil
}
